### ISSUE TITLE
Excalidraw as Figma plugin

### ISSUE THREAD

**Issue by nikitavoloboev** [excalidraw/excalidraw#1035]
I often use [Figma](https://www.figma.com) for designing but also as a place for scratchpad style thinking and drawing although Figma does lack capability to do free form drawings and lots of excalidraw features.

I would love to build a plugin adds a block or something inside Figma that embeds Excalidraw inside it. To do free form drawing.

Would be cool if one can leverage Figma collaborative style editing to do editing on the Excalidraw embedded block too although that's probably impossible.

**Comment by dwelle** [comment]
Hi. No clue how Figma plugins work, so can't help. A few notes:

- There's an open PR to allow embedding of Excalidraw, so that might come in handy: https://github.com/excalidraw/excalidraw/pull/958
- Excalidraw currently doesn't allow free form drawings, either (if you meant non-bezier, free draw tool).

**Comment by lipis** [comment]
Do we really have a use case here.. I think it's either Figma or Excalidraw.. what's the point of doing Excalidraw inside Figma?

**Comment by joshuaiz** [comment]
I would love this feature too - in fact I came looking for it. 

The use case is being able to draw with Excalidraw within Figma without having to leave Figma. The point is to have your quick mock ups and more finished vector art all in one place.

I love using Excalidraw and while it is relatively easy to export, having it right in Figma means you can sketch something out to see some ideas and then move on to more detailed mock ups. 

Seems like a very common workflow that would be used by anyone who uses both Excalidraw and Figma.

**Comment by hinsencamp** [comment]
+1

**Comment by MaskyS** [comment]
+1, had the same idea today. Being able to draw rough mockups from within Figma (or elsewhere) and then creating Hi-Fi UI in Figma side by side would be terrific

**Comment by hydrosquall** [comment]
Hi, I made a Figjam widget for Excalidraw as I found myself copy-pasting screenshots regularly, you can find it here:  https://www.figma.com/community/widget/1047391719101881118

The nice thing about using Figjam instead of Figma is that there's a bidirectional relationship, so you can reopen your initial drawing without switching browser tabs just by clicking on it. In contrast, if you embedded an image in Figma via a Figma plugin, you wouldn't be able to edit your image as an Excalidraw file once it's been inserted.

**Comment by nikitavoloboev** [comment]
Thats an amazing plugin @hydrosquall 

Although I tried to install it but it's not showing in Figma Jam:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/6391776/144521474-051d0a4c-2a63-4003-9958-612a7bb699d6.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/6391776/144521515-1c80cdc9-d9d6-4c30-a2b1-dd47cc73c3b5.png">

**Comment by hydrosquall** [comment]
Ah I think it might be classified as a “widget” rather than a plugin  - not
sure if there may be plans to add a widget tab separate from plugins, but
in the meantime here’s the docs page.

https://help.figma.com/hc/en-us/articles/4410047809431-Use-widgets-in-FigJam-files

Let me know if you run into further issues, I can post a public Figjam file
for you to copy paste from if it might help.

**Comment by spoontstr** [comment]
> Do we really have a use case here.. I think it's either Figma or Excalidraw.. what's the point of doing Excalidraw inside Figma?

My usecase is to do click through prototypes of excalidraw style wireframes.  AFAICT Excalidraw does not allow prototyping.

**Comment by marekbrze** [comment]
I would love the SVG import of Excalidraw+ account sketches using the plugin. Excalidraw+ is perfect for gathering and enhancing ideas in the Lo-fi stage of the design process. Figma is perfect for doing high fidelity design based on those sketches.
