### ISSUE TITLE
Select filled elements by clicking inside

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#104]
Figma allows to select filled elements by clicking inside the element
![Screen Recording 2020-01-02 at 23 19 20](https://user-images.githubusercontent.com/9278185/71764277-b3709d80-2f07-11ea-94a6-f6bcfd79c259.gif)

**Comment by giovannigiordano** [comment]
This has been discussed in an issue with @vjeux and the #9 was created to avoid the selection on fill.
I think this can be closed, but let's wait him.

**Comment by vjeux** [comment]
We need two modes for enclosed shapes: with or without background. When there’s a background we want to make the hit to be the entire rectangle, otherwise just the edges

**Comment by jimthedev** [comment]
Hey there. One thing I'd suggest is to ignore background fill once someone has selected something and is now attempting to move it. Once they have selected it, allow them to drag it using any interior part of the selection. We get it, selection has to be tedious because there's a lot on the screen, but once I have my correct selection then I don't really want the mental work of evaluating if it has a background color or not to determine if I need to again use the precision of clicking the outline. I think it is ok to presume that I've selected the correct thing so moving it somewhere else should be a matter of clicking anywhere inside it (yes, including starting my drag inside the potentially transparent background).

**Comment by vjeux** [comment]
We now have the distinction between shapes with and without background. We should be able to implement this.

**Comment by dwelle** [comment]
I'm on it.
