### ISSUE TITLE
Undeletable content/session

### ISSUE THREAD

**Issue by dasblitz** [excalidraw/excalidraw#1072]
### Background:

So last week we used excalidraw to draw a board with goodbye messages for a collegue who had her last day, since we're all forced to work from home because of corona :( We kind of pushed it to the limits with over 20 participants, it was very unresponsive but in the end it was a nice goodbye gift :)
This week we have another collegue leaving and we wanted to do the same again. 

### The problem:

I opened excalidraw.com. The content from last week was still there somehow. I went and clicked the clear canvas button. The canvas was now empty. I created a share link and shared it with a collegue. As soon as my collegue joined the session all of the content of last week shows up again, on both our screens.

I've tried deleting my bowser history/sessions etc. But the content keeps coming back when I close and open excalidraw.com. I wonder if I'm doing something wrong.

### Expected behaviour:
Always see an empty canvas when I open excalidraw.com without a room hash

**Comment by dwelle** [comment]
> As soon as my collegue joined the session all of the content of last week shows up again, on both our screens.

This sounds eerily similar to what I warned about in https://github.com/excalidraw/excalidraw/pull/1036. I'll need to do a review if there is other code path that could trigger this, unrelated to the `this.socketInitialized`.

/cc @idlewinn

**Comment by dwelle** [comment]
Upon review, it's quite clear: since we're merging local & remote changes, if we unconditionally initialize from localStorage upon mount, we'll always end up emitting localStorage to remote users.

To solve this, we can either go back to @idlewinn's initial implem of passing the localStorage scene data to `initializeSocketClient()`.

But I'm now thinking: why should we do this at all? When you load a room via link, you expect that room's content to load. Since we can't do this since we don't persist the room state, why do we go from that to "load unrelated content"?

**Comment by vjeux** [comment]
This is an awesome use case! 

> it was very unresponsive but in the end it was a nice goodbye gift :)

We've done a lot of optimizations since then. Hopefully it should be a better experience now. If you could record a video and send to me in private (vjeuxx@gmail.com) if it reproduces that would that would be awesome. This way I can figure out where the bottlenecks are and come up with a plan to address them.

**Comment by dasblitz** [comment]
I'm having my own last working day next tuesday, so they might do the same for me. If they do, I'll see if I can record it. I could send you a version of the first drawing if that helps?
