### ISSUE TITLE
Feature: Assets/Component Library

### ISSUE THREAD

**Issue by parker-codes** [excalidraw/excalidraw#1091]
A good feature might be to have a component library to choose from, not just shapes. While having default components could be nice, I'm specifically thinking of my own components that I could reuse.

For example, I could have buttons, cards, image containers, etc that match the actual components I develop with. When I start a fresh Excalidraw session, I could immediately start using these to build my interface.

As far as how these are stored, the creators would have more insight, but here's my thoughts:

- Update the import tool to specify you are importing components (which accepts multiple files) - this way the existing canvas is not overridden; this would also mean that no persistent storage method is needed; to make updates to components, it has to be edited individually and then saved again; potentially a component could be updated in existing canvases if the same component is re-imported (based on name/id)
- Allow for categories (perhaps a part of the component metadata?) so that a popover drawer is easily usable
- Component instances could be individually modified as needed
- If a new component is added to a canvas, the easiest way to add it to existing components may be to select it with mouse and then export it (this is also the reason for using multiple files instead of one file to house all components)

Thanks for such a fantastic tool!

**Comment by dwelle** [comment]
This was discussed a few times, but it seems no tracking issue has been yet created. :+1:

**Comment by lipis** [comment]
Maybe some sort of plugin directory where people could add some info
- Author
- Component name
- Bunch of links to Excalidraw scenes

In Excalidraw app, we should be able to import to the existing scene other scenes via an Excalidraw link :)

Somehow integrate a plugin search and adding stars to the ones that we use the most or something among those lines. All data stored locally.. assuming that we don't want to build a backend for it just yet.

**Comment by google-mac** [comment]
@lipis While that sounds great and you would know more than me, would it make more sense to start with local components? Then build on top of that after for a community "store"?

I would not likely go for many components from others because my team has specific design requirements for our sites.

**Comment by kbariotis** [comment]
It would be nice to have a preset of icons to use on our diagrams. Some examples could be:

- a user icon
- a data store icon
- a server icon
- a cog icon
- etc

Next step could be to have icons of existing services, like AWS/GCP icons to use while drawing such architectures.

Now for the first set of icons, in order to make them feel more hand-drawn we could do some of our own (using rough.js) and have them as presets. For the second set of existing services could be trickier but something for the future maybe.

If we do predefine the first of set of icons on our own, we could even have them respect current font, so a user icon could be drawn with the current scene font style.

What do you think?

Example:
![image](https://user-images.githubusercontent.com/605742/80276313-db1a8a00-86df-11ea-9c8a-3c899bb242f6.png)

**Comment by petehunt** [comment]
I have a working prototype of this locally, but I'm not happy about the UX I came up with.

Here's a sketch of how it currently works. Definitely looking for feedback on how it could be better.

https://excalidraw.com/#json=4859963037974528,ZVR_UO8h1E-fRBM2wGX19g

**Comment by dwelle** [comment]
I think the popup menu should open to the right, similar to our shape-properties menu that opens to the left. This way, you can keep it open while you arrange/modify the components you drop on the canvas.

For the same reason, it might also be a good idea not to make the asset into another tool, so that you can keep the menu open for a longer period of time (that is, if your prototype currently works in a way so it closes when you change tools).

**Comment by pA1nD** [comment]
A easier way to handle component imports would be amazing.

I see this feature has two aspects which would make it useful:
1) Allow the community to create and share polished templates (probably there would be a page or multiple with excalidraw components very soon) e.g. there is https://tailwindcomponents.com/ and https://www.tailwindtoolbox.com/ for community made resources for tailwindcss.

Miro has launched Miroverse a while ago: https://miro.com/miroverse/ and it is incredible useful to be able to "import" something over and over again.

2) Have my own coponents.

Also interesting is how draw.io (now diagram.net) handles components. You can create a component from any group of elements (very similar to figma) and store them as a component to reuse it later. You can then load multiple component libraries (default or own ones).
https://www.diagrams.net/blog/custom-libraries

**Comment by dai-shi** [comment]
For @pA1nD and someone interested, I made an experimental external tool for this purpose in mind (but not yet really usable for this purpose).
Repo: https://github.com/dai-shi/excalidraw-gallery
Tool: https://dai-shi.github.io/excalidraw-gallery/
How to use: https://twitter.com/dai_shi/status/1266309261316943873

**Comment by hedythedev** [comment]
A related feature would be to have a templates gallery so you can start drawing with a template instead of starting from scratch.

Related to: #1863

**Comment by dai-shi** [comment]
Apart from how we would share the templates, how would it be different from loading a file (or a link)?

Ex: https://excalidraw.com/#json=5079026368512000,ZEdA1CP3wBBhG-MT0NgstQ Is this a template you imagine?

**Comment by hedythedev** [comment]
Yes something like that and we have a gallery full of templates similar to those, now I think this might overlap with components gallery...

**Comment by dwelle** [comment]
Closing as implemented. For follow ups, see https://github.com/excalidraw/excalidraw/issues/1904
