### ISSUE TITLE
Don't assume keyboard input device attached

### ISSUE THREAD

**Issue by emilsjolander** [excalidraw/excalidraw#1125]
Excalidraw currently works great on devices such as laptops where a keyboard can be assumed present. However it doesn't work as well on devices such as iPad where a keyboard isn't always available. The most obvious to me being that there is currently no way to delete an object without keyboard with a backspace key connected.

I would suggest implementing a UI strategy where all features should be present as clickable (or touchable) UI elements, and view keyboard input as options and only there to provide a faster way to do what is possible by clicking around the UI.

**Comment by vjeux** [comment]
cc @j-f1 as you built all of those for mobile

**Comment by j-f1** [comment]
Interesting. This is definitely a core principle of macOS, where context menus are totally optional. Not sure how to best integrate this without over complicating the UI when a keyboard is attached. Maybe a button to open the context menu? Part of the problem here is that the iPad is too big to have the mobile UI.

**Comment by vjeux** [comment]
What about two additional buttons at the bottom of the edit menu: duplicate and delete. Should be small enough and be useful

**Comment by lipis** [comment]
Delete was added.. we just need duplicate now. I'll open a new issue for it.

**Comment by emilsjolander** [comment]
Thanks!
