### ISSUE TITLE
Commit text on cmd/ctrl+enter

### ISSUE THREAD

**Issue by j-f1** [excalidraw/excalidraw#1166]
Just like the message editor on GitHub does

**Comment by blankyao** [comment]
发送到发送到

**Comment by haikyuu** [comment]
## History:
@vjeux had an idea https://github.com/excalidraw/excalidraw/issues/1158 to commit texts on `enter` click. And it was implemented within 2 days.

In those two days, i was frustrated because there was no way to commit a text item without clicking on `esc` and selecting it again. 

While i was thinking of opening an issue to complain, i thought it would be faster to make a PR 😂
#1185 

I think shift/cmd is better. But it's my personal preference ...

**Comment by lipis** [comment]
Oups I was too fast to merge it.. felt OK :) So let's have a follow up if needed.

**Comment by haikyuu** [comment]
no @lipis it's ok. Let's discuss this further but keep it merged 😆

**Comment by lipis** [comment]
> i was frustrated because there was no way to commit a text

I hope you are less frustrated now, during these difficult times :)

**Comment by haikyuu** [comment]
Yes, i am. Thanks @lipis

**Comment by j-f1** [comment]
Why is this closed @lipis?

**Comment by dwelle** [comment]
@j-f1 fixed via https://github.com/excalidraw/excalidraw/pull/1185 with a followup https://github.com/excalidraw/excalidraw/pull/1188
