### ISSUE TITLE
Export broken

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#118]
Export is broken (again), I believe due to the introduction of the (infinite) scrolling to the canvas.

(will fix tomorrow unless someone wants to take it on, sooner).

Possibly blocked by #117

**Comment by vjeux** [comment]
Since we have infinite scrolling, I don't think that the "visible area" setting makes sense anymore, we should always crop to where elements are. I also think that hardcoding 10px is fine. So that's two less options that currently clutter the UI.

Last one is background. I think both use cases are useful. I would err on the side on having a background by default, it's a bit annoying when it's transparent, but idk.

**Comment by Fausto95** [comment]
Sketch.app has an “export selection” feature, it’d be nice if we had something similar

**Comment by dwelle** [comment]
> Since we have infinite scrolling, I don't think that the "visible area" setting makes sense anymore, we should always crop to where elements are. I also think that hardcoding 10px is fine. So that's two less options that currently clutter the UI.

Agreed.

> Last one is background. I think both use cases are useful. I would err on the side on having a background by default, it's a bit annoying when it's transparent, but idk.

Yup.

> Sketch.app has an “export selection” feature, it’d be nice if we had something similar

Yea. We'll leave this for later because [we might want](https://github.com/excalidraw/excalidraw/issues/27#issuecomment-570222613) to introduce artboards, instead.
