### ISSUE TITLE
Shape should preserve last shape (better Shape Lock behavior)

### ISSUE THREAD

**Issue by mbj36** [excalidraw/excalidraw#1206]
After we select shape and draw, we have to select again to use same shape and its annoying.

**Comment by dai-shi** [comment]
How would one know about `Q` without reading code/doc?

**Comment by mbj36** [comment]
Oh that's lock icon is confusing then. To me, it seems first that it's for locking the whole whiteboard (means not allowed to edit when locked)

**Comment by dai-shi** [comment]
That's what I actually thought too. (especially with collaboration)

**Comment by lipis** [comment]
Hmm.. interesting.

**Comment by dwelle** [comment]
Yea, we should think about how to make this more obvious.

As for how to find out the `Q` hotkey. Two ways:

1. when you over over the icon, it shows the tooltip with a not-so-obvious hint for the hotkey:

     ![image](https://user-images.githubusercontent.com/5153846/78422552-60ba9500-7660-11ea-9fb9-138ae20d6280.png)

2. as @dai-shi mentioned, we have a document listing our hotkeys: https://github.com/excalidraw/excalidraw/blob/master/docs/shortcuts.md

**Comment by dai-shi** [comment]
Well, I didn't notice either of them, tbh. I only knew it by clicking the lock icon and try the behavior. I think I'd want `Q` at the right bottom of the lock icon, but it's not a very strong suggestion.

**Comment by lipis** [comment]
My opinion (and I expressed it before) is to remove this button and have the locked behaviour as default! Less things to care about and usually that's how Photoshop does it.. you select one tool and you work with it until you select something else..

Maybe with an ESC when nothing is selected it should go to Selection mode.. but other than that I think we can switch.

**Comment by dwelle** [comment]
@lipis that was my original sentiment, too https://github.com/excalidraw/excalidraw/issues/41. But Figma does it the way we do (and as @vjeux noted, PowerPoint and Keynote supposedly does that -- though they're not in the exact ballpark we're in).

**Comment by lipis** [comment]
We can do it our way :D

(Again no strong opinion here, it's just my opinion. Either way people are confused on how to use and what the lock does.)

**Comment by dwelle** [comment]
> Again no strong opinion here, it's just my opinion.

Yea, I have no strong opinion on this either.

> Either way people are confused on how to use and what the lock does.

Absolutely.

IMO we should either align to how most (established) apps similar to us do it (e.g. Figma) -- because that's where most our users will likely come from. Or do what we think makes most sense.

But, like you said --- we don't necessarily need to copy others, because we have our own vision on how to do things.

**Comment by dwelle** [comment]
Reconsidering my position, I vote for keep current shape active by default, because that's how everything I used throughout my life worked like, so it's the most intuitive behavior for me personally.

BUT --- here's the caveat.

If we do this, I think we should allow modifications (resizing, or even selecting) even with non-selection tool, because often after creation you want to quickly edit the shape or move it.

Here's Affinity Designer:

![affinity_create_and_modify](https://user-images.githubusercontent.com/5153846/78426528-00cde980-7674-11ea-815d-f73f1a83b409.gif)

**Comment by dwelle** [comment]
https://mobile.twitter.com/kviglucci/status/1246515980521689094

**Comment by vjeux** [comment]
Interesting @dwelle, so this means that while a shape is active, you can also select other elements?

**Comment by dwelle** [comment]
@vjeux yep. You can do pretty much all the things you can do with `selection` tool, except drag-select.

I don't think there's much downside to this hybrid mode. We'd of course retain `selection`. This would just be a bonus that would improve the UX if we switched to "keep shape active after creation" by default.

**Comment by lipis** [comment]
We are sticking to current behaviour for now. Maybe this is related #2458
