### ISSUE TITLE
Clear canvas doesn't clear the stored elements

### ISSUE THREAD

**Issue by kbariotis** [excalidraw/excalidraw#1234]
Clearing the canvas doesn't clear the stored elements.

If you have X elements in your scene and clear the canvas and create a new element, the next broadcast will include X+1 elements.

This can cause the connection to lag, even though you are sure you have a clear canvas.

**Comment by kbariotis** [comment]
K I see, the [elements are being marked as deleted.](https://github.com/excalidraw/excalidraw/blob/master/src/actions/actionCanvas.tsx#L39-L45). My knowledge is limited there and I wonder if these deleted elements should be included when we broadcast the scene information.

**Comment by dwelle** [comment]
Yes, the reason to keep deleted elements in the array is so that they can be broadcasted in collab. At first, we were just syncing a list of deleted ids, but then decided to keep them in the array and just mark them as `isDeleted: true`.

**Comment by kbariotis** [comment]
@dwelle why do we want them to be broadcasted in collab though?

**Comment by dwelle** [comment]
We need to tell other clients to delete their local elements when we delete them remotely. That can be implemented in many ways, but we arrived at using the tombstone pattern in form of setting them as `isDeleted: true`.

Using fully-qualified tombstone elements instead of a list may prove useful later when we fix undo/redo to work with collab. That way when you delete an element locally, it's synced and the remote client will be able to replay the history to arrive at the same state from which they can then undo the deletion (if desired) and sync it back.

Technically, this could be accomplished using other-than-tombstones pattern, but arguably would require custom logic.

There may be other cases.

@petehunt would be able to explain this better.

**Comment by kbariotis** [comment]
@dwelle thanks for explaining, I'm still trying to wrap my head around the collaboration algorithm.

I think a great resource for algorithms like these is (Operational transformation](https://en.wikipedia.org/wiki/Operational_transformation), def something we can learn from.

**Comment by dwelle** [comment]
OT often uses tombstones as well.

Also check our collab blog post https://blog.excalidraw.com/building-excalidraw-p2p-collaboration-feature/

**Comment by kbariotis** [comment]
@dwelle if I'm not mistaken, at the moment on every scene update, the whole scene is being transmitted and consolidation happens in each clients' end.

OT, on the other hand, transmits only each individual action and tries to transform it against all previously executed actions before applying them (everything is based on time and the correct order of each action).

**Comment by kbariotis** [comment]
@dwelle to come back to the issue in hand though, I would argue that the Clear Canvas command doesn't have to keep the original state. It can be a distinct event, that will wipe out the local state and also wipe out all clients' state.

**Comment by dwelle** [comment]
> OT, on the other hand, transmits only each individual action and tries to transform it against all previously executed actions before applying them (everything is based on time and the correct order of each action).

Yes. We went with sync-everything for now because it's much easier than implementing OT or similar algorithm. When Excalidraw much more mature we can start optimizing on this front, for sure.

> I would argue that the Clear Canvas command doesn't have to keep the original state. It can be a distinct event, that will wipe out the local state and also wipe out all clients' state.

Locally, yes. In collab we'd again arrive at the problem of synchronization. Even if we created a custom `CLEAR_CANVAS` event, there would be a race condition where a remote client could sync to you the elements you just deleted before the `CLEAR_CANVAS` message would get to them.

**Comment by dwelle** [comment]
Also note that to my knowledge collab OT cannot be implemented without a server as a mediator, and our server cannot read data due to end-to-end encryption. So we'd need to go with [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) which is much more complex to implement.

**Comment by johnwebbcole** [comment]
@jorendorff has a nice RGA implementation at https://github.com/jorendorff/peeredit/blob/master/lib/rga.js and a talk to go along with it https://github.com/jorendorff/talks/blob/master/textarea-distributed/textarea-distributed.md

I've used this implementation in a hackathon multiplayer editor demo.  The explanation of how you are storing an array of Exalidraw objects sounds like it could translate nicely into an RGA.
