### ISSUE TITLE
Throw an error when someone pastes an SVG

### ISSUE THREAD

**Issue by roxanagherle** [excalidraw/excalidraw#1252]
As per discussion in https://github.com/excalidraw/excalidraw/pull/1250, now that we support copying to clipboard as SVG, we should throw an error when someone tries to paste an SVG into excalidraw since that won't render nicely.

**Comment by dwelle** [comment]
Since we're allowing to paste arbitrary text into excalidraw as text elements, and our copy-as-SVG currently copies the SVG as plaintext to clipboard, we can't determine whether user doesn't want to in fact paste an SVG-plaintext as a text element.

If we really want to prevent pasting the SVG text copied from excalidraw, we can prepend `<-- source:excalidraw -->` to the SVG text copied to clipboard and match against this on paste.

But I'm thinking whether we should, per @vjeux' philosophy of letting users do whatever they want. Thoughts?
