### ISSUE TITLE
Allow naming .excalidraw file before download

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1271]
*Edit: This is now more about how to name the .excalidraw file, we don't want to add naming as suggested originally*

*Edit: Original suggestion:*

Something like this (design can be improved of course):

<img width="266" alt="Screenshot 2020-04-06 at 2 16 50 PM" src="https://user-images.githubusercontent.com/125676/78553115-6d321f80-7811-11ea-97a6-56fdf3e68aed.png">

I'm often just downloading the file and renaming it later, without going into the export dialog.. because I want to download it as .excalidraw and this option doesn't even exist there.

Also if we make that change, we should even consider starting with just `Untitled` instead of `excalidraw-123456789`, as the word excalidraw is already in the file extension.

**Comment by vjeux** [comment]
This was the initial proposal for the title but I vetoed it. Naming is a big cognitive load and I don’t want the first thing in the UI to be about it.

**Comment by lipis** [comment]
I see, asking for a name before downloading it's also a bad UX.. dunno :) If we make it a bit gray or something?! :D

**Comment by j-f1** [comment]
What if we made a share button there that opened a popup with buttons for sharing a link, saving, and exporting? That would enable there to be a reasonable place to add the text field and clear up a couple of spots on the top bar for new features.

**Comment by xixixao** [comment]
@dai-shi I just tried and it seems like there is a Save-as dialog (at least on MacOS), so I guess this can be closed?

**Comment by dai-shi** [comment]
@lipis ?

**Comment by lipis** [comment]
Sure..

**Comment by eric-schleicher** [comment]
Am trying to understanding the intended behavior which seem counter intuitive from what most document oriented systems facilitate.  

Right now the UI automatically generated name is proposed as `Untitled-${ISO_DATE}`, an evaluated (template) value? It seems however that it does ***only*** this and it's not possible to allow this to be set by user for UX complexity reasons?   Checking because the consequence is that if the user wants to name the file the same they must re-type the desired name each repeatedly (every time a save?)  

Is that the case?

The naming approach implies that the string literal for `Untitled` could also  be templatized, and a reasonable place for it to be stored in the localStorage, DOM and/or document state where it could be checked/loaded as a very limited change without new IA or UI.

If there isn't any interested in adding this functionality in the user interface; would a pull request we entertained to allow for a default value to be set in local storage or in the excalidraw dom/json representation?  

In looking through the json schema, there isn't a name property for the board and if adding a proper 'name' value is controversial; a default value object/entry could be stored in the files collection to and allow this functionality to exist without having to build new UI patterns or sledgehammering a browser plugin to hijack the dom.

![image](https://github.com/excalidraw/excalidraw/assets/8261783/79db2e53-fd2d-4a25-98ac-0a2703925133)
