### ISSUE TITLE
Resizing curved lines from W/N doesn't fix E/S

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1275]
We would probably need to fix this before continuing #1218.
This behavior existed before we added rotation support.

![exdraw19](https://user-images.githubusercontent.com/490574/78560836-a7231600-7851-11ea-9254-cdd53fbf49f1.gif)

**Comment by dai-shi** [comment]
For rotated curved lines, this happens for all directions.

**Comment by dai-shi** [comment]
This is far more complicated than I expected.
We need to calculate the real width/height of a curved line on the fly.

@pshihn Is there a way to get the curved paths without generating an element?

**Comment by pshihn** [comment]
@dai-shi If you want to **exact** size, it is a bit tricky because of randomness at play in every shape generation. you can call `generator.curve` to create a rough shape without actually drawing it. [e.g here](https://github.com/excalidraw/excalidraw/blob/6abcb2d87f777d5be5fb7657dfcec62b3f924758/src/renderer/renderElement.ts#L255) and then use the function already being used in excalidraw to get the bounds. 

If you want a "close enough but fast" size, i recently published. a package which lets you get the points on a curve (https://github.com/pshihn/bezier-points#curvetobezierpointsin-point-point). You pass in all the element points, and you get the points on the curve. You can use min/max to get the dimensions. 

Hope it helps a little bit. It's strange that the other ends moves this much though when resizing. Not sure how the resize code is written. Perhaps a fresher look might help.

**Comment by dai-shi** [comment]
@pshihn Thanks. I need the exact size for this issue. So, I'd call `generator.curve` with random seed. The `generator` seems to base on a class instance. Can it be called just as a function?

As I noted, this behavior existed before I made any modification. I almost know how to fix it, it just requires the exact size.

**Comment by pshihn** [comment]
you can create a generator from rough:

```
import rough from "roughjs/bin/rough";

const gen = rough.generator();
gen.curve(points, options);
```

or if you have the instance of RoughCanvas available, you can get it from it, e.g. here: https://github.com/excalidraw/excalidraw/blob/6abcb2d87f777d5be5fb7657dfcec62b3f924758/src/renderer/renderElement.ts#L325
