### ISSUE TITLE
applyResizeArrowFn to be position based (no lastX)

### ISSUE THREAD

**Issue by jquintozamora** [excalidraw/excalidraw#1339]
Apply the same approach we used in #1330 but for `arrow` and `line` elements.
Once that's done we will not need to use `lastX` and `lastY` anymore for resize. So that will clean up the code.

**Comment by dai-shi** [comment]
I want this weird behavior fixed too. Maybe it's not for this issue, though, it's related.

![exdraw25](https://user-images.githubusercontent.com/490574/78983073-71867180-7b5e-11ea-80fa-e00e7f662e1f.gif)

**Comment by dai-shi** [comment]
I would like to fix this gap between pointer and the handle.
But, that would lead to the suboptimal behavior (#1506).

![exdraw37](https://user-images.githubusercontent.com/490574/81402925-4860fd00-916d-11ea-85a7-d33bdb593714.gif)

**Comment by dwelle** [comment]
IMO current behavior is fine.. wouldn't over-engineer it. But if that would go against #1506, then we shouldn't do that anyway.

**Comment by dai-shi** [comment]
Well, I agree that we don't agree with it. I feel like the current behavior is worse than #1506. (but less worse in the case of normal elements because we don't have shift-ratio-locking.) Anyway, my motivation was more to clean up the code and avoid using too many states.

To avoid going against #1506, I would need to change the handle position of two-points lines/arrows. Maybe, we don't need the dashed rectangle. They look like breaking changes in UI. Let's wait until we find a resolution in #1506. Meanwhile, I'd tackle part of #1218 without this fix.

**Comment by dai-shi** [comment]
Hm, I may change my mind. The current absolute positioning isn’t very mobile friendly. I’d explore dynamic pointerOffset. It’ll be something you like.
