### ISSUE TITLE
Do not show export dialog if there are no elements in the scene

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1349]

**Comment by Fausto95** [comment]
https://github.com/excalidraw/excalidraw/pull/1034#issuecomment-602275958
@dwelle also pointed it

**Comment by dwelle** [comment]
While for export (instead of save-file) it makes more sense, I think it's better instead of hiding it to render a message "cannot export empty canvas" when you open it.

Reasons:

- Discoveribility: new users may want to go through what Excalidraw can do, and on empty scenes it would not show export which isn't good. 
- Menu buttons jumping in and out.

**Comment by lipis** [comment]
My intention wasn't to hide the button, but the Export dialog it self.. showing some sort of message when the user presses export.

**Comment by dwelle** [comment]
I see, yea that makes more sense. Wouldn't you say disabling the buttons and showing the error message in place of scene preview is better, so that users can gauge what they can do in Excalidraw?

But maybe for sake of not complicating it, we can go with your proposal.

**Comment by lipis** [comment]
we don't have the disabled button state anywhere else.. so it's more work.

**Comment by vjeux** [comment]
What’s wrong with exporting an empty canvas? Just going to be a 1x1 white pixel. Why special case it in the UI?

**Comment by lipis** [comment]
fair enough..

**Comment by dwelle** [comment]
We can't export empty canvas as there are several APIs along the way that would throw. Currently we're showing a prompt on such an export.
