### ISSUE TITLE
VSCode Webview

### ISSUE THREAD

**Issue by jaredpalmer** [excalidraw/excalidraw#1377]
There is a new custom editor webview api in preview for VSCode that could be of interest: https://code.visualstudio.com/api/extension-guides/custom-editors

Use case would be to edit excalidraw images in VSCode without leaving the editor. Also being able to keep the same file name would be cool.

Example Custom Editor for Asciiflow2: 
https://github.com/zenghongtu/vscode-asciiflow2

**Comment by kbariotis** [comment]
We tried to do Excalidraw as [an embedded document](https://github.com/excalidraw/excalidraw/pull/958) which might be the same case here.

I love the idea.

**Comment by brijeshb42** [comment]
@jaredpalmer Basic implementation - https://marketplace.visualstudio.com/items?itemName=brijeshb42.vscode-excalidraw
More feature and fixes to be added. You can't edit multiple excalidraw files at once right now.

**Comment by brijeshb42** [comment]
@kbariotis The marketplace has the link for the extension repo and the extension itself embeds a forked and slightly modified version of excalidraw which is also under my account on github.

**Comment by brijeshb42** [comment]
Changes in the core itself would be best so that the hosted version of excalidraw can also be integrated as an option.

**Comment by Jan-M** [comment]
https://github.com/jkchao/vscode-excalidraw#readme
This one works well for me, bit odd on the save flow, but up to date including "binding".

**Comment by davidnussio** [comment]
I forked brijeshb42/vscode-excalidraw and tested it with package @excalidraw/excaldraw instead of the patched version.

I'am tried to wire most excalidraw functionality and It is not so bad.
Sometimes there is "focus" problem and keyboard commands doesn't work until you click on, for example, selection icon. The problem could be with the iframe, I will test without it.
I like the idea to have the same experience as the web on vscode but the easy to open files from filesystem.

https://www.youtube.com/watch?v=6diPhnSlX-M

**Comment by pomdtr** [comment]
The [excalidraw extension](https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor) is know available in the VS Code marketplace.
