### ISSUE TITLE
Zoom reset point should be attribute of canvas content

### ISSUE THREAD

**Issue by OrenMe** [excalidraw/excalidraw#1399]
Excalidraw is meant to be an endless virtual whiteboard.
Today zoom is an attribute of the fixed screen scale to 1.
I suggest that there will be no fixed zoom scale and that we will have a reset to view that takes into account all the area with elements in the canvas with some margin for top-bottom and right-left.

For example, if we have initial element like this:
![image](https://user-images.githubusercontent.com/5461862/79065210-44010b80-7cb7-11ea-87ff-34241385881a.png)

And then we move the view to the right and paint another rectangle:

![image](https://user-images.githubusercontent.com/5461862/79065213-609d4380-7cb7-11ea-9a03-c308b41fcc74.png)

Now, there's no way to say "show all elements on screen", and a user needs to zoom out to some zoom scale.

What I mean is that we need to be able to have this view happen in a programatic way:
![image](https://user-images.githubusercontent.com/5461862/79065235-93473c00-7cb7-11ea-98a2-06b77818dd25.png)

Some considerations:
* We might want to limit the scale out of a view, or not...
* we might need to rethink zoom as there's no notion of percentage, just a state of zoom which is persistent and inclusive of the view state as the user wants to see it

A nice example of it is how sketchboard does it

I tried understanding how this works from looking at renderScene.ts but this might get messier per the zoom concepts in Excalidraw

**Comment by dwelle** [comment]
Zoom-to-fit is implemented via `Shift+1`.

I don't think we should dispense with percentages, and we definitely want to keep 100% as the default reference point at which you started and to which you can go back to, irrespective of how many elements are on the scene.

Otherwise you'd lose the ability to know how big elements really are (to point out just one consideration).

Whether we have infinite canvas or not is not relevant here.
