### ISSUE TITLE
😢Save doesn't work.  The saved Json file is empty.

### ISSUE THREAD

**Issue by miguelhau** [excalidraw/excalidraw#1441]

**Comment by dwelle** [comment]
Hello. What's your OS & Browser?

**Comment by dwelle** [comment]
Ok, I can repro on Chromium 84 (Edge/Canary).

/cc @tomayac is it possibly some origin-trial error, or Native FS regression?

**Comment by tomayac** [comment]
I’ll have a look tomorrow.

**Comment by dwelle** [comment]
The prev bug was about `createWritable` while this one is about `createWriter`. I couldn't quite figure out the code path by looking at your source.

Also it only manifests in Chromium 83+ so I don't think it's cache problem.

Anyway, since it's not on stable channel, it's not a priority, so take your time!

**Comment by dwelle** [comment]
Thanks for the fix Thomas. :tada:
