### ISSUE TITLE
Feature Request: Color Picker

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [excalidraw/excalidraw#1517]
I'm wondering if it would be possible to add a color picker sort of similar to the one in Visual Studio Code:

![image](https://user-images.githubusercontent.com/19352442/80738233-ac871f80-8ae2-11ea-9071-9b573d09d36a.png)

Currently, if I want to use a color not supported out of the box, I have to leave the app to generate the color in another app and return to paste it in.

**Comment by jose-donato** [comment]
Added a quick example with [react-color](https://casesandberg.github.io/react-color/)
![colorpickerexcalidraw](https://user-images.githubusercontent.com/43375532/80748902-9054a400-8b1d-11ea-9322-11b9c0a47775.png)
Would definitely be interesting something like this. if anyone wants to provide some suggestions for the UI i can make this feature

**Comment by vjeux** [comment]
I don't think that adding such a feature would be good for the project. One of the key feature of Excalidraw is the simplicity and good defaults. If you want something else, we added the ability to enter arbitrary hex colors. Using a different program for that is, I believe, a good enough experience compared to adding complexity in the UI.

**Comment by AleksandrHovhannisyan** [comment]
Yeah, I get what you mean regarding defaults and simplicity. But I think Excalidraw's main appeal is not with its limited color palette but rather the limited shapes and styles in which they're drawn. I often find that the existing colors do not suit my needs.

In my experience, it's actually been pretty annoying to copy-paste hex codes into Google and use the color picker there :/

**Comment by j-f1** [comment]
What about allowing people to manually enter custom colors, then saving the most recent 5 (or whatever) in the color picker?

**Comment by dwelle** [comment]
Not bad. It won't complicate the base UI because it won't even show until you paste custom color.

I'd maybe tweak the idea and show X recent color that are actually on the scene (if found), before showing X recent custom-picked colors, because you may play with a color before settling on it, and it would replace all your recent colors with shades of a single one.

**Comment by borekb** [comment]
For reference, Balsamiq also don't have a color picker but I find their color palette much more suitable for my real-world needs, probably because there are several hues for each color.

<img width="185" alt="Screenshot 2020-08-05 at 09 53 48" src="https://user-images.githubusercontent.com/101152/89386802-e24f2c00-d701-11ea-9355-65f08fd7c255.png">

But people still requests custom palettes / remembering previous choices / color picker in Balsamiq products 😄.

My point of view:

- Remembering previous custom values would indeed be useful.
- Maybe full color picker could be behind something like option-click or something (agree that the simplicity of the the primary UI is important).

**Comment by benoitzohar** [comment]
A good middle ground between having an entire color picker grid and just the hex code would be to have a  "picker" that grabs any color on the page.

Like this:
<img width="285" alt="Screen Shot 2020-11-24 at 5 28 25 PM" src="https://user-images.githubusercontent.com/1698042/100158685-9116a400-2e7a-11eb-88b4-214d059a506e.png">

It would allow to easily reuse colors already on the page without having to type anything and the added UI would just be a pipette:

<img width="31" alt="Screen Shot 2020-11-24 at 5 30 05 PM" src="https://user-images.githubusercontent.com/1698042/100158770-b6a3ad80-2e7a-11eb-971e-dd317d8269e4.png">

I'm super interested in that feature so if you agree I'll happily create a PR for it 👍

**Comment by dwelle** [comment]
Not sure if a color sampler will be useful considering most diagrams use hachure/cross-hatch fills where picking the color would be really hard.

You'd either have to use solid fills, or keep extra elements with solid fills on scene to serve as a swatch palette (at which point it's better to just support user swatches).

**Comment by lipis** [comment]
As @vjeux mentioned, we'll keep it simple in Excalidraw.

**Comment by brooksvb** [comment]
I am dumbstruck that this isn't possible in Excalidraw.

Use Case: I want to make some brown boxes in my sketch. Pretty straightforward, right? Okay, there's no brown option. Okay, where's the color picker? There is none. Okay... What is the hex code for brown??? Who knows that off the top of their head, and how do you expect someone to find a color they want without opening up some kind of website or tool just to find the hexcode paste in?

Why couldn't a discreet color picker button be put somewhere on the color change popup, which opens a *slightly* more advanced color picker that everyone who has used the most basic of graphical editing software has seen 5000 times before in their life? It doesn't have to be visible by default; just add the option for people who need it. I can't understand how "not complicating the UI" is an excuse to ignore a pretty basic need and egregious pain point of UX.

**Comment by brooksvb** [comment]
> A good middle ground between having an entire color picker grid and just the hex code would be to have a "picker" that grabs any color on the page.
> 
> Like this: <img alt="Screen Shot 2020-11-24 at 5 28 25 PM" width="285" src="https://user-images.githubusercontent.com/1698042/100158685-9116a400-2e7a-11eb-88b4-214d059a506e.png">
> 
> It would allow to easily reuse colors already on the page without having to type anything and the added UI would just be a pipette:
> 
> <img alt="Screen Shot 2020-11-24 at 5 30 05 PM" width="31" src="https://user-images.githubusercontent.com/1698042/100158770-b6a3ad80-2e7a-11eb-971e-dd317d8269e4.png">
> 
> I'm super interested in that feature so if you agree I'll happily create a PR for it +1

I think a color pipette would also be another fine discreet button to add. If I am sketching ideas in Excalidraw (as one does, because it's a great program for rudimentary sketches), there might be a photo that I'm looking at that I like, and I want to grab a color out of it, or a website. I should be able to easily grab eyedrop that color so I can get it in my sketch. Otherwise I would have to open up element inspector in my browser, or if it's a local photo open up some OTHER photo editing program just to eyedrop the color, or have an eyedropper integrated into my desktop environment, which I'm pretty sure not many users do.

**Comment by grosslarnakh** [comment]
+1 for color picker (for example, palette opening thru click on color rectangle). As for me, color picker is not a feature but a necessary thing.

**Comment by alebrozzo** [comment]
With no intention to keep kicking a dead horse, but I am trying to create a yellow text over black background button and I enter the hex for yellow and it looks olive. I don't know if this is an optical illution caused by the contrast of both colours but in my actual web site it looks ok. I have randomly tried other yellow-like hexes with the same result. I don't know how to make it look as I intent and I feel a color picker that live updates the target as I hover the colurs would be ideal _in my use case_.

I understand that Excalidraw is not a design tool and you want to keep it simple, but on the other hand I certainly don't need a full blown Figma just to try out a couple look and feel tweaks or discussions.

Those are my two cents and all I can do with them is throw 'em in the wishing well while asking for a clor picker. Good night and thanks for reading.
