### ISSUE TITLE
Unhandled Rejection  - Cannot read property 'generateKey' 

### ISSUE THREAD

**Issue by JeromeD84** [excalidraw/excalidraw#1563]
Hi,

When i start a live collaboration i receive the Error web page : 
Can you help me and explain me how i can generate the key on my server ?

Regards,

>  Unhandled Rejection (TypeError): Cannot read property 'generateKey' of undefined
> 
> generateEncryptionKey
> src/excalidraw/src/data/index.ts:86
>   83 | }
>   84 | 
>   85 | async function generateEncryptionKey() {
> > 86 |   const key = await window.crypto.subtle.generateKey(
>   87 |     {
>   88 |       name: "AES-GCM",
>   89 |       length: 128,
> View compiled
> 
> generateCollaborationLink
> src/excalidraw/src/data/index.ts:112
>   109 | 
>   110 | export async function generateCollaborationLink() {
>   111 |   const id = await generateRandomID();
> > 112 |   const key = await generateEncryptionKey();
>   113 |   return `${window.location.origin}${window.location.pathname}#room=${id},${key}`;
>   114 | }
>   115 | 
> View compiled
> async App.openPortal
> src/excalidraw/src/components/App.tsx:759
>   756 | };
>   757 | 
>   758 | openPortal = async () => {
> > 759 |   window.history.pushState(
>       | ^  760 |     {},
>   761 |     "Excalidraw",
>   762 |     await generateCollaborationLink(),
> View compiled
> This screen is visible only in development. It will not appear if the app crashes in production.

**Comment by dwelle** [comment]
Hello. I can't find this error on our bug tracker. What browser & browser version are you using?

> Can you help me and explain me how i can generate the key on my server ?

Unclear what you mean by your server.

**Comment by JeromeD84** [comment]
Hello,

Some informations :
- My Chrome PC Version 81.0.4044.138 doesn't work.
- My Chrome Android Phone Version 80.0.3987.162 doesn't work
- My Safari Ipad IOS works. Yes i can start a live session

I said : "Can you help me and explain me how i can generate the key on my server ?"
It means that i install NodeJS on my private server afetr git clone ... npm install ... npm start. I wanted to said : I can't start a live collaboration when i use excalidraw on my private server.

When i start a live session with my Ipad, when my PC or Phone try to join, then they receive the error :

> Unhandled Rejection (TypeError): Cannot read property 'importKey' of undefined
> getImportedKey
> src/excalidraw/src/data/index.ts:117
>   114 | }
>   115 | 
>   116 | function getImportedKey(key: string, usage: string) {
> > 117 |   return window.crypto.subtle.importKey(
>   118 |     "jwk",
>   119 |     {
>   120 |       alg: "A128GCM",
> View compiled
> .........




Regards,

**Comment by dwelle** [comment]
Okay. If you're not running your server on localhost, and the domain isn't secure (HTTPS), then the [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) API won't be available.

Does this describe your problem?

**Comment by MartinP7r** [comment]
I'm getting this error when I try to share the workspace on a self-hosted instance. Since you state in your README.md that collaborative features are not supported for self-hosted, yet, I think that's the issue for @JeromeD84   

May I ask btw, if this can be implemented soon?  
Or what would be necessary to implemented it myself?  

Best regards,
Martin

**Comment by dwelle** [comment]
As I understand it, this consists of two parts: 1) dockerizing the backend servers 2) supporting encryption on non-secure, non-localhost servers.

You don't have to wait for (1) as you can run the servers yourself, and change the ENV variables so they point to your server instead of ours.

As for (2), that will not work unless we drop the encryption part for self-hosted instances, which I don't see happening.

Since you mentioned you're getting the OP's error, it's likely connected to (2), though :frowning_face:.

**Comment by MartinP7r** [comment]
Thanks for your reply @dwelle,  

I have an https enabled local server. In that case I would just have to run the servers myself like you said and change the endpoints in `.env` file in the root of this project?  
I take it, this is the socket server? : https://github.com/excalidraw/excalidraw-room  
I can't quite figure out where the backend server for `https://json.excalidraw.com/api/v1/` etc. is located, though.

**Comment by dwelle** [comment]
@MartinP7r sorry, I must have missed your reply.

Yes, you should update your `.env` or wherever you supply ENV variables.

The JSON server repo is here: https://github.com/excalidraw/excalidraw-json

Also note that we'll be soon releasing a new npm package under `@excalidraw/excalidraw` where it'll be easy to implement your own backend(s). We should eventually get around to writing up how to do that, but before then you can to read the source of code of this repo since we've already factored out the backend logic from the core, and are using the same API to implement the backends for excalidraw.com

Cheers.

**Comment by MartinP7r** [comment]
@dwelle thanks a lot for letting me know!
