### ISSUE TITLE
Horizontal arrows are cropped when zoomed in

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1572]
The canvas intermediate bounding box must not correctly take into account the arrow edges.

200%

![image](https://user-images.githubusercontent.com/197597/81523520-e20de300-9302-11ea-8bdd-5348d3c3b1f3.png)

100%

![image](https://user-images.githubusercontent.com/197597/81523528-e89c5a80-9302-11ea-83a8-de800dddc73d.png)

**Comment by dai-shi** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/490574/81523890-3b6d2500-938a-11ea-8972-cf8545ca66cf.png">

Any arrows seem to have this issue...

**Comment by luc4leone** [comment]
Would it be a good first issue? In case it's not, any suggestion for a good first issue? Thanks :)

**Comment by steveruizok** [comment]
Would love to know more about this one as we work more on arrow decorators. https://github.com/excalidraw/excalidraw/pull/2452

**Comment by lipis** [comment]
@steveruizok  Is that still an issue?

**Comment by lipis** [comment]
That's still an issue..

**Comment by dwelle** [comment]
Yea, the problem probably lies somewhere in `renderElemene.ts` where we create element-specific canvas elements (`generateElementCanvas()`). As vjeux said, we must be making a mistake during the calculation when taking zoom into account.

**Comment by steveruizok** [comment]
I don't think it's the zoom, actually. When we create the canvas for linear elements, we're only looking at the line itself—not its arrowheads. It just happens that on normal zoom levels, the arrow heads fit into the 20px of canvas padding around the shape. When we zoom in, those arrowheads are drawn larger and are drawn off of the element's canvas.

![Kapture 2020-12-12 at 13 47 54](https://user-images.githubusercontent.com/23072548/101985560-afeda680-3c80-11eb-9c03-a3fd84259047.gif)

In this GIF, I'm painting the canvas padding area in red. Notice that the inner (white) box is sized to the arrow's line. The arrowheads aren't included.

One solution could be to apply the zoom against the padding, too, so that the paddings are larger when zoomed in. But that doesn't actually solve the problem, which is that we're not computing the canvas size based on the shapes that are actually there.

**Comment by dwelle** [comment]
> One solution could be to apply the zoom against the padding, too, so that the paddings are larger when zoomed in. But that doesn't actually solve the problem, which is that we're not computing the canvas size based on the shapes that are actually there.

Yep, this is the way to go. The padding was always meant to be a hack, but unless we wanna solve it for every shape, let's just apply the zoom to the padding as well so it's consistent.

**Comment by dwelle** [comment]
@luc4leone since you have dibs on this (I missed your comment earlier), lemme know if you wanna work on this :).

**Comment by steveruizok** [comment]
PR here: https://github.com/excalidraw/excalidraw/pull/2515

The padding adjustment was pretty straightforward. We're still not looking at the arrowheads though.

**Comment by luc4leone** [comment]
>@luc4leone since you have dibs on this (I missed your comment earlier), lemme know if you wanna work on this :).

thanks @dwelle. I was curious about this bug because it's related to the part of the program that I am interested in: the frontend interaction part. If there some other issues you would suggest for me to attack I'll be glad to try ☺️

**Comment by dwelle** [comment]
@luc4leone not sure right now. Try to look at our latest issues, see if anything catches your eye and we can discuss it :).

**Comment by luc4leone** [comment]
thanks @dwelle, I will!
