### ISSUE TITLE
The left and top menu region blinks on cursor movement

### ISSUE THREAD

**Issue by tusharf5** [excalidraw/excalidraw#1582]
First of all thank you for this amazing tool ❤️. I've been looking for something like this for months now and I saw a link to this on a newsletter. I got so excited after using it that I ordered a drawing tablet only to find out later that it doesn't support free hand drawing but I see it's a work in progress feature.

Now the issue. Take a look at the video which shows it.

The menu on the left and top sometimes blink (a lot) on different cursor movements. There are no errors in the console.

https://www.loom.com/share/136ab7183db64593ae172c3c17767400

**Comment by dwelle** [comment]
Hello. Thanks for your kind words.

What browser & version are you using? I have no clue what that could be, except something GPU-related. Chrome used to have similar issues on certain GPUs, but they fixed it.

**Comment by tusharf5** [comment]
This is my system config 

16 GB 2133 MHz LPDDR3
2.5 GHz Dual-Core Intel Core i7
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

It doesn't happen on Firefox but happens consistently on Chrome (latest version).

**Comment by dwelle** [comment]
Hmm, the fact it only happens on Chrome suggests it might be related to that GPU bug. Checking google, its GPU (Intel Iris Plus Graphics 640) doesn't ring any bell, but that means absolutely nothing because I wasn't really involved in that previous GPU issue  (apart from being affected by it).

That said, I don't want us to stop considering any other possibilities --- except I have nothing else to contribute :(. It really looks like a GPU bug since parts of the UI disappears, not whole elements.

One thing you can try. Go to `chrome://flags` and if you have `GPU rasterization` enabled, try to disable it (or other way around). If that fixes the issue then it's pretty much settled, and you should open an issue on www.crbug.com

![image](https://user-images.githubusercontent.com/5153846/81598893-49419b00-93c8-11ea-8cd4-d6b4463e2384.png)

**Comment by tusharf5** [comment]
Disabled it but it still blinks as shown in the video :( Let me know if you need any help debugging it. I wonder if it happens to everyone with the same config or is it just my machine.

**Comment by dwelle** [comment]
I'm on the same Chrome as you (81.0.4044.138). We haven't had any such reports, but if it's your GPU I'd be a bit surprised if no one experienced it (MacBook pro 2017 isn't that uncommon).

Either way, I'm out of ideas. If anyone else has any, let's chime in.

**Comment by tusharf5** [comment]
Just installed Canary, the issue doesn't seem to happen there. I guess I'll wait for the next Chrome release and let you know if the issue still persists after that.

**Comment by dwelle** [comment]
Sweet, good to know. In my experience, it's usually the other way around (Canary breaking something from stable) :smile:.

**Comment by tusharf5** [comment]
or it fixes something broken in stable 😇(my glass is just half full 😀)

**Comment by tusharf5** [comment]
This was happening because of a hardware issue on my macbook pro's display. Once I got it replaced it stopped.

**Comment by dwelle** [comment]
Good it was resolved!
