### ISSUE TITLE
version each release

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1665]
An autoincrementing id (or something) accessible from global object, so we can more easily debug problems. Also should be made to be reported to sentry..

Not sure how to automate it so it's persisted to release commit, preferably without us having to do anything (or commit anything). Is it doable?

**Comment by ad1992** [comment]
Are you looking for something like https://docs.sentry.io/workflow/releases/?platform=browser#create-release?
Also can't we use the last commit hash as the build version as that will always be unique?

**Comment by dwelle** [comment]
Thanks for the link. I meant something exposed from our app itself so that you can check the version even if nothing was thrown and logged to sentry, but we can start with that, for sure.

**Comment by petehunt** [comment]
+1 on using the latest commit hash

**Comment by kbariotis** [comment]
@dwelle @petehunt  Sentry is already reporting the SHA where the issue was first introduced. :)

![image](https://user-images.githubusercontent.com/605742/85016151-0d38ed00-b161-11ea-9cf4-faafbe64643b.png)

**Comment by kjellkvinge** [comment]
Is the result from `git describe --tags --always` sufficient?

* Without tags it will be the start of the SHA, i.e `0ed6a96`
* after a version is tagged, we will see this version, i.e `v0.1.1`
* commits after this will be in the following format `v0.1.1-3-g0ed6a96` - so you have `tag`-`commits since tag`g`SHA`

I am not familiar with the stack on this project, but playing around i see that the following in package.json

```patch
diff --git a/package.json b/package.json
index ebf6352..3a4ea3c 100644
--- a/package.json
+++ b/package.json
@@ -74,7 +74,7 @@
   "scripts": {
     "build": "npm run build:app && npm run build:zip",
     "build-node": "node ./scripts/build-node.js",
-    "build:app": "REACT_APP_GIT_SHA=$NOW_GITHUB_COMMIT_SHA react-scripts build",
+    "build:app": "REACT_APP_GIT_SHA=$NOW_GITHUB_COMMIT_SHA REACT_APP_VERSION=$(git describe --tags --always) react-scripts build",
     "build:zip": "node ./scripts/build-version.js",
     "eject": "react-scripts eject",
     "fix": "npm run fix:other && npm run fix:code",
```
Will let this version string be accessible in the project (as `process.env.REACT_APP_VERSION`), so one could expose it wherever it is needed. For instance:

```patch
diff --git a/src/components/LayerUI.tsx b/src/components/LayerUI.tsx
index 75d8304..b254991 100644
--- a/src/components/LayerUI.tsx
+++ b/src/components/LayerUI.tsx
@@ -219,6 +219,7 @@ const LayerUI = ({
                   />
                 </Island>
                 {renderEncryptedIcon()}
+                <div id="version">v:<span>{process.env.REACT_APP_VERSION}</span></div>
               </Section>
             </Stack.Col>
           </div>
```

![version](https://user-images.githubusercontent.com/3092520/85212004-c27cc800-b34e-11ea-9858-d60b2aecc81d.png)

This might solve #1751 

regards - and thank you for the work that is put into this project :love_you_gesture:

**Comment by kbariotis** [comment]
@dwelle is it fair to close this since Sentry includes the commit hash?

**Comment by dwelle** [comment]
We still need to expose it on `window` so that we have some way of debugging spicier issues.

**Comment by kbariotis** [comment]
Alright that should be a small addition.

**Comment by dwelle** [comment]
If we want to use a commit hash, I can't think of anything other than what you're doing with the i18n percentages post-push action.

**Comment by kbariotis** [comment]
Hmm sorry I lost you. The commit hash is already there as a variable. All we need is to expose it to the global window object.
