### ISSUE TITLE
copy element style shortcut conflicts with DevTools element inspector

### ISSUE THREAD

**Issue by matt-l-w** [excalidraw/excalidraw#1688]
**Environment Info**
Firefox version: 76.0.1 (64-bit)
OS: Ubuntu 18.0.4

**Reproduction Steps**
1. Create a new document (or open an old one)
1. Select a node
1. Press `CTRL`+`SHIFT` + `C` to copy the styles of the selected node

**Expected**
Styles to be copied and paste-able.

**Actual**
Opens the "Element selector" in firefox dev tools.

**Notes**
See the [MDN page about firefox keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts). It's one of the ones defined there.

There might be other shortcuts that override the excalidraw ones for which that might prove a useful resource. I've not done a proper cross-comparison.

**Comment by dwelle** [comment]
I think it was me recently who made this regression because I didn't realize we have `Cmd/Ctrl + Shift + C` mapped to copy-styles action.

Not sure we want to override browser behavior here. Should we find a new shortcut for this or override? I realize this is a developer shortcut so it's not high-profile, but still (it's also useful in excal development itself).

/cc @lipis

**Comment by lipis** [comment]
I'm not very happy overriding something that is doing completely different thing. Overriding Cmd+C for example is fine as we want to be more specific on what's going there, etc.. So for this case maybe we should find a new shortcut for styles.. It's also I believe not something that used so frequently anyways!

**Comment by hartmut-co-uk** [comment]
same for chrome, shortcut not usable.

> **Environment Info**
> Version 83.0.4103.116 (Official Build) (64-bit)
> macOS Catalina 10.15.5

**Comment by dwelle** [comment]
Anyone feel free to toss ideas for a substitute shortcut.

**Comment by matt-l-w** [comment]
Cmd+Shift+Opt+C doesn't seem to do anything on Firefox or Chrome. Not tried out a Windows machine yet.

A bit clunky but, as someone mentioned before, it's not that frequently used so I'd be happy with an slightly awkward shortcut over no shortcut!

**Comment by hartmut-co-uk** [comment]
`Cmd+Ctrl+C` (mac) is not an option is it? (for windows `Cmd == Ctrl`, right?)

**Comment by matt-l-w** [comment]
Sorry, I meant "alt" not Opt. I'll edit the original comment.

**Comment by matt-l-w** [comment]
But yes, Cmd is roughly equivalent to Ctrl

**Comment by dwelle** [comment]
> `Cmd+Ctrl+C` (mac) is not an option is it? (for windows `Cmd == Ctrl`, right?)

Yea.

Figma actually uses `Cmd + Opt + C`. This is [supposedly taken](https://github.com/excalidraw/excalidraw/pull/941#issuecomment-599105000) by Mac's Chrome to inspect element, but IMO `Cmd + Shift + C` should be enough (that shortcut is cross-platform), plus since Figma already does that, I'd go with that one.

**Comment by matt-l-w** [comment]
There is still a Ctrl key on Mac but it has a slightly different purpose.

**Comment by dwelle** [comment]
I've opened a PR. I don't have Mac so please check if it works https://github.com/excalidraw/excalidraw/pull/1881 - if not I'll need to switch to different workflow.

**Comment by matt-l-w** [comment]
Thanks @dwelle!
Looks good to me.

**Comment by Nilegfx** [comment]
CMD+Option+c doesn't work for me on mac. am I missing something here?

**Comment by dwelle** [comment]
@Nilegfx what's your keyboard layout (US/FR...)?
