### ISSUE TITLE
Can’t undo when duplicate editing line

### ISSUE THREAD

**Issue by lusingander** [excalidraw/excalidraw#1742]
When I duplicate the editing line, I could not be able to undo it.

![200609](https://user-images.githubusercontent.com/31386431/84140636-e3ab0200-aa8c-11ea-89a4-bc79e233de41.gif)

If I try to undo, it seems to blink for a second.

**Comment by sparkingdark** [comment]
Can i work on it? @dwelle

**Comment by dwelle** [comment]
I actually looked at it the day this issue was filed but I've hit some react state problems, apart from the fact that our history workflow doesn't account for for cases like this.

Don't have time to explain, but will write up notes tomorrow.

**Comment by sparkingdark** [comment]
Ok

**Comment by dwelle** [comment]
Sorry for not-tomorrow-reply.

First, to describe the problem at hand. When you duplicate while editing a line, it does:

1. call `duplicateSelection` action. This duplicates the element, selects it, and creates a new history entry (let's call it `N+1`) which still tracks previous element as being edited.
2. In the ensuing `componentDidUpdate` it checks whether the currently-editing-line (`state.editingLinearElement`) is still referencing currently selected element:

https://github.com/excalidraw/excalidraw/blob/f0463fadc34df747c3119a05ad7fb498e96f3d7c/src/components/App.tsx#L505-L513

3. At which point it realizes it doesn't (the newly duplicate element is selected instead), and calls `finalize` action to exit the line editing. This creates a new history entry (`N+2`) with setting `state.editingLinearElement` to `null`. 
4. If you then undo the last history `N+2`, it falls backs `N+1` which still tracks `editingLinearElement` set to the 1st element. It again falls to step (2), calling the `finalize` action and so on.

Ideally, we could batch `duplicateSelection` and `finalize` actions together but it has several problems right now:

- We'd still need to manually call `finalize` action when calling `duplicateSelection` (or along the the pipeline, e.g. in `syncActionResult` handler).
- Most notably, doing the above, I hit a roadblock I couldn't debug & didn't have time to debug further: the react schedule (or the way we make updates) ended up not setting the state correctly (some race condition going on). Will investigate further when I have time and describe the exact issue I was having.
- race conditions [described in here](https://github.com/excalidraw/excalidraw/issues/1773) --- technically not a problem for this specific issue as both actions would end up committing to history (for now).

A quick hack to get around this is instead of calling `finalize` action, inline the contents of `finalize` action into `syncActionResult` (i.e. avoid dual `setState`). I didn't want to do this because that sounds like a very bad idea and won't solve similar problems down the line.

**Comment by sparkingdark** [comment]
Is it possible to split the actions in functions and call them when required ?
As you said it done the work in n+2 after finishing goes to n+1.

**Comment by dwelle** [comment]
> Is it possible to split the actions in functions and call them when required?

Everything can be hacked in one way or another. Whether it's a good idea to add that complexity is another matter. Would rather do some more thinking and try to fix in a different way.

We also need to handle the related history issues I mentioned in the linked issue.
