### ISSUE TITLE
Great Work! Starting Canvas?

### ISSUE THREAD

**Issue by MGHonor** [excalidraw/excalidraw#1746]
Hello,

first i appreciate the work and adore using it. Thanks for that!
I would like to know, if there is a possibility to set up some kind of starting canvas. 
Like some example texts and shapes which appear with the scene.  

Thanks

**Comment by MGHonor** [comment]
> 
> 
> @MGHonor when you load excalidraw.com we want you to be able to draw right away. If we had an example scene, you'd always need to clear it first.
> 
> If you want to ease the introduction at you company you could maybe create an example scene yourself, share it as a link, and use that link when you send excalidraw to your colleagues.
> 
> @kjellkvinge there's also #1091 in the works

Great Idea!
I launched Excalidraw in my Cloud but there the shareable link wouldnt work (firefox and chrome). Would you have a solution for that?

**Comment by dwelle** [comment]
You mean you've self-hosted Excalidraw, which means the sharelink doesn't work because the domain isn't whitelisted?

Mhm, then you're right that #1090 is the only option at this point (loading the example scene from a JSON file isn't really an option I'd say). Unless you want to roll out your own backend for link sharing (which you'll need to do eventually if you want that functionality on self-hosted instances).

**Comment by MGHonor** [comment]
Exactly.
To be honest i dont have much experience related to programming and everything.. but the white list could be the problem. At the moment everything seems working, even the collaboration link which will be generated correctly.

**Comment by dwelle** [comment]
On our backend server, we're only whitelisting our own domains + localhosts, so sharelink (and collaboration AFAIK) won't work on self-hosted instances.
