### ISSUE TITLE
Can someone explain why this tool is so popular?

### ISSUE THREAD

**Issue by himat** [excalidraw/excalidraw#1876]
I don't do much design myself, so maybe that's why I don't understand.
But does someone understand why excalidraw is so popular when there are things like Figma and many other design/whiteboard tools out there?

I do think it's a great tool, so just curious what other people think.

Thanks!

**Comment by kbariotis** [comment]
@himat I'm not sure what answer exactly you are looking for and I certainly can't speak on behalf of the many users out there that use Excalidraw. What I can do is give you my perspective on how Excalidraw differs from some of the alternatives:

_Below is my own opinion and it's not by any means an official response._

**Excalidraw promoted the hand-drawn like diagrams**

At first, Excalidraw promoted the creation of hand-drawn like diagrams. So unlike draw.io for example, diagrams made with Excalidraw felt like they were drawn on hand. That was something that made many blog authors use Excalidraw diagrams on their posts and contributed to its promotion.

**Excalidraw is easy**

At its core, Excalidraw is easy to use. No registration steps, no pop-ups, no nothing. Just open and draw. The team is working hard to maintain the same spirit while adding more and more features to it.

**Excalidraw is open-source**

Excalidraw is open-source and also its JS codebase makes it very easy for contributors around the world to leave their mark. There are over 100 contributors so far with a lot of them being really active, doing commits almost every day. It only started this January.

**Excalidraw is not just user interfaces, it's any diagram**

Since you mentioned Figma, I will give you an example from my environment and the company I work at. Figma is being used primarily by designers to share and collaborate on user interfaces. Excalidraw is being used primarily by engineers to enhance their design documents with diagrams and communicate their ideas. But we have seen lots of examples where people are using it for early UX prototypes and mock-ups.
