### ISSUE TITLE
Zoom of no return

### ISSUE THREAD

**Issue by AaronRobinson** [excalidraw/excalidraw#1938]
Using Brave on Macbook. I was zooming in and out and got to a state in the attached image. 
<img width="1792" alt="Screenshot 2020-07-19 at 00 06 06" src="https://user-images.githubusercontent.com/1792811/87863535-c1da5000-c953-11ea-856f-73326b02e583.png">

I can't find a way out of it. Going into dev mode and switch to ipad persepctive looks fine...

<img width="383" alt="Screenshot 2020-07-19 at 00 12 29" src="https://user-images.githubusercontent.com/1792811/87863613-a3288900-c954-11ea-8a45-e2187b38c529.png">

...but switching back to full screen returns to the zoom of no return. I can't see anything that's cached or in local storage etc to clear out. No error in the console.

Closing down the Excalidraw tab, starting a new one just shows the same screen.

window.__EXCALIDRAW_SHA__ gives ac6707120c9aff3868ddd3c9911b1910075f4645

I'm working on Chrome now and will leave Brave as it is just in case it helps to investigate.

**Comment by dwelle** [comment]
Ok, my reaction to your tweet missed the point because I read it as "zen mode", not "zoom mode" --- probably because we don't have zoom mode, only zen mode :).

(Also, the `EXCALIDRAW_SHA` was needed more for your second issue about saving empty excalidraw files.)

---

As far as this issue is concerned, do I understand it correctly that you zoomed into a state where it zoomed into a mobile view, and you can't get out of it?

What I believe happened is you managed to zoom the actual browser window instead of the canvas (app). Generally, we disabled browser zooming, but there's a bug where if you zoom while editing text, it zooms the browser (at least when you do that via mouse wheel). Maybe there are other cases. I'll think about what to do about it.

As for how to get out of it (provided my assumption is correct) --- check if there's a "reset zoom" button in your browser's url bar.

**Comment by AaronRobinson** [comment]
That solved it. The browser zoom was set at 300% and zooming out using cmd+- didn't change the browser zoom. Presumably I must have been editing a text field at the time I zoomed as you suggest.

Thanks

**Comment by lipis** [comment]
I guess we can close this one!

**Comment by vjeux** [comment]
Is it possible to detect browser zoom somehow and put a warning or something?

**Comment by dwelle** [comment]
From what I've seen it's pretty hard. I think the best bet is to try to prevent it in all situations, but that could turn hard as well.
