### ISSUE TITLE
Shortcut conflict on Google Chrome

### ISSUE THREAD

**Issue by rfoel** [excalidraw/excalidraw#1974]
How does one use the action group and ungroup on Google Chrome?

![image](https://user-images.githubusercontent.com/19496473/88607467-b07cfc00-d055-11ea-897f-2bae6b470617.png)

**Comment by dwelle** [comment]
Hello. So on your Mac pressing `Cmd+G` does a browser search instead of grouping? What keyboard layout do you have (meaning, is it a localized layout with different positions for keys than the default English layout)? Does `Cmd+G` for grouping work for you on Figma.com?

**Comment by rfoel** [comment]
@dwelle I cloned the project and tried it locally on Chrome and it worked without a problem. Then I tried again on excalidraw.com and it worked too. I don't know if something changed in the last 12 hours but it just works now. 

Thanks anyway, closing the issue.

**Comment by lobre** [comment]
Hi, I know this is an old issue, but I am encountering this same problem.

@dwelle, you mention that a localized layout could be the "problem", which is my case, as I am using a bépo french layout.

Can you please elaborate a little on why this is a pb? I tested the grouping with `Ctrl+g` in Figma and I don't have the issue there. In Excalidraw, this triggers a browser search instead of grouping.

Thanks
