### ISSUE TITLE
Share scene via URL

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#203]
It can be really simple way to share scenes

**Comment by dwelle** [comment]
Depending on the scene complexity, serializing it into base64 might prove too large for URLs (even if it works now for average scene sizes, it may break at any moment in the future when we introduce more state).

First, we'd need to investigate URL length limits for various browsers so that we get an idea where we stand.

**Comment by paulomenezes** [comment]
Can you thought about have a server with database to store this? And share only the ID? I don't know if it's the idea of this project.

**Comment by jaredpalmer** [comment]
We could serialize state to a query string and then we just need a url shortener and we’re done

**Comment by dwelle** [comment]
@jaredpalmer I'm not sure how that would help:

1. url-shortener services must impose length limits, too
2. but even if they didn't, the url still gets expanded upon redirection, and if it extends beyond browser url limit, then that redirect won't work.

Or am I misunderstanding?

**Comment by jaredpalmer** [comment]
Yeah, I guess you’re correct. How does storybook do it? Or does it not actually serialize state?

**Comment by nanot1m** [comment]
Maybe we can start with storing state in url hash? Like in [typescript playground](http://www.typescriptlang.org/play/index.html#code/MYewdgziA2CmB00QHMAUByAMiEBrAhAAQCSALgDroSECuEAlmMoUsAIan3iEAWbEPQqRCEIwgE6xRpDrHQBKIA). Someone told to me, that buggy feature is better then unshipped feature))

**Comment by dwelle** [comment]
@nanot1m that was the whole idea (it's not really important whether we put it in `hash` or `query`, although `hash` is preferable). But having the url be cut-off (dunno what's the default browser behavior) due to exceeding length would possibly result in silent errors such as some elements being lost etc.

> Someone told to me, that buggy feature is better then unshipped feature))

I'm just voicing concerns and pointing out possible problems. I'll recuse myself from making a judgement on this issue, and leave that for others :)
