### ISSUE TITLE
Please get us an Eraser 

### ISSUE THREAD

**Issue by gagan1510** [excalidraw/excalidraw#2052]
An eraser for anything on that layer will be beautiful.

**Comment by dwelle** [comment]
Excalidraw doesn't work like that. Every element is its own layer. The best I can imagine is an eraser for free-draw shapes where it would delete points.

**Comment by lipis** [comment]
Not very clear on what exactly he means by eraser.. 😕

**Comment by dwelle** [comment]
While I can see a limited use case (e.g. you have lots of tiny elements or lines/free-draws that you want to remove in a manner different to box-selecting), I don't think it's worth adding to Excalidraw at this point.

**Comment by mahrud** [comment]
I'd like to re-request this, and make it more specific: I'd like a special pen that, within a radius, deletes points on any layer, and any line segment connected to that point. This would be useful for editing an existing layer without deleting it and starting over.

**Comment by dwelle** [comment]
It'd be hard to do in terms of how our shapes work. If you deleted a point in a middle of a line with the intent to split it into two lines, we'd have to delete the shape and create two shapes in its stead. Doable, but not simple. It'd also regenerate the shape slightly, etc.

We also want to keep the UI simple and not introduce new tools unnecessarily.

> This would be useful for editing an existing layer without deleting it and starting over.

You can double-click (or press <kbd>enter</kbd>) to edit a line and delete points selectively.

**Comment by mahrud** [comment]
> We also want to keep the UI simple and not introduce new tools unnecessarily.

I think an eraser is going to be the second thing that most people will look for, after a pen. It's ultimately up to you, and your intended audience, but an eraser is more necessary than drawing circles, diamonds, squares, arrows, etc. (which are useful in a library of shapes, but not in the UI) for my collaborators and I.

> If you deleted a point in a middle of a line with the intent to split it into two lines, we'd have to delete the shape and create two shapes in its stead. Doable, but not simple.

Okay, then just delete the point if it's at one of the two endpoints, and otherwise delete the point without splitting the layer into two. This still allows me to eventually erase the whole layer. Even erasing the whole layer at once is more convenient than repeatedly selecting a layer and pressing delete.

> You can double-click (or press enter) to edit a line and delete points selectively.

Say I draw a curve by hand and it's accidentally too long. Is your suggest to start from one end point and manually delete points until it is the desired length?

**Comment by dwelle** [comment]
> Say I draw a curve by hand and it's accidentally too long. Is your suggest to start from one end point and manually delete points until it is the desired length?

Just select the last point and hold <kbd>Delete</kbd>. It's quite fast :).

> Okay, then just delete the point if it's at one of the two endpoints, and otherwise delete the point without splitting the layer into two. This still allows me to eventually erase the whole layer. Even erasing the whole layer at once is more convenient than repeatedly selecting a layer and pressing delete.

That would be pretty weird behavior.

Also, even if we implement it "correctly", it will only work with lines, not circles/rectangles/2-point-arrows etc.

**Comment by Coda-Coda** [comment]
Can I suggest simply adding `#ffffff` as one of the pen colour options? This would make an 'eraser' fairly easily accessible.

A couple of brief thoughts on my suggestion:
------
Pros:
 - Simple to implement
 - Works for the most common use case (a white background) (could be improved to add whatever the current background colour is as a pen colour option) (could even add it as one of the main tools).

Cons:
 - Would not work well if the background colour was changed partway through (unless it was extended so that the 'erasor' lines where special and always were updated to match the background colour)
 - Gives people the impression the drawing has been erased when it really _hasn't_ been. This might be bad if sensitive data has been 'erased' but then someone the drawing was shared with deletes the white portion and reveals the sensitive data.

-------

> I think an eraser is going to be the second thing that most people will look for, after a pen. 

^ this was true for me 🙂

------
By the way, Excalidraw is really cool - thanks for developing it!

**Comment by Coda-Coda** [comment]
On second thoughts, I'm starting to get used to the way it currently works. Deleting lines is not as discoverable as you'd expect erasor functionality to be, but it's usable.

**Comment by mahrud** [comment]
> Just select the last point and hold Delete. It's quite fast :).

You're assuming that every user has easy access to a delete button, which is not the case for me.

> By the way, Excalidraw is really cool - thanks for developing it!

I agree, even though we ended up not using it after it became clear that having to select and press delete is too cumbersome.

**Comment by 3nzoFerrari** [comment]
I'd prefer an eraser which deletes single drawn lines, like a pencil which deletes the entire line when I drag over it. Similar to the *stroke eraser* in OneNote or Notability or any other program.

**Comment by dwelle** [comment]
@3nzoFerrari if you're talking about an erasing the free draw tool, then I've created a special issue for it here: https://github.com/excalidraw/excalidraw/issues/3682

**Comment by gshiva** [comment]
_So_ this is what I had to do to get the same effect. Painful but works. Use the "Draw" tool for the same effect. Just make the line color same as the background color. "All" the Excalidraw team has to do is to add this with the ability to increase the radius (instead of the current stroke width).

![image](https://user-images.githubusercontent.com/2817954/127361258-4f06f1f4-7bc3-4328-ba9f-02598bddf59d.png)

**Comment by dwelle** [comment]
@gshiva that wouldn't work in too many cases. We'll need to implement a proper eraser.

@steveruizok should that be implement as part of https://github.com/steveruizok/perfect-freehand or in host apps? If in the library itself, are you open to PRs?

**Comment by zachdaniel** [comment]
Agreed, its kind of a pain. With that said, in case anyone else here sees this, you can also drag to select a region and delete everything you've selected. So that can ease the burden if you're like me and doing handwriting on an ipad in some cases, where clicking each little stroke and removing is 100% not an option. I agree w/ the sentiment that a tool that deletes any lines it comes into contact with would be extremely useful, and I think makes perfect sense in the context (especially on ipad where you can't "hold delete").

**Comment by steveruizok** [comment]
Erasing is really tricky in apps like Excalidraw. The simple solution would be to create a tool that, as you drag, would delete any shape that it collides with. Here it is working in [Clover](https://cloverapp.com). 

![Kapture 2021-11-10 at 11 43 43](https://user-images.githubusercontent.com/23072548/141107275-695217ab-de85-4954-8d86-3b59ed0da45f.gif)

This could be implemented quite easily in Excalidraw; however it's probably not what anyone actually wants. Rather than deleting the entire shape, we'd probably expect something that deletes only the _part of the shape_ that collides with the eraser. But this is _super_tricky. 

First, should an eraser produce its own elements? In that case, a shape could be moved from being its eraser element, or that eraser element could be deleted. This is how it works in [Limnu](https://limnu.com/) and it doesn't seem very good.

![Kapture 2021-11-10 at 11 30 45](https://user-images.githubusercontent.com/23072548/141106055-f2b3e130-e120-4e11-b6f0-10dbfce154f6.gif)

Or maybe the eraser should be made part of the shape itself? This is how it works in [browserboard](https://browserboard.com/), but this also feels strange.

![Kapture 2021-11-10 at 11 38 28](https://user-images.githubusercontent.com/23072548/141106948-aba7b3bb-27f6-43fc-997c-82f97c3a57f8.gif)

> Sidenote: this approach is especially tricky for Excalidraw because it relies on [`source-out` composition](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation), which both preserves the underlying shapes (problematic for security) and would be poorly supported in SVG exports.

And anyway—shouldn't erasing the middle of a shape actually produce two new shapes? This seems most correct, but given the way that shapes are made in Excalidraw (and in perfect-freehand), it would be difficult to preserve the appearance of the two new shapes without rasterising them. However, this approach creates its own host of problems for text, bound arrows, arrowheads, etc.

**Comment by zachdaniel** [comment]
Honestly, I don't mind at all if the eraser just deletes the whole shape. Make it a "trash can" or a "cancel" icon if the messaging seems too confusing having it be an eraser. Other apps I use have an eraser that deletes the whole shape. The point is that there is no good, non workflow breaking way, to bulk remove shapes. Having to drag a box to select works if there aren't other shapes interleaved with the shapes you want to remove, but it's not very intuitive IMO.

**Comment by zachdaniel** [comment]
But most importantly, thanks for all the hard work! I probably
Sounded pretty demanding in my last message, just bad wording sorry 😀 . If an eraser is on the table, I think it's an okay compromise to delete entire shapes. In fact, it almost seems like in a perfect world you'd want *both* sometimes.

**Comment by shaunsauve** [comment]
When I'm using a board to brainstorm or explain ideas (as opposed to
pre-made presentation material), I rarely interact with shapes and instead
scribble, draw and erase just as I would on a real whiteboard. An eraser
tool that destroyed everything it touched would probably interfere with
that workflow.

On the other hand, when I am arranging shapes, drag-selecting an area and
clearing by pressing delete already seems sufficient.

**Comment by zachdaniel** [comment]
Well, even though you wouldn't personally use it doesn't necessarily mean it shouldn't exist, right?

**Comment by IsmaelAlvarez** [comment]
> Erasing is really tricky in apps like Excalidraw. The simple solution would be to create a tool that, as you drag, would delete any shape that it collides with. Here it is working in [Clover](https://cloverapp.com).

the clover erasing tool would be so usefull for people like me using pen display tools, also the ability to change the hotkeys for the tools, E has always been the erasing tool, B brush and P pen

**Comment by hawk78** [comment]
When using a big screen with colleagues you can't easily reach the cancel/delete button on the keyboard. Sometimes the laptop is just some meters away. A possible easy solution would be to make the delete button toggable... when the button is toggled selections are immediately deleted. I would then add an undo/redo button next to it. just my 0.2 cents

**Comment by dwelle** [comment]
We will be adding Eraser soon. Due to how Excalidraw works at the moment, it will remove whole elements under cursor.

**Comment by dwelle** [comment]
Eraser now released 🚀 https://twitter.com/excalidraw/status/1502300183362781190 (via https://github.com/excalidraw/excalidraw/pull/4887)

We're also considering a more granular erasing behavior for the freedraw/line shapes. Share your thoughts in https://github.com/excalidraw/excalidraw/issues/4904

**Comment by Reno0vacio** [comment]
Is it not possible to create a script that captures the incoming bluetooth signal transmitted by the eraser function from the pen?
