### ISSUE TITLE
Creating a blank whiteboard

### ISSUE THREAD

**Issue by mani-ramaswamy** [excalidraw/excalidraw#2080]
It isn't intuitive to know what to change to create a blank whiteboard. It'd be good to have an icon/feature that creates a new one with auto-filled parameters.

**Comment by lipis** [comment]
<img width="196" alt="Screenshot 2020-08-25 at 9 52 43 PM" src="https://user-images.githubusercontent.com/125676/91215534-4ff8e180-e71d-11ea-8338-853be5afb067.png">

This one does exactly that :)

**Comment by mani-ramaswamy** [comment]
Thanks - though I would recommend the icon being changed, since the recycle bin icon isn't what I would hit normally when I need a new whiteboard. And I would also suggest documenting the icon functionality in the how-to guide.

**Comment by dwelle** [comment]
I kinda agree, but after further thought I'd leave this as is until we implement multi-tab support and the `new-file` button will actually create a new scene instead of trash the current one.

Not only due to semantics, but so that when we finally introduce it we don't silently & fundamentally change what that button does (from trashing to creating new scene).
