### ISSUE TITLE
Stable strokes for shapes

### ISSUE THREAD

**Issue by matias-capeletto** [excalidraw/excalidraw#211]
Hey there! Great tool :)

Currently, the strokes are not stable when creating o resizing a shape:
![stable-shapes-current](https://user-images.githubusercontent.com/583075/71833789-0421fb00-30ae-11ea-8a3f-2163232dd46e.gif)

Looks like Rough.js first draws the fill using a variable number of `Math.random` calls, so the stroke starts at a different seed even after using `withCustomMathRandom`. If you use Solid Fill this issue disappears, the first `Math.random` call is used for the stroke directly in that case.

It would be great as was discussed before if Rough.js would support stable strokes, in the meanwhile a possible workaround is to draw the fill and the stroke separately. I think the improved user experience makes the extra calls worthy. The only way I found to only draw the fill for the first call is to pass a `stroke: "rgba(0,0,0,0)"` though.

You can play with this approach in this forked code sandbox:
https://codesandbox.io/s/currying-architecture-8f7nt

This would be the result:
![stable-shapes](https://user-images.githubusercontent.com/583075/71834287-2bc59300-30af-11ea-927f-3ea0e41ee52f.gif)

**Comment by dwelle** [comment]
I think this is in fact desirable:

1. you may *want* to toy with an element until it looks "right"
2. if a shape is initially generated with a very rough edge and you freeze it, resizing it up the roughness gets magnified a lot.

**Comment by matias-capeletto** [comment]
I was thinking about that too @dwelle, it is one of the things that pushed me to create an issue first.

The problem with conflating changing the seed with resizing is that once you get a good one, you can not resize it without changing it or you have to start toying around again.

I think a better UX is to make the resizing stable + adding some way to change the seed. For example, a dice button in the sidebar for the shape or maybe allow something like a drag handle, Alt+Click or Alt+slide directly in the display to toy with it.

**Comment by vjeux** [comment]
Ohh, this is unfortunate :( Thanks for the great investigation!

I think the solution here is to ask @pshihn if it wouldn't be too annoying to reorder the shape generation to first generate the borders, which uses a fixed number of Math.random() calls and then the background, which uses a variable amount (based on the dimensions). This way it would solve the problem here.

We've already taken steps within excalidraw to keep the same seed and not regenerate shapes when not needed.

**Comment by matias-capeletto** [comment]
Following Rough.js code, it looks like you are right @vjeux. If excalidraw keeps the `curveStepCount` option fixed then the number of `Math.random` calls are going to be stable. So drawing the stroke first, then the fill in Rough.js would keep both of them stable while resizing. 

And looking at the code that generates the shapes, it looks like it is just a matter of moving the `rectangle(x, y, width, height, o)` call up before the fill generation, and then push it at the end. I think @pshihn may be open to the change. https://github.com/pshihn/rough/blob/12c29c10bdc96b1fe96e7d76ea5e0c15bb76a894/src/generator.ts#L15

**Comment by pshihn** [comment]
There are a couple of issues here that are on my list in roughjs that address this to some extent:
1) Seeding randomness
2) Update roughness and bowing variability based on the size of the shape - this issue is particularly visible for non-linear shapes like ellipses. The reason is that for ellipses, for example, I estimate `n` number of points on the perimeter of the ellipse and fit a curve through them. the value of `n` is configurable here but I had planned roughjs to automatically computer the value of `n` based on the size of the shape.  This is not hard to do, I just never got around to doing it. 

I have some time this week, and will implement these appropriately. 

As for the reordering of stroke/fill random calculations, it is a bit tricky because the number of points to randomize is a function of the size of the shape. I'll give it some more thought. 

Also, note that the shape of the sketched line can be preserved when the aspect ratio stays the same, It gets complicated when it's not.

**Comment by pshihn** [comment]
@matias-capeletto I can move the fill calculation after the stroke. It should not cause any trouble. 

Excited to see Excalidraw evolved, would love to play a small part helping it grow :)

**Comment by matias-capeletto** [comment]
Great @pshihn! Doing the stroke calculation first would at least keep some of the shapes stable without a more involved change. 

But I see your point, this should be an implementation detail to let you add later features like dynamic fitting for curves so a more careful solution is needed. 

If seeding is implemented in Rough.js, maybe you could allow the user to pass two seed for the shape, one for the fill and one for the stroke. If you want users to provide only one seed to simplify the API, then the same seed could be used for both the stroke and fill. Or the seed may be used for the stroke, and then modify it in a fixed way to do the fill.

Thanks for such an awesome lib by the way :)

**Comment by pshihn** [comment]
Thanks!
Btw, I have seen some people use Scaling transforms to keep the shape the same on resize. But, again it doesn't work as nicely when aspect ratio changes significantly. 
I will keep all these issues in mind when making my changes.
