### ISSUE TITLE
Display that binding is disabled

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#2112]
On macOS if you take a screenshot you disable binding until next cmd press. One way to ease the problem, and to generally improve the UX of binding, would be to display that binding is currently disabled.

Because we want to support cmd+shift for moving along straight lines and not binding it’s not easy to prevent the screenshot shortcuts (cmd+shift+4 etc) to break the UI.

**Comment by dwelle** [comment]
> you disable binding until next cmd press

Can you elaborate what you mean by that? Binding disabling happens only while Cmd is being pressed.

**Comment by xixixao** [comment]
When you press CMD+SHIFT+4, the key down is registered, but the key up isn't. So binding is disabled "permanently".

**Comment by dwelle** [comment]
I see. My first suggestion was to reset on `blur` but now I see you're already doing that. What's the mechanism then? OSX fires `keydown` when you press the `cmd`, but finishing the combo makes it so that `keyup` isn't fired (without any `blur` event and similar)?

Specifically the binding case can be fixed by moving temp-disabling from `appState` to `pointerDownState`. But not sure how you'd want to solve this in a general way (for other APIs).

**Comment by xixixao** [comment]
I am not sure we can move it to pointerDownState, then you’d have to keep pressing CMD on every drag, which might be inconvenient.

**Comment by dwelle** [comment]
What do you mean. Currently you *do* have to press Cmd on every drag. In the future we may implement a mode toggle, which will live in `appState` for sure, but then there won't be any issue with Cmd down/up events.

**Comment by xixixao** [comment]
You can press cmd, drag, drag, then release. If we moved the state to pointedDownState, you’d have to press cmd, drag, release and press, drag, release. Right?

**Comment by dwelle** [comment]
Nope, `pointerdown` event contains modifier keys information, too.

**Comment by xixixao** [comment]
Ah, that sounds good then! Less state to keep in appState is great.
