### ISSUE TITLE
Sticky arrows do not work well for all types of diagrams

### ISSUE THREAD

**Issue by wietsevenema** [excalidraw/excalidraw#2138]
Hi, 

I think the sticky arrows feature is very well done. It works well for graphs. 

There are also other types of diagrams where it doesn't work well, I am opening this issue to start a conversation about how the feature can be improved. 

I find myself deleting arrows and redoing them (I don't do many graphs).
Take a look at this [example diagram](https://excalidraw.com/#json=5738321212866560,cVnQ6e8kg5eNii-5en5uRg). 

- When you move the CPU usage label, the arrow vanishes. 
- When you move the autoscaler a bit down to align it, the perpendicular arrows need to be redone. 

What do you think? 

One alternative I thought of is to move the grey 'hitting areas' to inside the shape you're connecting to. Drop the arrow ON the shape and it pops to outside the shape?

**Comment by xixixao** [comment]
I think it was a mistake to enable binding by default. I completely agree it doesn't work for all kinds of diagrams, for me specifically any kind of "high-school"-like geometry.

@wietsevenema for the example you gave, the only change I would make is to disable binding to text. That gets rid of the CPU usage label (people have asked before for binding text to middle of arrows instead). The fact that you have to fix the perpendicular arrows seems fine - you'd have to do that without binding too.

Now I do think we should either make a mode toggle for binding, or flip the modifier key.  I don't want to have to constantly press CMD to be able to draw my diagrams, it's uncomfortable. cc @dwelle

**Comment by dwelle** [comment]
> I think it was a mistake to enable binding by default. I completely agree it doesn't work for all kinds of diagrams, for me specifically any kind of "high-school"-like geometry.
> [...]
> Now I do think we should either make a mode toggle for binding, or flip the modifier key. I don't want to have to constantly press CMD to be able to draw my diagrams, it's uncomfortable. 

Yea, at least until #2106 is implemented. But then I'll just learn to hold Cmd all the time as you stated, so that's not a good default.

I'm undecided between (1) mode-toggle and (2) hold-to-bind.

(1) is adding UI complexity, friction (you need to toggle on/off when you want to bind just a specific shapes), reduces discoveribility.

(2) also reduces discoveribility (people need to read the hint to figure out what to do, and people often don't do that. But then this applies to current behavior too).

If push comes to shove I'd definitely prefer (2) as it has better ergonomics (I believe that binding shapes is much less common than plain drawing, and as such hold-to-bind is perfectly acceptable).

(2) will also allow adding binding for lines since unintentional binds will become less likely (although in diagrams with lots of lines mixed with arrows it might still be an issue).

**Comment by wietsevenema** [comment]
I think hold-to-bind works best.

**Comment by xixixao** [comment]
I wouldn't rule out mode toggle just yet. There are types of diagrams (mind maps, state transition diagrams) where you want to bind almost constantly. It might be equally annoying to have to constantly hold cmd there.

Here's a PR to test the "modifier key to bind" version: https://github.com/excalidraw/excalidraw/pull/2146

**Comment by xixixao** [comment]
One thing I noticed already from #2146 is that it feels strange that moving an already bound arrow automatically unbinds it.

**Comment by ad1992** [comment]
Closing this as I have created a new issue where we will be discussing this and improve the overall UX for arrow binding https://github.com/excalidraw/excalidraw/issues/6685
