### ISSUE TITLE
Replace property toggle labels with icons

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#2201]
It always takes me a second too long to pick Fill/Stroke width etc. It's because I need to read the labels, and I never remember which order they are in. We should replace the labels with icons, I bet it would be much easier to use.

<img width="220" alt="Screen Shot 2020-10-04 at 21 13 24" src="https://user-images.githubusercontent.com/1473433/95039724-e253b400-06d1-11eb-8ab1-25940e792961.png">
WYSIWYG

**Comment by lipis** [comment]
That's an interesting one, obviously the current labels will become titles (tooltips).

What about the font family?

<img width="257" alt="Screenshot 2020-10-05 at 5 45 49 PM" src="https://user-images.githubusercontent.com/125676/95094472-9d139e80-0732-11eb-9594-ed5b90d9ced3.png">

**Comment by lipis** [comment]
While it's a big change on the UI, we should check it in action and iterate until we are happy with it.

/cc @vjeux

**Comment by vjeux** [comment]
It’s not a bad idea. Of course need to see how it looks in practice.

**Comment by lipis** [comment]
@xixixao are you up for a test?

**Comment by xixixao** [comment]
This is a pretty easy change, so happy for anyone else to take it. I'm busy with a move atm so might not have time to work on this for a while.

**Comment by ekdnam** [comment]
Can I do this? But would need some help from y'all!

**Comment by dwelle** [comment]
Sure. I suggest you start with just a few (e.g. the fill) so we can get a feel for how it'll look.

**Comment by ekdnam** [comment]
@dwelle  thanks! I am trying to find the script which needs to be modified to do this change, but have not been able to find it. Can you tell what is the name of the file and/or where it is located?

**Comment by dwelle** [comment]
Most element actions are defined as [actions](https://github.com/excalidraw/excalidraw/tree/master/src/actions) which specify both the logic and UI in the same place.

The fill action is here:

https://github.com/excalidraw/excalidraw/blob/63566ecb929ccfd755f56c7413fcb79ddfaa173b/src/actions/actionProperties.tsx#L128

You'll want to edit the `<ButtonSelect>` UI part.

https://github.com/excalidraw/excalidraw/blob/63566ecb929ccfd755f56c7413fcb79ddfaa173b/src/actions/actionProperties.tsx#L144-L160

End goal will probably be to make `ButtonSelect` component support rendering non-`<input>` buttons, so you can specify something like:

```jsx
<ButtonSelect
    options={[
        { value: "hachure", text: t("labels.hachure"), icon: icons.hachureFill },
        { value: "cross-hatch", text: t("labels.crossHatch"), icon: icons.crossHatchFill },
        { value: "solid", text: t("labels.solid"), icon: icons.solidFill  },
    ]}
    /* ... */
/>
```

But for the proof-of-concept you can just replace the `<ButtonSelect>` component with ad hoc JSX just so that we know how it looks in practice.

**Comment by ekdnam** [comment]
@dwelle thanks a lot for your help! I was going to make a PR to address what you have suggested, but I am having a hard time understanding the code base. I am currently busy with some personal stuff, so won't be able to spend the required time on this project.
Thanks a lot all for being so great!  

I am unassigning myself.
