### ISSUE TITLE
excalidraw Docker image is not working on RPi3

### ISSUE THREAD

**Issue by mrdc** [excalidraw/excalidraw#2209]
Hello,

I'm experiencing an issue with running excalidraw in Docker on Rpi3 - it's not starting at all. Don't see any errors.
On Win10 x64 image works fine.

Does it related to an incompatible architecture?

`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by pascal71** [comment]
There are some libs/pips not available on ARM64
Let me take a look at it

**Comment by mrdc** [comment]
@pascal71 Have you managed to check what should we do to run it on ARM64?

**Comment by ThisIsBenny** [comment]
Hi @mrdc, i was able to create a Docker image for arm and arm64:

https://github.com/ThisIsBenny/excalidraw
https://hub.docker.com/r/thisisbenny/excalidraw

It is running on my RPi 4 with Ubuntu 64Bit

I will create a RP to apply my changes to the official repo / image.

@pascal71 i didn't see any error due to not workings libs.

The current approach isn't the best, because I build the app on amd64, arm and arm64. Normally, it should be ok to generate the build outside of the container (no multi stage docker build) and copy the built files to the nginx docker image which can be a multi arch image. But I didn't want to change too much.

**Comment by mrdc** [comment]
Hi @ThisIsBenny 

Thanks for the update!

Unfortunately, I was not able to test due this error: 
`Using default tag: latest
Error response from daemon: manifest for thisisbenny/excalidraw:latest not found: manifest unknown: manifest unknown
`

**Comment by ThisIsBenny** [comment]
Hi @mrdc please use
thisisbenny/excalidraw:812c7ce24cf1b2b0375dea5f0ff56b9e3bf8db08

latest was broken due to #4355 why i have deleted the tag.

**Comment by mrdc** [comment]
@ThisIsBenny 
Thanks!
It works :)

**Comment by aniston** [comment]
any update of an official excalidraw build for OS/ARCH = linux/arm64 ?

many VPS providers are lately offering competitive ARM Ampere hosting solutions. [Hetzner](https://www.hetzner.com/news/arm64-cloud) for example and the current build of linux/amd64 will fail as well on RPix.

**Comment by aniston** [comment]
jumping to issue #4010 as its more relevant to the context of arm64 builds and since the issue is still open there.
