### ISSUE TITLE
Optimize the SVG with SVGO before exporting

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2305]
https://www.npmjs.com/package/svgo-browser

If it's not a huge overhead :)

**Comment by dwelle** [comment]
Makes sense, but damn is it big: https://bundlephobia.com/result?p=svgo-browser@1.3.8

![image](https://user-images.githubusercontent.com/5153846/97482774-e2547600-1956-11eb-9d20-0506aacd8992.png)

We can lazyload it, but I recently learned that due to PWA, we're precaching everything and as such download every chunk on first load (for each new release). Something to keep in mind.

(@ad1992 also a reason why I didn't want to bundle all node modules together because now when we want to use a small lib for something, we'll have to download a huge chunk of every node package.)

**Comment by lipis** [comment]
Maybe not worth it for that much..

**Comment by dai-shi** [comment]
why do you want to optimize the svg in the first place? is it too big?

**Comment by lipis** [comment]
Mostly the size.. but in the end of the day I think it's not worth the effort.

**Comment by dwelle** [comment]
If people tend to use the SVG on the web, it may be. I'm seeing 70% size savings on many diagrams.

**Comment by dai-shi** [comment]
Are there any drawbacks? I suppose people would optimize files before uploading on the web. Not sure if we really need to do it before exporting. (unless excalidraw has an capability of deploying files.)

**Comment by dwelle** [comment]
> I suppose people would optimize files before uploading on the web.

I wouldn't, people are lazy (and why shouldn't they be), or unaware, or lacking expertise to do it. Furthermore, we are already exporting the SVG, and as such it is our business to be doing our job the best we can, which includes optimization. We're already optimizing output size when embedding scenes to PNG/SVG, this is similar.

**Comment by dai-shi** [comment]
Fair enough. I'm not against it unless there's any drawbacks, like missing information. In my _old_ experience with SVGO, I felt optimizing too aggressively. (maybe because of some configs.)
