### ISSUE TITLE
Add border to text boxes

### ISSUE THREAD

**Issue by odedva** [excalidraw/excalidraw#2409]
Hi there,
It would be nice if test boxes will have automatic borders capability. i find myself struggling to add squares and group behind text all the time :)

other then that - this is an awesome product and I use it almost daily.
Thanks you!

**Comment by lipis** [comment]
I think the better idea would be, to be able to lock the text to the center of any shape. That way you can do more things and playing with backgrounds, paddings, shapes, etc..

**Comment by sojusnik** [comment]
Implementing [this](https://github.com/excalidraw/excalidraw/issues/1428#issuecomment-676221512) would make this issue obsolete.

**Comment by lipis** [comment]
Yeah something like that, but sticky notes it's a different thing.. we don't want those to be exported or printed.

**Comment by lipis** [comment]
We'll pass on this one, as it will require the text element to have extra properties to change the border color, possibly the background color and other ones that are not related to the text it self but to the background box of it..

**Comment by sojusnik** [comment]
Can you at least leave this issue open, because with this feature you can easily format text with optional boxes and so on by copy and paste the style? This is very useful to have, especially if you're doing text-heavy brainstorming sessions and try to maintain some visual structure by quickly formatting some text.

**Comment by copernico** [comment]
How about the option of reacting to a double-click on a shape by creating a text box with centered text right in the middle of the shape?

**Comment by dwelle** [comment]
We're already doing that when you dblclick in the vicinity of the center, but I guess we can make also it center the text when dblclicking on the element itself.

![image](https://user-images.githubusercontent.com/5153846/113138374-011ca880-9226-11eb-99b1-f3702ff2abb7.png)

In case of filled shapes, we can center the text when clicking on the fill also.

Note that you can also do this today by selecting a shape and pressing `enter` instead of dblclick.

---

In terms of single-clicking with a text tool, I guess it should retain current behavior even if you click on a shape?

**Comment by copernico** [comment]
@dwelle You're right, and I must have used that feature unconsciously a few times :-) What is missing though is then to group the text and the shape, because the most frequent action that follows the double click and the typing is a repositioning of the shape....at which point one finds that the text is left behind. Makes sense?
