### ISSUE TITLE
Inserting elements from clipboard or library with the grid on, the positions of the elements are all messed up

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2470]
Try to copy paste the following while having the grid on

https://excalidraw.com/#json=6234903687462912,mLfPmu5OpJnHVptTbI5_Sg

Also if you add this item to the library, same problem exists if add it back to the scene with the grid enabled.

**Comment by dwelle** [comment]
The problem is in how we align items on grid on paste in `addElementsFromPasteOrLibrary()`. When grid is enabled, we normalize positions of every pasted element so it lands on grid.

But it takes `x`/`y`, which in case of a bottom-aligned bar graph will end up misaligning it in case a given bar `x`/`y` (which is the top coordinate of the bar) isn't already aligned.

![image](https://user-images.githubusercontent.com/5153846/101632053-9ac90b80-3a25-11eb-9a3e-c7fffe7cf7a5.png)

If we top-align it, the pasted elements `y` positions are untouched (in the case below, `x` position are still messed up because they weren't on the grid to begin with):

![image](https://user-images.githubusercontent.com/5153846/101632228-e54a8800-3a25-11eb-86e4-8758bbb3960e.png)

Not sure what we can do here, since the algorithm doesn't know what your intent was.

**Comment by dwelle** [comment]
We can actually do this: check if the elements were copied from a scene with grid enabled, and on paste don't re-align if that is the case.

**Comment by dwelle** [comment]
Actually, scratch that. We shouldn't ever re-align anything but the group as a whole.

**Comment by lipis** [comment]
Not only if it's a group.. separate elements as well.
