### ISSUE TITLE
Cmd-z should update global state

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#259]
If you change the background color, cmd z should revert it back. Right now it keeps it as is

**Comment by enzoferey** [comment]
Looking at the code this happens because only the `elements` array is being stored in the history.

Simplest solution I can think of is to stringify `{ appState: { ... }, elements: [ ... ] }` instead. Then, we can grab both values when `redo` and `undo`. Finally, in order to only sync desired properties of the app state, I think we should hand pick properties inside the `componentDidUpdate` flow.

What do you think @vjeux ? Did you have something else in mind ?

**Comment by vjeux** [comment]
Yeah, that’s the idea on how to fix it! PR would be welcome

**Comment by enzoferey** [comment]
I will open the PR later today then 👌

**Comment by enzoferey** [comment]
Closed via #309.
