### ISSUE TITLE
Snap to objects

### ISSUE THREAD

**Issue by clementgenzmer** [excalidraw/excalidraw#263]
Arguable, and difficult to implement correctly. But most drawing apps have a snap to position feature. To make sure things aligned. Now by the very spirit of this tool, we don't want things to be too clean, and the snap to position should respect that.

I think it would be cool

**Comment by vjeux** [comment]
Agreed! @hmaurer has a cool proposal for attaching an arrow to an object here: https://github.com/excalidraw/excalidraw/issues/157#issuecomment-570937963 Would love for someone to implement it

**Comment by hmaurer** [comment]
@vjeux I am sick at the moment so happy for someone to take #157 up :-)

**Comment by vjeux** [comment]
@hmaurer oh noes, I hope you get better!

**Comment by lipis** [comment]
Snap to position or AKA snap to grid is different from snapping to objects.. I think we need the latter one more than the former due to the spirit of the tool.

Maybe changing the title to something more descriptive?

**Comment by dwelle** [comment]
I'm not sure what this issue is about actually. It seems it mentions both snap-to-grid and snap-to-object.

**Comment by lipis** [comment]
Let's just change it to snap to object for now. WDYT?

**Comment by clementgenzmer** [comment]
I think I did a poor job of describing it. Snap to object makes sense to me.

**Comment by dwelle** [comment]
I've edited the original post to remove mention of connect/attach-to-object, which we're tracking in [Attached arrows](https://github.com/excalidraw/excalidraw/issues/157).

So I'm still sure what the original intent of this issue was, but as of now, let's keep this issue to track *Snap to objects* as title suggests, which is widely used term to describe snapping during creating/moving/resizing:

![excalidraw_snap_to_object](https://user-images.githubusercontent.com/5153846/72973602-d804ba80-3dcd-11ea-9717-05448160044c.gif)

**Comment by steveruizok** [comment]
I'm working on snapping now for tldraw and I think I've got the math and logic worked out (see [here](https://twitter.com/steveruizok/status/1449873118777024512)). The solution is generic enough that it could be used in Excalidraw as well. 

Rendering for snap lines can get a bit noisy though. I'm curious, if snap lines were implemented in Excalidraw, what would that even look like?

**Comment by ngrilly** [comment]
Would be really amazing to have this!

**Comment by BaileySimrell** [comment]
Yeah this would be amazing
