### ISSUE TITLE
Feedback when copying to clipboard

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2664]
Would be great to add some kind of toast when we do shift-option-c to copy to clipboard. It's not clear that it's working right now.

**Comment by lipis** [comment]
Speaking of toasts.. saw recently a tweet by @steveruizok

https://twitter.com/steveruizok/status/1341665194733387777

(probably adding a library just for it.. it's not worth it though.. but it looks nice)

**Comment by rish07** [comment]
If there is a possibility of adding this feature, @lipis I would like to work on it

**Comment by vjeux** [comment]
@rish07 would be awesome! But let's not go overboard and keep the implementation simple :)

**Comment by rish07** [comment]
@vjeux Thanks for the quick reply. I am new to typescript and have only been a user of excalidraw but I am familiar with frontend dev in flutter. And I see this as an opportunity to learn something new. Could you help me with how to get started on this?

**Comment by steveruizok** [comment]
Toasts are fun. They can create some tricky animation problems when you have more than one on the screen at once because you need to FLIP current toasts to new their new position when older toasts disappear. See that example @lipis posted above.

We could simplify the problem by having only one toast on the screen at a time and making new toasts occlude / dismiss earlier ones. We could also have all toasts be a fixed size, which would let us animate by hand to known values without having to FLIP.

If we did want to have the whole package, we could still do the FLIP stuff ourselves without adding a library.

**Comment by steveruizok** [comment]
Are there other places in the app where we might want to toast a message? Maybe when a contributor joins, or when a project is copied / exported?

**Comment by lipis** [comment]
> Are there other places in the app where we might want to toast a message? Maybe when a contributor joins, or when a project is copied / exported?

When someone joins is a good idea.. maybe also when copying styles. We could use it in other places for sure.

**Comment by lipis** [comment]
> We could simplify the problem by having only one toast on the screen at a time and making new toasts occlude / dismiss earlier ones.

Yeah.. we should keep it simple. One toast at the time is more than enough..

**Comment by rish07** [comment]
@steveruizok Since I am new to this framework, how about you add a toast for when someone joins in and I'll follow your lead to implement similar thing for copy feature.
