### ISSUE TITLE
Add option to share link to read-only version

### ISSUE THREAD

**Issue by thijsv** [excalidraw/excalidraw#2832]
When sharing the link to a drawing, include the option to make it read-only.
This can be handy to send bigger files to people who do not need to adapt it.

**Comment by dai-shi** [comment]
The shareable link is already immutable and you can only copy&edit the drawing, no? I may misunderstand your point though.

**Comment by dwelle** [comment]
Correct. While you can still edit the scene, the changes are not persisted back to the server, so the original drawing is immutable.

Even if we later support updating link-shared scenes then we will likely still only allow to prevent updates from being synced to server, but allow local changes. This is so that people can do whatever they want on top, locally.

You could make a case that the diagram is "sensitive" and you want to preclude export etc., in that case I don't think sharing the link would be a smart idea as they could simply share the link with others in turn (and they could still get to the scene JSON data with a bit of reverse engineering).

For collaboration rooms that's a different story, and we plan to support read-only mode there: https://github.com/excalidraw/excalidraw/issues/1866

**Comment by thijsv** [comment]
Hi guys, thanks for the quick answers.
The idea was more to have like a quick share to a customer, to whom you want to present a schema or some wireframes. The only thing he can do (for example) is zooming and moving in the document. No drawing, no settings, ... just viewing.

Look at it like you can share designs using Figma or Invision.
What do you think?

**Comment by ad1992** [comment]
Maybe we can use the `readonly` prop in the URL for this which would give a minimal view as shown [here](https://github.com/excalidraw/excalidraw/pull/2840). Thoughts?

**Comment by dwelle** [comment]
We should clear up what the goal is. If it's only a UX thing, then `readonly` query param is fine. If it should serve some pseudo-security goal, then that won't do.

I'm not a fan of the latter though, as I mentioned above, since it will likely give people a false sense of security.

**Comment by ad1992** [comment]
@dwelle agreed I meant the UX thing only for this case and the user should also be able to move from read-only mode as well.

**Comment by lipis** [comment]
Let's keep all under #2842

**Comment by ad1992** [comment]
@lipis let's keep this as a separate issue ? since this is not about the collaboration mode but the shareable link for drawings in read-only mode.  And we can launch this soon after the read-only mode is launched.

**Comment by ad1992** [comment]
Since we have `view mode` now already so this feature might not been needed, hence marking out of scope.

**Comment by thijsv** [comment]
@ad1992 So is it possible to share it to someone in view mode? I know you can turn it yourself into view mode but this issue was created to:

1) make something in Excalidraw
2) pass a link to a customer so he/she can see it without controls and can not adapt it

**Comment by thijsv** [comment]
Hello @dwelle thanks for the quick reply. It is totally fine for me to place this out-of-scope for now.

Nevertheless I see the following as a logic use case, except eventual backend/storage logics:
- user A create something in Excalidraw
- user A wants to share it to user B via a link. User B opens the link and just sees the drawing. Nothing more.
- eventually user B can click on a link "edit this drawing" which switches to the editor mode

Except from coding perspective, what do you think of this UX logic? For me there is a lot of potential to share it to customers who don't bother about drawing theirselves and just want to see your drawing.

Thanks for all your work so far on the project. It's awesome.
