### ISSUE TITLE
Add read only mode as an option

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2841]
The idea is that you will still be able to select the elements (to copy them or see the properties from the stats dialog) and save the scene to a file at any time.

- [x] Add the action to the context menu: `Read only` (just like `Zen mode`)
- [x] Hide the top center toolbar
- [x] Hide the properties toolbar
- [x] Hide the canvas background color
- [x] Hide the reset canvas button
- [x] Disallow deleting elements
- [x] Disallow modifying elements (size, position, rotation, align, order, etc)
- [x] Disallow pasting elements or styles
- [ ] Instead of selection it should pan the canvas when mouse down and drag on empty canvas
- [x] Make the context menu contextual and only show minimal options applicable for readonly mode
  *  Copy to clipboard as png
  * Copy to clipboard as SVG
   *  show stats for Nerds
   *  Exit readonly mode
 - [x] Update mobile view
 - [x] Add a shortcut for readonly mode

**Comment by lipis** [comment]
Maybe selecting elements in read only mode could go on version 2.. but would be nice.

**Comment by dwelle** [comment]
- I'd rename the `read mode` to `presentation mode` since this feature is about UI and not about privacy/security/etc. behavior
- instead of showing save/save as/export buttons which for presentation mode doesn't make much sense, I'd add a button `exit presentation mode` similar to what we do with `exit zen mode`
- Similarly, I think allowing selecting elements etc. is not a good fit for a presentation mode. If you need to check their dimensions, or export selected elements etc., you shouldn't be doing that from a presentation mode. If you still want to edit with a lightweight UI, that's what zen mode is for. Let's not mix the two together.

**Comment by ad1992** [comment]
> * I'd rename the `read mode` to `presentation mode` since this feature is about UI and not about privacy/security/etc. behavior

+1 for this would also convey to the users to use this mode when presenting something to spectators.
We already have an issue for [presentation mode](https://github.com/excalidraw/excalidraw/issues/253) so might need to rename this then

Also, this means that for collab mode(when we implement it) we would call it sharing a link in `presentation mode` right?

> * instead of showing save/save as/export buttons which for presentation mode doesn't make much sense, I'd add a button `exit presentation mode` similar to what we do with `exit zen mode`

Thinking about this when we will implement read-only mode in collaboration mode the save as / export might be useful for spectators. WDYT?

> * Similarly, I think allowing to select elements, etc. is not a good fit for a presentation mode. If you need to check their dimensions, or export selected elements, etc., you shouldn't be doing that from a presentation mode in the first place. If you want to create/edit with a lightweight UI, that's what zen mode is for. Let's not mix the two together.

Agreed but same as the above what about spectators when we implement collab read-only mode?

**Comment by dwelle** [comment]
In case of collab there will be different use cases:

- Limit/hinder access to the underlying data (I'm still ambivalent about this).
- Prevent editing so that viewers can't interfere (or save back to server even outside the session) — in this case, exporting makes sense, but e.g. showing stats on selected elements doesn't. But it may make sense to allow selecting elements to either 1) highlight them to the collaborators/presenter 2) be able to export them individually.

There may be other use cases, and sub-use cases within those.

**Comment by ad1992** [comment]
If we agree that export/save options does make sense in collab presentation mode then I would suggest keeping it now as well so that UI doesn't change too much for the user and we can try to have a consistent UI for `presentation mode`. And it's not an invalid use case right ? as the user might want to save the drawing when the link (non-collab) shared in presentation mode as discussed [here](https://github.com/excalidraw/excalidraw/issues/2832) without switching to edit mode.

**Comment by dwelle** [comment]
Generally, the presentation mode should be used for what it's called: presentation. In that mode, displaying UI such as export/save buttons, or even language picker and the help button, doesn't make much sense.

Presentation mode should be distinct from read-only mode in that you shouldn't be able to exit read-only mode, and thus it makes sense to have all the necessary UI in there, as opposed to the presentation mode, which you can toggle off.

For example, take Figma's read-only mode: https://www.figma.com/file/Nx1aJOHJRTPcmhVwbNVKXF/Untitled?node-id=560%3A2

In that mode, you can even toggle presentation mode on top.

Whether we tackle presentation mode or read-only mode first, that's a different question. But if we agree that we want to eventually end up with both of these modes, then we shouldn't initially mix the two and later remove/add features to make them distinct, precisely so that the UI doesn't change over time as you mention above.

**Comment by lipis** [comment]
I was thinking more like a viewing mode for the read only like in Google Docs

<img width="242" alt="Screenshot 2021-01-26 at 10 29 47 PM" src="https://user-images.githubusercontent.com/125676/105901406-0131d980-6026-11eb-9597-6e3347cab2fe.png">


Maybe presentation can leave on it's own and remove more actions.. but readonly/viewing mode should also be selectable and only when you get a link for the readonly mode not able to switch, but still be able to select/export/copy elements since you have access to them (like you can copy/duplicate etc when viewing access in Google Drive)

My two cents.

**Comment by ad1992** [comment]
I get your point for presentation mode we should only show the drawing and a button to exit presentation mode (all other options including the footer should not be present) and for readonly we should not have exit read-only mode.

Presentation mode actually makes sense for the individual user who wants to present something to others (that time user can use presentation mode), but when it comes to collaboration read-only mode makes more sense (so the spectators can not come out of the mode).

Do we agree on that?
Then we can go ahead with the presentation mode for collab we can do the readonly mode.

**Comment by ad1992** [comment]
> I was thinking more like a viewing mode for the read only like in Google Docs
> 
> <img alt="Screenshot 2021-01-26 at 10 29 47 PM" width="242" src="https://user-images.githubusercontent.com/125676/105901406-0131d980-6026-11eb-9597-6e3347cab2fe.png">
> 
> Maybe presentation can leave on it's own and remove more actions.. but readonly/viewing mode should also be selectable and only when you get a link for the readonly mode not able to switch, but still be able to select/export/copy elements since you have access to them (like you can copy/duplicate etc when viewing access in Google Drive)
> 
> My two cents.

Just noticed your comment. So as mentioned above, I feel readonly / view only makes more sense when in collab mode / shareable links and presentation mode makes sense for an individual user and not collab mode. What are your thoughts ?

**Comment by dwelle** [comment]
Yes, in read-only mode we'll also want to show active collaborators, while in presentation mode we don't, etc.

**Comment by ad1992** [comment]
To summarize then we agree on having 
1. Present mode (support on Excalidraw and via prop as well)

    - [ ] An individual preference.
    - [ ] Show drawing and hide all other options
    - [ ] Allow switching to present mode context menu and also add a button to exit presentation mode when in the present mode. Or we want to have some button in the footer somewhere via which we can just toggle present mode coz in present mode context menu might not make sense so we might want to avoid it adding on context menu.
    - [ ] Allow to zoom/scroll/pan/copy in the canvas.
    - [ ] Allow selection ?
    
2. Readonly mode
     - [ ] show the drawings.
     - [ ] Show export, savas options.
     - [ ] Hide keyboard shortcuts(at least for the first version.Since we would want to make it contextual), properties toolbar, shapes toolbar, etc as discussed already.
     - [ ] show the footer (It depends on the host for example Excalidraw App if we want to hide the language selector but the core will always call the prop)
    - [ ] Not an individual preference but can be used in collaboration / shareable links and passed via prop
    - [ ] Should not be possible to exit read-only mode
    - [ ] show Collaborators.
    - [ ] Make the context menu contextual and only show minimal options applicable for read-only mode
    
        * Copy to clipboard as png
        * Copy to clipboard as SVG
        * show stats for Nerds
    
   Let's try to finalize this list and then I can update the PR accordingly(and separate the changes for read-only and present mode). 
   
This is how I was planning to break the tasks 👇 

1. Present mode (in excalidraw and host support).
2. Readonly (host support).
3. Allow readonly shareable links.
4. Readonly collab URL in Excalidraw App.

**Comment by ad1992** [comment]
Had a discussion with @lipis regarding the same and we agreed to keep only one mode to start with. 
We can rename the `read-only mode` to `view mode`. 

For collaboration view-only links and shareable view-only links, we can make the view-only mode irreversible.

And later we can add presentation mode as well if needed.

@dwelle what do you think?

**Comment by lipis** [comment]
Yes, let's keep it simple to begin with.

**Comment by dwelle** [comment]
Yea, let's start simple. Even if we get it wrong on the first try, it won't be a big deal.

**Comment by lipis** [comment]
We can track this feature for the time being..
