### ISSUE TITLE
Idea: press enter when shape selected to add text

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#285]
Since we now have ability to put text in center, this could reduce the need to double click in a precise location

**Comment by giovannigiordano** [comment]
It's a good idea! 🚀

**Comment by dwelle** [comment]
Not sure if overloading `Enter` is a good idea though, since if we later implement some sort of modification/state for a shape that needs to be confirmed, than double `Enter` will result in confirm + add-text. I think `Enter` should be idempotent *confirm* action in that regard.

Shouldn't we come up with a different key, or `Enter` + some modifier?

**Comment by nanot1m** [comment]
On mac os <kbd>Enter</kbd>'s default action on selected file is a renaming

**Comment by dwelle** [comment]
> On mac os Enter's default action on selected file is a renaming

Strange. What's the hotkey for open?

**Comment by nanot1m** [comment]
<kbd>⌘</kbd> + <kbd>O</kbd> or <kbd>⌘</kbd> + <kbd>↓</kbd>

**Comment by vjeux** [comment]
@dwelle that’s a legit concern. Since adding text in the middle of a shape is such a common use case, I’m trying to find ways to make it as simple as possible to do so.

**Comment by lipis** [comment]
> On mac os Enter's default action on selected file is a renaming

Which makes it perfect for pressing enter to add text to elements.
