### ISSUE TITLE
fix: when i share a live collabration room the app resets its apperance

### ISSUE THREAD

**Issue by fdemir** [excalidraw/excalidraw#2860]
i'm using on dark mode normally. But when i share live, it sets apperance to light mode. Is it a expected thing that suppossed to be?

**Comment by lipis** [comment]
If I understood correctly, you want the joined parties to have dark mode as well since you change it to dark?

Dark mode is personal preference and we are not changing that unless the user explicitly set it to dark (I think there is an open issue for doing it based on the system settings by default)

**Comment by lipis** [comment]
So if that's the case, we are not going to change it.. and leave this choice to the end user.
