### ISSUE TITLE
Stop showing encrypted info for Excalidraw package

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#2899]
We should not show 👇 since its specific to Excalidraw App and might not make sense for host
<img width="429" alt="Screenshot 2021-02-02 at 7 57 06 PM" src="https://user-images.githubusercontent.com/11256141/106614401-4f4c5d00-6591-11eb-9f36-19fe994b60a5.png">

Solution
We already have `renderFooter` prop but it can be used to render the footer on the right side so have two props `renderFooterLeft` and `renderFooterRight` ? and `renderFooterLeft`can be used in excalidraw-app to render the encrypted info.

cc @dwelle

**Comment by dwelle** [comment]
If we could combine it so that we can still have just `renderFooter`, that'd be best. Splitting it into left/right would also not make sense in mobile view.

So, `renderFooter` could have a free range over this part of the UI:

![image](https://user-images.githubusercontent.com/5153846/106615471-c02d4e00-656c-11eb-9539-620ee8fcbddf.png)

It will require us to move all the bottom menu inside the `.App-menu_bottom`, but I think we should be doing that regardless, same as we're already doing it with the top menu `.App-menu_top`.

**Comment by ad1992** [comment]
makes sense, will look into this 👍
