### ISSUE TITLE
Dynamic import inside the package makes it difficult to consume

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#3013]
My Excalidraw embed works in one Next project but breaks in another one:

<img width="702" alt="Screenshot 2021-02-12 at 04 42 40" src="https://user-images.githubusercontent.com/810438/107731524-1f6a2b80-6cee-11eb-8741-b2120e87b984.png">

It is very difficult to debug why webpack is attempting to load via non-root URL. I know that I'm supposed to adjust this via `__webpack_public_path__` but that's not super helpful since that can break other things.

I don't have any great solutions but this is a pain point. It would be nice if there was some way to just force Excalidraw to load from a particular path, _ignoring_ webpack variables. I would then hardcode it to root.

**Comment by gaearon** [comment]
Looks like this is because the bundle is trying to "guess" the public path from the current script.

<img width="673" alt="Screenshot 2021-02-12 at 05 12 08" src="https://user-images.githubusercontent.com/810438/107732732-fbf4b000-6cf0-11eb-9484-03116b1a057f.png">

Not sure how I could influence this process. How can I set `__webpack_public_path__` just for Excalidraw without it changing for my website itself?

**Comment by gaearon** [comment]
Here's my "fix" for now.

```js
[...document.getElementsByTagName("script")].forEach(el => {
  Object.defineProperty(el, 'src', {
    get() {
      return '/';
    }
  })
})
let  ExcalidrawImpl = require('@excalidraw/excalidraw').default;
```

:D

**Comment by winternicine** [comment]
Thank you.

On Feb 11, 2021 9:26 PM, "Dan Abramov" <notifications@github.com> wrote:

Here's my "fix" for now.

[...document.getElementsByTagName("script")].forEach(el => {
  Object.defineProperty(el, 'src', {
    get() {
      return '/';
    }
  })})let ExcalidrawImpl = require('@excalidraw/excalidraw').default;

:D

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/excalidraw/excalidraw/issues/3013#issuecomment-777982132>,
or unsubscribe

**Comment by CV1928** [comment]
> Here's my "fix" for now.
> 
> ```js
> [...document.getElementsByTagName("script")].forEach(el => {
>   Object.defineProperty(el, 'src', {
>     get() {
>       return '/';
>     }
>   })
> })
> let ExcalidrawImpl = require('@excalidraw/excalidraw').default;
> ```
> 
> :D

Where do I put it in the code? Just where that function is starting?

**Comment by ad1992** [comment]
> Here's my "fix" for now.
> 
> ```js
> [...document.getElementsByTagName("script")].forEach(el => {
>   Object.defineProperty(el, 'src', {
>     get() {
>       return '/';
>     }
>   })
> })
> let ExcalidrawImpl = require('@excalidraw/excalidraw').default;
> ```
> 
> :D

This is really a cool trick to override the script path :). 

It would be great if we could expose a window variable like `EXCALIDRAW_ASSET_PATH`  which could be used by hosts to lazy load the assets so it can be used for non webpack hosts as well.

**Comment by gaearon** [comment]
I was wondering why compiling with webpack is needed at all. Can you just leave dynamic `import()`s as is in the npm package? Seems like bundlers can handle it now.

**Comment by gaearon** [comment]
Another alternative is to provide limited functionality with fully synchronous imports, and then expose some way for users to load dynamic code from their app. E.g.

```js
<Excalidraw
  loadStuff={() => import('@excalidraw/excalidraw/stuff'))
/>
```

Then the default package never needs to worry about how code splitting works, and delegates it all to the app.

**Comment by dwelle** [comment]
I like the option of not compiling at all. I'm not sure if there was a specific reason to do that, or whether it was done to allow for cases like importing via a `<script>` tag (without needing to do a special deploy for that).

> Another alternative is to provide limited functionality with fully synchronous imports, and then expose some way for users to load dynamic code from their app.

That would be a lot of work since we'd have to design Excalidraw with that in mind. Right now we just lazyload whatever is heavy and doesn't need to be in the base bundle. There's also i18n.

**Comment by gaearon** [comment]
I think the `<script>` tag use case makes sense but maybe it should just be a separate output rather than the package entry point. So you can use it just for that, but in the main case the entry point refers to the source.

**Comment by gaearon** [comment]
So basically there's two use cases:

- You want to load it as a `<script>` tag. Then your setup is probably simple (just serving some static folder from some URL) and the current approach works well.
- Or you want to `import` it. In that case the requirement to serve assets under a specific URL gets painful cause it's like keeping two different universes in sync (and with a framework, you might just not have enough control over what gets served where). So the raw code is more useful in this scenario.

**Comment by ad1992** [comment]
> > Here's my "fix" for now.
> > ```js
> > [...document.getElementsByTagName("script")].forEach(el => {
> >   Object.defineProperty(el, 'src', {
> >     get() {
> >       return '/';
> >     }
> >   })
> > })
> > let ExcalidrawImpl = require('@excalidraw/excalidraw').default;
> > ```
> > 
> > 
> > :D
> 
> Where do I put it in the code? Just where that function is starting?

Yes just before requiring the package you need to add this.

> I was wondering why compiling with webpack is needed at all. Can you just leave dynamic `import()`s as is in the npm package? Seems like bundlers can handle it now.

Yep, the main reason behind bundler was so we have a umd build that can also be used to load directly via a script tag.
For the `lib` / `es` modules I don't recall exactly but was facing some issues when using in host due to some third-party deps so will check again on that, this would definately be helpful for `imports`

> You want to load it as a <script> tag. Then your setup is probably simple (just serving some static folder from some URL) and the current approach works well

Yes for host who wants to load via script can directly use `unpkg` CDN(currently) for that.

**Comment by giuseppeg** [comment]
Would make it configurable solve this issue? I worked on a similar library and we were doing the following in the library:

```js
// this goes in Excalidraw's entry file
__webpack_public_path__ = props.baseUrl || detectBaseUrl()
// detectBaseUrl would use document.currentScript.src and fallback to parsing the stack of an error generated on the fly with new Error()
```

@gaearon could then solve his issue with:

```jsx
<Excalidraw baseUrl="/" />
```

If I am not mistaken `__webpack_public_path__` should be scoped to your library (won't be shared with Next.js')

**Comment by ad1992** [comment]
@giuseppeg I had tried a similar kind of approach by reading a window variable `window.EXCALIDRAW_ASSET_PATH`and assigning to `__webpack_public_path__` in entry file instead of taking from props but that didn't work out. 
But probably I might be reading at the wrong place, will try it reading from props as you suggested. 

This would definitely help as there would be no dependency on the host to set the webpack path then and webpack path would be scoped to Excalidraw.

We would need to make sure that all imports happen assigning the `__webpack_public_path__` for example fonts then I think this approach would work.

**Comment by giuseppeg** [comment]
Happy to do a small pair programming session if you need help. 

> in entry file instead of taking from props but that didn't work out. But probably I might be reading at the wrong place, will try it reading from props as you suggested.

Probably because of this?

> Be aware that if you use ES6 module imports in your entry file the __webpack_public_path__ assignment will be done after the imports. In such cases, you'll have to move the public path assignment to its own dedicated module and then import it on top of your entry.js:

source: https://webpack.js.org/guides/public-path/#on-the-fly

**Comment by ad1992** [comment]
> Be aware that if you use ES6 module imports in your entry file the __webpack_public_path__ assignment will be done after the imports. In such cases, you'll have to move the public path assignment to its own dedicated module and then import it on top of your entry.js:

That's what I had tried :D earlier. Will give it one more try :)

**Comment by ad1992** [comment]
Sadly I was assiging `window.EXCALIDRAW_ASSET_PATH` at wrong place hence it wasn't working but now it works 🎉.
Thanks, @giuseppeg for sharing the props approach as well :)

**Comment by ad1992** [comment]
closing this via #3068

**Comment by gaearon** [comment]
Great, thanks!
