### ISSUE TITLE
Hints manager

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#335]
I’ve been thinking about how to implement the best hints.

Now that we have an action manager. Whenever an action is performed by clicking a button, we can add a small toast providing the corresponding shortcut.

For shifting the text faster, we can trigger a hint to press shift when we notice many movement in the same direction in a short period of time.

If the person clicks the text button, we can hint about using double click anywhere in the scene.

I think that this is a small attention but is going to be very high leverage in order to make users more efficient using excalidraw

**Comment by dwelle** [comment]
Not sure if you already have a concrete UI/imlementation in mind, but I propose doing pretty much what Affinity Designer does.

There's a "status" bar at the bottom of the app where there are context-specific hints:

![excalidraw_hint_proposal](https://user-images.githubusercontent.com/5153846/72218357-8ee57880-353a-11ea-9dd1-835353f31232.gif)

Benefit is it's minimalistic (doesn't bother users), ever-present (no need to come up when/if a hint is supposed to be shown).

One downside is that if we can't fit all the hints onto one line, they'll be cut off (Affinity does the same), because I don't think we'll want to expand it to multilines which would cause canvas jump. But I think we should generally strive for the least amount of hints we can manage.

**Comment by vjeux** [comment]
Nice, yeah something like this. Agreed we should only have a small amount of useful hints

**Comment by lipis** [comment]
I think we can close this for now..
