### ISSUE TITLE
Add the ability to have arrows on free draw

### ISSUE THREAD

**Issue by bric3** [excalidraw/excalidraw#3448]
I would like terminate a free draw line by arrows (for both ends), currently only the following options are supported :

![image](https://user-images.githubusercontent.com/803621/114867201-c8b7c580-9df4-11eb-92d6-2fd903ba387b.png)

The option could the same os the one for arrows : 

![image](https://user-images.githubusercontent.com/803621/114867690-63180900-9df5-11eb-9609-2e8aa0c31d05.png)

**Comment by ad1992** [comment]
little unclear, why not use arrows instead of drawing free draw line for this case?

**Comment by bric3** [comment]
Actually I wanted a non straight path between two points, which is currently not possible with current arrows.

**Comment by dwelle** [comment]
> Actually I wanted a non straight path between two points, which is currently not possible with current arrows.

It is. You just need to make a multi-point arrow by clicking instead of dragging (check the tooltips below the toolbar when you select an arrow). Technically, there's nothing you cannot achieve with a line/arrow that you can do so with draw, since underneath it's the same thing — it just differs in how it behaves when you draw.

**Comment by bric3** [comment]
> You just need to make a multi-point arrow by clicking instead of dragging

woah, I missed that, thank you !
