### ISSUE TITLE
[RFC] use CRDT for collaboration

### ISSUE THREAD

**Issue by kyle-mccarthy** [excalidraw/excalidraw#3537]
I think that using CRDTs for collaboration would provide better performance and data integrity. It should be possible to use an existing CRDT implementation like [yjs](https://www.npmjs.com/package/yjs) rather than rolling a custom solution.

_Disclaimer: I realize this is a nontrivial RFC and is easier said than done._

**Comment by dwelle** [comment]
Hey Kyle. Sorry for missing this.

At some point we may start using CRDTs, but for now it seems unnecessarily complex solution. It may change soon, though :0.

**Comment by alsuren** [comment]
I'm highjacking this thread to write up my thoughts from tuesday's livecoding session (https://twitter.com/kevin_jahns/status/1440635129928380418) before I've completely forgotten them. I am starting a new job next month, so I'm unlikely to make progress on this anytime soon.

 I *think* that using yjs would allow excalidraw to support concurrent edits to text boxes. It feels like quite a lot of work though.

Minimal demo version would be:
* rip out excalidraw's App.scene.elements array and replace it with a Y.Array or something
  * probably also normalize .elements and elementsMap into a single structure, because the denormalized version feels like a recipe for pain.
  * for backwards-compatibility, maybe convert the elements struct back into an array and pass it into the onChange handler. Feels expensive though.
* use the webrtc provider for comms
  * pro: it already supports e2ee out of the box for the signalling channel, and the data channel is e2ee using DTLS-SRTP 
  * pro: it's pretty quick, and there's no server bottleneck
  * con: no persistence
  * con: data channel is not http, and it's common to end up with a net-split if some clients are in firewalled environments/certain GSM providers

This wouldn't solve the "concurrent edits to the same element" problem though: it would just be a tech demo of what's possible.


Release quality version would need:
* Somehow hide all changes behind an opt-in feature flag.
  * This would allow us to merge to main as we go and test things thoroughly in production before enabling the feature more widely.
  * One option would be to encode the yjsness in the url by putting a y in front of the room id (https://excalidraw.com/#room=yc9e1cd7c34d306fb985a,ogZG1yuCwU6BtGAaKnkrqw) since excalidraw won't naturally generate room ids with y at the start.
  * It might be that we could create a typescript IScene interface that is implemented by Scene and YjsScene, and swap to a YjsScene only when we start a yjs-enabled room.
* Concurrent edits to the same element
  * Would probably need to re-think how onChange notifications happen at this point, so you can properly reconcile concurrent edits to the same element. Could go all-in on yjs and pass the yjs events down? Not sure.
* Persistence
  * It should be fine to have multiple providers for comms, so you could have a webrtc provider plus a websocket provider plus a firebase provider if you wanted.
    * My instinct says that you would end up with traffic amplification if you did this, so you might want to stick to just webrtc+firebase? This was not discussed on the call though, so it might be that yjs is able to avoid this problem out of the box?
    * Multi-provider presence information? Presence (cursor position) is also a crdt, but simpler. Recommendation is to have the presence info come from the lowest latency provider. Not sure whether there is a sensible way to combine presence from multiple providers.
    * There's probably some edge cases if webrtc can't connect but firebase can for some users - they would have a laggy experience and probably wouldn't see anyone else's cursors. Would be good to reflect this status to the user somehow (we currently don't indicate to the user if their websocket connection is down. This should probably be fixed even if we don't use yjs)
  * Kevin mentioned that a firebase provider exists but might be closed source. Apparently providers are not too complex to build though, so building our own and open-sourcing it would be fine.
  * E2EE:
    * Kevin mentions that https://www.serenity.re/en/notes uses yjs+e2ee persistence, so we could look into what they're doing.
    * This has also been discussed in the yjs forums before (https://discuss.yjs.dev/search?q=encryption yields https://discuss.yjs.dev/t/implementing-end-to-end-encryption/308). Basically store an opaque log of encrypted synchronisation messages (have the database generate an auto-incrementing index) and clients `select id, encrypted_payload from messages where id > largest_id_i_know_about`, then decrypt them and send to yjs. Seems simple enough. We could keep statistics on the length of the synchronisation message history and how long it takes to load drawings with lots of history, and devise a history compaction scheme if we notice problems later.

**Comment by WofWca** [comment]
I just want to throw this at you. I know some other collaborative tools.

There is CryptPad. [Their docs say](https://github.com/cryptpad/cryptpad/blob/a3772cf92c448e893cf8e021cfe9149939d3fd6c/docs/ARCHITECTURE.md) that it uses somewhat of a less known CRDT algorithm, they call the library [Chainpad](https://github.com/cryptpad/chainpad). For transport [they're using WebRTC](https://github.com/cryptpad/cryptpad/blob/main/docs/ARCHITECTURE.md#transport), namely a library called [Netflux](https://github.com/coast-team/netflux).

The Netflux library used to be used by another collaborative editor called [Mute](https://github.com/coast-team/mute), but they have since [migrated to `libp2p`](https://github.com/coast-team/mute/blob/99ec0c567b47fe0bd3512b383db808f54213c15b/README.md#hammer_and_wrench-architecture).

**Comment by WofWca** [comment]
There is this project which seems to be using [Loro CRDT](https://www.loro.dev/) to sync an Excalidraw board:
https://github.com/loro-dev/loro-excalidraw/tree/main

**Comment by satoren** [comment]
I tried creating Yjs bindings.
https://github.com/satoren/y-phoenix-channel/blob/main/assets/js/y-excalidraw.ts
[Demo](https://y-phoenix.gigalixirapp.com/excalidraw)

**Comment by RahulBadenkal** [comment]
I was working on yjs bindings for excalidraw but @satoren beat me to it.
Anyways here's the implementation -> https://github.com/RahulBadenkal/y-excalidraw (Took some good parts from @satoren 's repo)
[Demo](https://y-excalidraw.rahulbadenkal.com/)

Can be installed via ``` npm install y-excalidraw ```
