### ISSUE TITLE
Freedraw creates points instead of lines too often

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3564]
All of a sudden my inputs, both Wacom and mouse, started to terminate in points instead of letting me draw lines way too often. This was happening to me even before, but now it happens more often than not. Unclear why (CPU load?).

![excal_freedraw_point_bug](https://user-images.githubusercontent.com/5153846/117717392-0bde3c00-b1db-11eb-82a8-86050c7b6b63.gif)

/cc @steveruizok

**Comment by dwelle** [comment]
Now I can't repro anymore. Note that before I could repro consistently, in different tabs and different apps (Excalidraw & Excalidraw+), both mouse and Wacom, and I even tried unplugging the Wacom to make sure it doesn't interfere in some way.

**Comment by steveruizok** [comment]
Does this happen with any of the other tools? With those shapes, it might look like a missed input instead of a dot: the only thing different about how we're handling the free draw element is that we don't discard shapes without dimensions (i.e. only one point) because those are usually dots.

**Comment by steveruizok** [comment]
There was an earlier problem with missed strokes due to bad SVG data, but that should be fixed. Try checking in dev whether it's still registering pointer move events after a dot, which would lead me to think that we bailed on the shape too early. If not, then it's something to do with our events, and a pointerup or pointercancel must have snuck in somehow. Wacoms can be very sensitive so we may need to debounce(?) the pointer down / pointer up events.

**Comment by dwelle** [comment]
`pointermove` fires normally. Affects mouse as well.

**Comment by dwelle** [comment]
Can repro on Mac M1 touchpad, too.

**Comment by johnatannvmd** [comment]
Same here. Mouse works without any issues, only tablet. GIMP for example works well on both.

Fedora 33
FF 89.0b13 (64-bit)
Chrome Version 90.0.4430.212 (Official Build) (64-bit)
One by Wacom (medium)

**Comment by rareconf** [comment]
+1 on this happens at unpredictable frequency.

Platform: Linux
Browser: Brave Browser

https://user-images.githubusercontent.com/69213917/121069937-b43bec00-c7eb-11eb-8584-b97b421a5406.mp4

It looks more like a rendering issue, as those points are captured by excalidraw (as selection tool shows in video), and inspecting json as well points are being captured.

**Comment by rareconf** [comment]
I think, i have found the issue here.

Here is my observation:
Assuming it as rendering issue I started looking for values in json which could be invalidating that element from rendering. What I found was that when first two points in array of points are same it doesn't renders the element completely, **although it doesn't had any issue when there were continuous duplicate points in middle section of array or at the end of the array**.

So I removed the duplicate points from starting and loaded that .excalidraw file again and voila that element got rendered correctly.

| Before                                          | After                                           |
| ----------------------------------------------- | ----------------------------------------------- |
| ![CopyQ DPoLLm](https://user-images.githubusercontent.com/69213917/121157996-a461ed80-c867-11eb-9ef2-6d5f0006f331.png)| ![CopyQ IglDtN](https://user-images.githubusercontent.com/69213917/121158133-c0658f00-c867-11eb-92ca-dfcb7863eb03.png)|
| ![CopyQ SOCoyc](https://user-images.githubusercontent.com/69213917/121158250-d70be600-c867-11eb-82d5-52abbda629cd.png)| !![CopyQ TsLSgH](https://user-images.githubusercontent.com/69213917/121158807-44b81200-c868-11eb-9251-1cfcfcd89d6b.png)|

The Steps to reproduce would be
- Either try to hold pen a while at a point and then move so that it contains starting duplicate elements of [0,0].
- Another way would be to draw a simple shape with free draw.
Export it in a file.Go to that element's points array and duplicate the 0th index.
Load again that file (element won't be rendered).

What i am thinking is correct behavior would be to render a dot even if it has same points from start to end.

**Comment by steveruizok** [comment]
I think that's it. I was pretty sure we already tested against the previous
point to avoid adding doubles—if not, we should do that. The algorithm
creates new points too when it smooths the input points, and so may end up
producing duplicates that way; I'll try and fix it in the library just to
be sure.

**Comment by pszponder** [comment]
I am having an issue where I am using the online version and trying to use the free draw but am getting points instead

**Comment by idvorkin** [comment]
Are there any workaround for this? ￼

**Comment by mp3guy** [comment]
Another repro here, Chrome on Linux.

**Comment by fev4** [comment]
Found this same problem and created a separate issue, sorry about that. I already closed the other one. Gonna paste its content here in case it's of any use. 

Here's a video showcasing the problem, it's seems to be more frequent with a Wacom than with a mouse.

https://user-images.githubusercontent.com/16828078/133317582-ec283f5e-79a2-4434-b55e-a66b07264af7.mp4

Same results while in incognito (to avoid any possible problem with other extensions):

https://user-images.githubusercontent.com/16828078/133318644-3d323791-33da-4196-a6de-8662ebdddcfc.mp4

I've done this same test with Miro and with Krita and there is no such problem, which suggests that it's as problem with Excalidraw directly.

I'm using: Version 1.29.76 Chromium: 93.0.4577.58 (Official Build) unknown (64-bit) on Linux Manjaro.

Here's also the `.excalidraw` generated:
https://excalidraw.com/#json=6676180954513408,7aXSuolsMNOXkfaPDH1RNw

**Comment by dwelle** [comment]
Actually, it's not fully fixed. I could repro on multiple new occasions:

https://excalidraw.com/#json=5982464447086592,W9k4FgnmE6tAsmkxkVidNw

**Comment by pszponder** [comment]
I have been playing around with this today and it has been working great for me on google chrome!

**Comment by fev4** [comment]
I'm not able to replicate @dwelle's results, how did you do it?

**Comment by dwelle** [comment]
@fev4 No clue. I just took it to town with Apple Pen.

**Comment by idvorkin** [comment]
I gave it a quick try with Apple Pencil on iOS 15  and it worked without issue.  (I did have to disable scribble per #3955 )

**Comment by idvorkin** [comment]
> https://excalidraw.com/#json=5982464447086592,W9k4FgnmE6tAsmkxkVidNw

Wow, @dwelle  is that your hand writing? That's amazing!

**Comment by dwelle** [comment]
@steveruizok it's connected to this issue https://github.com/excalidraw/excalidraw/issues/4007 — single-point freedraw elements (in terms of rendering) shouldn't consist of two points.

All the "buggy" dots from excalidraw.com/#json=5982464447086592,W9k4FgnmE6tAsmkxkVidNw are actually 2-point elements with the 2nd points offset enough to form a big bounding box.

**Comment by dwelle** [comment]
This appears to have been fixed somewhere along the path. If anyone can still reproduce, we will reopen.
