### ISSUE TITLE
Scrollable context menu

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#3732]
On a smaller screen, it may happen that the context menu does not fit. Making the menu scrollable would address this problem.
![image](https://user-images.githubusercontent.com/14358394/121797011-adfba480-cc1d-11eb-840a-4d0676bc2d0e.png)

See also: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/73

**Comment by dwelle** [comment]
It must have regressed as it's supposed to reposition itself to fit on screen. It should indeed fall back to scrollbar if it can't fit at all.

**Comment by ShubhamCanCreate** [comment]
I don't know if the bug is a regression or not but this PR(#3399) still has the bug in it.

It appears that there is re-rendering of the ContextMenu when the `viewMode` is disabled and clicked on the canvas. You can see that when I click on element: text, circle, etc.. the contextMenu would be rendered once as seen in the browser console and twice when clicked anywhere else. 

When element is clicked:
![element-context-menu](https://user-images.githubusercontent.com/52590791/135831831-ddd0acc2-446c-4403-bdcf-5512ab90ff72.gif)

Otherwise
![canvas-context-menu](https://user-images.githubusercontent.com/52590791/135831889-44b0cd0f-e275-4789-adf2-1612b7216105.gif)

**Comment by ShubhamCanCreate** [comment]
I've opened a PR. @dwelle Can you tell if I am on right track?

**Comment by dwelle** [comment]
Actually, I'll reopen this because the issue is about contextMenu being scrollable, which it currently still isn't when it doesn't fit the window height.

/cc @ShubhamCanCreate if you wanna take this as well

**Comment by ShubhamCanCreate** [comment]
Cool. I'll do that.
