### ISSUE TITLE
switch to selection tool on library item insert

### ISSUE THREAD

**Issue by Illusion3D** [excalidraw/excalidraw#3765]
White board: switch to mouse mode (movement) when adding a template.
Because when you are in text or other drawing mode (rectangle, circle...), instead of moving the template, you make an involuntary drawing.

**Comment by dwelle** [comment]
What do you mean by a template? A file you're using to seed new scenes?

**Comment by vincentfretin** [comment]
I asked @Illusion3D to create this issue. By template here, he meant a component from the library.

**Comment by vincentfretin** [comment]
To reproduce, first you need to have a component/element/item in the library.

Scenario: 
- select draw mode, draw something if you want
- click on library icon, select an item
- the item shows up on the center of the canvas, I want to move it right away by clicking on it and moving the mouse but instead of moving it I start to draw.

I think the excepted behavior here should be the following:
- select draw mode, or any other actions excepted selection
- click on library icon, select an item
- the item shows up on the center of the canvas, *the selected action goes automatically into selection*
- I can click on the newly added element to move it

**Comment by dwelle** [comment]
Ok, that makes sense. I can imagine a case where *not* reverting to selection may be useful, but I agree it makes more sense to do so. We're also incorrectly showing the bounding box as if you were using the selection tool.
