### ISSUE TITLE
Apple Pencil and Galaxy Note Stylus support

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#3838]
These two features would go a long way to making Excalidraw pen friendly:

- ~~To add points to a line, currently only possible with a keyboard.~~
- Palm rejection when pen is active.

**Comment by zsviczian** [comment]
Adding points to the line has a workaround. Thanks @dwelle!
![image](https://user-images.githubusercontent.com/14358394/126101510-87cfcf5f-21bd-4162-b9ed-c8ce6ec8fb2d.png)

I also disabled the "Scribble" feature on the iPad as recommended by @steveruizok 

Palm rejection would still be very useful. 

Palm rejection would still be very needed.

**Comment by niieani** [comment]
Palm rejection for iPad should be easy enough to implement since Safari supports the `touchEvent.touchType` `'direct'` and `'stylus'` respectively.
I guess the question is how do know when to flip into the mode where `direct` touch events should be rejected or treated as zoom/pan. Is there a special button for this, or do we assume that after at least one Touch Event with `stylus` type? 
But then touch input would be broken if someone where to put the pencil down. 

One workaround would be to only show a button that disables pen input once it's been auto-enabled. I don't think there's another way.

**Comment by zsviczian** [comment]
Additional requirements by @slimhk45 (Obsidian issue [#314](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/314)):
_Currently when we are drawing we are stuck to the view we set in and need to change the tool to be able to move it. It would be better to be able to use the finger for moving the canvas view and a stylus to write._

**Comment by niieani** [comment]
@davidsu I think instead of trying to satisfy every browser and every pen, it would be probably easier to break the work into smaller chunks. Work could be broken down to at least 5 separate PRs:

- [ ] support Apple Pencil on Safari
- [ ] support Android styluses in Chromium
- [ ] support Android Styluses in Firefox
- [ ] differentiate using finger to move the canvas vs writing with stylus
- [ ] support variable brush stroke width from the pressure information

**Comment by dwelle** [comment]
@niieani @davidsu I'm not sure we can implement a solid palm rejection in a cross-browser cross-device way. At least I don't know of any app that does it well (Figma/Figjam tries, but falls short).

@davidsu I've tried excalidraw-davidsu.surge.sh but it doesn't seem to allow drawing at all?

I think the way to go right now is implement a pen mode: https://github.com/excalidraw/excalidraw/issues/4202

**Comment by dwelle** [comment]
I'm closing this via #4532  (https://twitter.com/excalidraw/status/1488884968243740674)

If we want to either improve or implement a better palm rejection, let's create new issue(s) for that.
