### ISSUE TITLE
Feature Request: When [[ entered in text box filter list of Obsidian Notes

### ISSUE THREAD

**Issue by adxsoft** [excalidraw/excalidraw#3867]
Obsidian will filter and display selections after **[[** is typed in. 

Would be great if you could do this when entering links into Excalidraw Text boxes.

Use case for me is I am creating concept maps and it would be very handy to be able to choose the link target in the same way Obsidian filters and displays potential link targets.

If the same Obsidian logic could be utilised then could search note, blocks and lines etc.

Workaround is to open a temporary note in a separate pane and type links and choose what you require and then paste it into the Excalidraw drawing

Thank you for all the hard work .. its a brilliant plugin for Obsidian

**Comment by dwelle** [comment]
I understand this is a request for the Obsidian plugin? There's a separate issue tracker for Obsidian: https://github.com/zsviczian/roam-excalidraw-issues/issues

When we add support for hyperlinks (https://github.com/excalidraw/excalidraw/issues/1205), we'll consider using the same [[]] syntax — though the initial implementation is aiming for a UI instead of a markup flow.

**Comment by adxsoft** [comment]
Thanks. Will post the issue in the appropriate place as per your link provided
