### ISSUE TITLE
Is this an Excalidraw ripoff?

### ISSUE THREAD

**Issue by ElianCordoba** [excalidraw/excalidraw#3868]
A coworker just sent me this [website](https://www.tryeraser.com/home).

https://help.tryeraser.com/what-does-eraser-cost/
https://help.tryeraser.com/compatibility-with-excalidraw/

**Comment by pvaliyaveedan** [comment]
That application is built on excalidraw. It's mentioned in their website.

**Comment by ElianCordoba** [comment]
I know it's built on Excalidraw, but I'm a bit uncertain on the legality of monetizing the project, they said it's free for now but could change in the future. I'm not very knowledgeable on OSS licenses but I know that there have been instances where private companies have just forked a project and started selling it, see the chess engine [Stockfish case](https://stockfishchess.org/blog/2021/our-lawsuit-against-chessbase/) for instance

**Comment by vjeux** [comment]
Thanks for raising this. Excalidraw itself is MIT and doesn't have the same kind of restrictive license as Stockfish. My goal with Excalidraw is to make it available to everyone where there's a need for a whiteboard. In practice, you need a business to be able to reach a lot of the workforce, where Excalidraw is most useful. We're building Excalidraw+ to help reach this market and Eraser is going at it from a different angle going at it through meetings. I wish them good luck and am super excited that more people are evangelizing Excalidraw!

cc @shinkim0914 if you have more thoughts!

**Comment by shinkim0914** [comment]
Thanks @vjeux for the cc!

Hi Excalidraw community! Founder of Eraser here. We're Excalidraw enthusiasts like everyone else here. We're thankful that we were able to leverage Excalidraw for our canvas module and want to be contributing members of the ecosystem.

As @vjeux mentioned, Eraser's scope is a bit different from Excalidraw / Excalidraw+. We're not just about drawing, but also drafting documents, speaking over audio as you can see in our product today. We also want to build a shared browser (imagine Zoom screenshare but actually collaborative).

Lastly, we wouldn't do anything that's against the MIT license since we're not trying to build a fly-by-night operation. Happy to answer any other question!
