### ISSUE TITLE
Pasting text outside of wysiwyg does nothing

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#397]
It may be good to mark the json copy/paste payload with a flag (eg: `"type": "excalidraw"`) so that if we're not pasting shapes, we create a text node with the text at the center of the screen/mouse position.

Not 100% sure we should do it but it's an interesting suggestion from Ivan Babak

**Comment by dwelle** [comment]
This would prevent moving forward with https://github.com/excalidraw/excalidraw/issues/386 since we wouldn't know which clipboard should take precedence.

Technically, we could implement a hybrid system, where in-app `ctrl+c` would also override (clear) system clipboard. This is what native desktop apps seem to be doing.

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/689
