### ISSUE TITLE
resizing from center doesn't work for groups/multiselection

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3989]
steps:

1. create to elements and group them OR select them all without grouping
2. resize the group while holding `Option/Alt` to resize from center
3. doesn't resize from center

**Comment by ishandeveloper** [comment]
@dwelle Would love to work on this one. Just to confirm, The expected behavior is that the origin of resize for that group should be center, but only in case the user is holding Option/Alt key right?  Something like this?

https://user-images.githubusercontent.com/54989142/134804551-4f21b2e8-47f0-41d2-a2fe-8a662b468986.mov

Or Is there something else I'm missing? Let me know if I should create a PR? 🙂

**Comment by dwelle** [comment]
That's correct!

**Comment by ishandeveloper** [comment]
> That's correct!

Awesome! will raise a PR 🙂
