### ISSUE TITLE
Switch to the Text tool on double-click

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#399]
Related to #163 and #398

This may be controversial, but for the sake of seeing and being able to tweak text styles while entering text, it may make sense to switch to the Text tool.

Currently, it keeps the currently selected tool (e.g. shape), but to apply the text I still click outside of the text area which switches to the arrow tool.

**Comment by dwelle** [comment]
Instructions unclear :). You mean when you have `recrangle` tool selected, and doubleclick with it, it should insert text?

**Comment by dwelle** [comment]
@sompylasar btw, the PR that closed this doesn't exactly do what you want, but I'm not sure what you  had in mind to begin with. The text tool isn't selected when you click (and create a text element), normally. If you meant to ensure the text panel (settings) is shown, then that has been fixed in the PR. Otherwise, feel free to open a new issue, and make sure to be more descriptive.
