### ISSUE TITLE
Laggy handwriting input on iPad Pro

### ISSUE THREAD

**Issue by jez** [excalidraw/excalidraw#4205]
When I use excalidraw on my 2nd generation iPad Pro 12.9" the handwriting input is extremely laggy compared to what it is in all desktop/laptop browsers. I’ve included some screen recordings to demonstrate the effect, but they don’t quite do it justice unfortunately because you can’t see where the point of contact with the screen is. But you can still see the effect because for many strokes a whole hunk of ink will appear on screen all at once, instead of immediately after having made the stroke.

https://user-images.githubusercontent.com/5544532/140473100-7a8a4f9b-5081-4fdf-a142-d2293a42c622.MP4

https://user-images.githubusercontent.com/5544532/140473109-3a17c4d4-398a-46df-b5d1-9c317bd0d55b.MP4

These were recorded on iOS 15.1 in Safari using the first generation apple pencil for handwriting input.

If there’s any other information about the set up that I can provide, I’m happy to help. If this sort of issue is not generally accepted here, I’m happy to move it elsewhere or close it. Thanks to vjeux for [suggesting to report this](https://news.ycombinator.com/item?id=29115687).

Thanks in advance for a great tool.

**Comment by vijaybritto** [comment]
This happens in Samsung Tab S6 too. It happens in Chrome/Brave browsers

**Comment by dwelle** [comment]
This touches on two things: 1) performance issues plaguing our renderer itself that we need to address as a whole, on a continual basis 2) the way the library we're using for the free draw tool works.

(2) the line is re-computed in its entirety every time _while_ you're drawing a given stroke. That said, your strokes are small enough (letters) that it should have almost no effect. On my iPad I see lags if the stroke is long enough to cover roughly 1/4 of the screen area.

(1) is more involved and there's no easy fix. One larger optimization is planned, but it again wouldn't have any effect in this case because it's apparently laggy from the first strokes.

Do you see any issues on https://perfect-freehand-example.vercel.app? If not, then it'd suggest it's a problem of our renderer.

**Comment by vijaybritto** [comment]
@dwelle  I just tried the experiment as you suggested. Its not getting progressively worse like seen here. I tried writing a long paragraph and it was fine. There is a delay between the input and the display but its consistent from the start. But in excalidraw its struggling to write it out. Looks like all the strokes are being rendered all the time rather than only the newly added ones

**Comment by exikyut** [comment]
I was wondering if this was stroke-length dependent. Yeah. Tricky one.

I had a bit of a play around on my old Note 4 (which has an EMR display and stylus), half expecting the device hardware and/or Android vintage to quadratically amplify the latency issues... but it actually feels (in Chrome 93) pretty much the same (no better, but no worse!) as the videos posted by OP.

I was incidentally [learning about `PointerEvent.pressure`](https://news.ycombinator.com/item?id=28942986) a couple weeks ago, and while headscratching through the pressure-to-line-thickness problem came across [a signature capture library](https://willowsystems.github.io/jSignature/#/about/) with [a memorably fast demo](http://willowsystems.github.io/jSignature/#/demo/). It apparently uses an approximating fast path to render realtime user input, and a higher-resolution renderer to generate the final bitmap or SVG.

The library kinda made a bit of an impression because it was as fast+responsive as the [minimal canvas drawing toy](https://nano-draw.glitch.me) I came up with which is doing exactly nothing in comparison :)

I'm guessing the library gets its speed due to being positively *ancient*; [the repo](https://github.com/willowsystems/jSignature) that the above page links to is a decade (!) old, and a [newer fork](https://github.com/brinley/jSignature) the original repo points to has IMO [much slower demos](http://www.unbolt.net/jSignature/). But it's MIT licensed, which may be nice.

I wonder if canvas size might be a contributing factor. While absolute display sizes are quite similar, Chrome presents my Note 4's 2560x1440 as 1024x576; I wonder what Safari does with the 2nd-gen iPad 2 Pro's 2732x2048?

FWIW as a point of comparison I actually find *perfect-freehand-example* unusably slow on the Note 4, while the signature demo (and the drawing thingy) is basically realtime. (In fact, split-screening Chrome and S Note, both seem to have about the same latency, and the only improvement is that S Note updates at 60fps. So *technically* the browser \*can\* be up there, it's just Fun™ to maintain thanks to JavaScript.)

...that gives me a thought. The whole time I was writing this I was musing about basically the only "real" solution to this whole problem domain being building "Excalidraw Native", ie platform-native apps. I wonder what would happen if you brought the entire rendering stack in-house and ported that to WebAssembly instead? Heh, chances are that's the "larger optimization" you speak of :)

**Comment by rsmyst** [comment]
hijacking to inform that issue exists on my windows laptop as well. works great for the first 10 words but continually proceeds into being very laggy after 20 words or so. past that, it's practically impossible to write anything or doodle anything. brush thickness didn't seem to affect it.

**Comment by dwelle** [comment]
This should be fixed since https://github.com/excalidraw/excalidraw/pull/4727 — lemme know if you're still experiencing the issues.

**Comment by rsmyst** [comment]
> This should be fixed since #4727 — lemme know if you're still experiencing the issues.

The overall experience seems much smoother now. It doesn't begin lagging until after i write down a decent amount of notes after which simply moving all the text off screen seems to fix the issue. Much more usable now on my laptop! kudos devs

**Comment by vijaybritto** [comment]
The experience has improved a bit in my samsung tablet but I can still feel significant lag after a few lines. The latency is around 600ms+ for a pen stroke.

**Comment by devinat1** [comment]
I am also getting significant lag after a few lines on my samsung tablet. My iPad seems to have significantly less lag, but that has the issue of freezing, so its a tradeoff between the two.

**Comment by Wictro** [comment]
Just to add, I'm using a MacBook Pro M1 and the Excalidraw lag increases the more notes I take (the number of objects increases). I tried it on Chrome and Safari with the same results. Every time it lags (>1s) I have to clear the canvas and start from scratch - in which case it starts working fine again.

**Comment by alelom** [comment]
Significant lag (>400ms) also on my Dell XPS tablet, to the point that Excalidraw is completely unusable, unlike any other note taking app.

**Comment by lpcluizhenrique** [comment]
> This touches on two things: 1) performance issues plaguing our renderer itself that we need to address as a whole, on a continual basis 2) the way the library we're using for the free draw tool works.
> 
> (2) the line is re-computed in its entirety every time _while_ you're drawing a given stroke. That said, your strokes are small enough (letters) that it should have almost no effect. On my iPad I see lags if the stroke is long enough to cover roughly 1/4 of the screen area.
> 
> (1) is more involved and there's no easy fix. One larger optimization is planned, but it again wouldn't have any effect in this case because it's apparently laggy from the first strokes.
> 
> Do you see any issues on https://perfect-freehand-example.vercel.app? If not, then it'd suggest it's a problem of our renderer.

I've tried it on my iPad Pro 10.5 inch (model A1701, year 2017), and indeed, the https://perfect-freehand-example.vercel.app has much less lag than the excalidraw.com website.

**Comment by Th3Lourde** [comment]
I'm using a huion draw pad + mac desktop. perfect-freehand is, perfect. Zero lag. Excalidraw lags inconsistently
