### ISSUE TITLE
Crash upon saving template or saving image

### ISSUE THREAD

**Issue by faizrekatama-tkpd** [excalidraw/excalidraw#4227]
Hi I am using `Chrome 95 on macOS (Catalina)`. 

Im trying to `export` my selected chart as image but it crashes my browser instead.
It happens too on `saving the template .excalidraw` file. Thank you. I love your product btw!

**Comment by dwelle** [comment]
Hi. We get reports like these from time to time (https://github.com/excalidraw/excalidraw/issues/4035) but it's hard to reproduce. Can you share the file, and if not, at least make a screenshot of the nerds for stats dialog?

(right-click on the canvas → show nerds for stats)

![](https://user-images.githubusercontent.com/5153846/139915895-29acf2b9-8708-4ffe-9b8d-dc72151ca382.png)

**Comment by faizrekatama-tkpd** [comment]
I am sorry cannot share you the original file, but here is the stat. 

![Screen Shot 2021-11-09 at 07 55 43](https://user-images.githubusercontent.com/80801652/140841950-631526a1-880d-41fb-bad6-d3b1e79d8647.png)

_this stat from my original file, there is a lot of drawing_

and this happen to small and simple draw as well. (https://excalidraw.com/#json=3pWi3RKS2QBpa7bxDuQ4_,D5Bz72eI7mOt3cDfux0U4A)

**Comment by polnetwork** [comment]
Same happening to me, hope this helps :-) 
<img width="163" alt="Captura de pantalla 2021-11-09 a les 11 37 07" src="https://user-images.githubusercontent.com/639877/140909060-0087bd0b-3170-4320-bc9e-9c91e1ef01fd.png">
.

**Comment by dwelle** [comment]
@faizrekatama-tkpd  Cannot repro. That large(r) scene could have conceivable issues around PNG exporting, though unclear why exporting to JSON (`.excalidraw`) would be a problem.

@polnetwork what's your OS, version and browser?

**Comment by polnetwork** [comment]
MacOs Monterey, with Chrome 95.0.4638.69
Works fine with other browsers (tested Safari, Firefox and Edge)
I'm trying to move manually my work in progress copying browser local storage without luck.
Is there a way to do that?
Many thanks :-)

**Comment by dwelle** [comment]
One other thing: do your canvases contain any images?

Though, at least the excalidraw.com/#json=3pWi3RKS2QBpa7bxDuQ4_,D5Bz72eI7mOt3cDfux0U4A does not.

@faizrekatama-tkpd could you test that drawing on these deployments?

1. https://excalidraw-q9t4cpreo-excalidraw.vercel.app
2. https://excalidraw-cigqdgbvg-excalidraw.vercel.app

The only problem is we've recently migrated to a different shareable link id scheme so that `#json` link won't work on those older deployments. The only way to load that link is download it as a file and import it manually: [crash.txt](https://github.com/excalidraw/excalidraw/files/7507178/crash.txt) ← this file is the #json=3pWi3RKS2QBpa7bxDuQ4_,D5Bz72eI7mOt3cDfux0U4A link (you can drag & drop the `txt` file, or rename to `.excalidraw` and import it via the open-file button).

@polnetwork does the excalidraw.com/#json=3pWi3RKS2QBpa7bxDuQ4_,D5Bz72eI7mOt3cDfux0U4A  crash for you as well? If so, can you check on the above 2 deployments as well?

Thanks!

**Comment by dwelle** [comment]
> I'm trying to move manually my work in progress copying browser local storage without luck.

@polnetwork just select all elements (`Cmd-A`), copy them (`Cmd-C`), and paste into the other browser(s) via `Cmd-V`.

**Comment by polnetwork** [comment]
Yes, I can confirm that excalidraw.com/#json=3pWi3RKS2QBpa7bxDuQ4_,D5Bz72eI7mOt3cDfux0U4A crashes my browser

**Comment by dwelle** [comment]
Lastly, I'd be interested if you can reproduce on Chrome 96 (beta): https://www.google.com/chrome/beta. But I understand that this can be too much work :p

**Comment by polnetwork** [comment]
Tested excalidraw.com/#json=3pWi3RKS2QBpa7bxDuQ4_,D5Bz72eI7mOt3cDfux0U4A with Chrome Beta 96.0.4664.35 for Mac/Intel and can confirm that it does not crash :-)

**Comment by dwelle** [comment]
@polnetwork nice!

![image](https://user-images.githubusercontent.com/5153846/141199877-c0c82d97-049f-4673-944a-dd79feccbd15.png)

**Comment by polnetwork** [comment]
Solved on latest Chrome release 96.0.4664.45 :-)

**Comment by dwelle** [comment]
Good, good.

Closing. @faizrekatama-tkpd let us know if you can still repro and we'll reopen.
