### ISSUE TITLE
CI tasks hanging

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#424]
https://github.com/excalidraw/excalidraw/commits/master

**Comment by lipis** [comment]
We should somehow ignore the commit hooks on deployments... is that even possible?

**Comment by dwelle** [comment]
Better to fix to issues.

**Comment by lipis** [comment]
It's autogenerated code.. we should ignore those!

**Comment by dwelle** [comment]
For sure. I thought you meant we should disable linting on CI.

Dunno why it started to lint build files. Looks like it started failing around when you made changes to CI configs: https://github.com/excalidraw/excalidraw/commit/86eadf379de329f4fb6be5e076aea242085d19f3

**Comment by dwelle** [comment]
Reopening since this is still not fixed.

I've noticed a pattern: the [`Node CI` tasks](https://github.com/excalidraw/excalidraw/tree/master/.github/workflows) fail exclusively when the PR is issued from a fork (not from a branch in the main repo).

(there are also some old PRs which have netlify/ZEIT failing/not-running for some reason.)

**Comment by dwelle** [comment]
It seems https://github.com/excalidraw/excalidraw/pull/511 fixes it (though it may have unintended consequences that will appear in time). If there are any issues, we can reopen this.
