### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by lucasnobre212** [excalidraw/excalidraw#4355]
I just cloned the repo and built the docker version following the instructions and readme to host a private session and got this error in console. The page is stuck in "loading scene"
```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Module.<anonymous> (main.a1e39ee0.chunk.js:1)
    at a ((index):1)
    at o ((index):1)
    at Array.e [as push] ((index):1)
    at main.a1e39ee0.chunk.js:1
```

**Comment by catherinetcai** [comment]
I've had the same issue. I ran a `git bisect` and it looks like `96b31ecbce8a34b51fe5ea4a7de1697ef55a9b12` is the first commit that the docker builds stop working for me.

**Comment by dwelle** [comment]
In that commit I changed `.env` → `.env.development`. It may be needed to add that file to [`.dockerignore`](https://github.com/excalidraw/excalidraw/blob/master/.dockerignore), but not sure if it will be enough.

Anyway, this error seems caused by the fact that no env files are now apparently used during docker build. This PR should fix at least the above error (I hope): https://github.com/excalidraw/excalidraw/pull/4381
