### ISSUE TITLE
Architect hachure doesn't fill whole ellipse

### ISSUE THREAD

**Issue by YouriTjang** [excalidraw/excalidraw#4378]
When I draw an ellipse with architect sloppiness, and a hachure or cross-hatch, 
Then the right top is not filled.
![image](https://user-images.githubusercontent.com/1197663/145003552-3954bbcf-7a29-40d5-a277-24fac9a200f4.png)

https://excalidraw.com/#room=9df1770a4c734898167d,tTWgcbR4cc29YWZT1ErHMg

**Comment by anudeepreddy** [comment]
The issue lies with the roughjs library, I have opened a ticket https://github.com/rough-stuff/rough/issues/199.

The author of the library has fixed the issue with this PR https://github.com/rough-stuff/rough/pull/200 . Version bump is still pending at the time of writing this comment and the progress can be tracked here: https://github.com/excalidraw/excalidraw/pull/4386
