### ISSUE TITLE
Button label with a weird behavior

### ISSUE THREAD

**Issue by dudunato** [excalidraw/excalidraw#4491]
Hey guys, have a look at this weird behavior: https://yac.com/play/a4VSXvBFk

I'm sure this wasn't like this before. It's quite unproductive having to create new buttons all the time you try to label them.

**Comment by ad1992** [comment]
Not sure what you are referring to, but now in any shape/image if you press enter / click on center of shape text is binded to that shape else its not binded.

**Comment by dudunato** [comment]
Did you watch the video?

-
Dudu

**Comment by dwelle** [comment]
Are you referring to the padding which in your case is undesirable?

**Comment by dudunato** [comment]
Yes. It wasn't like this. And it doesn't allow to resize which is quite frustrating.

-
Dudu

**Comment by dwelle** [comment]
Yes, as @ad1992 noted, this is because we've made text inserted via `dblclick-on-center` or `enter` to be bound to the container, which also maintains a fixed padding.

For a start, we'll make the padding adaptive to the container size https://github.com/excalidraw/excalidraw/issues/4498. If that's not enough, we may consider allowing to disable the padding altogether. We'll see.

**Comment by inwardmovement** [comment]
Same weird behavior here:
![exc-enter](https://user-images.githubusercontent.com/9438102/147923037-b0aa176c-84bd-4a3c-a069-ed6b06e7fff6.gif)

If I want a "big number in a small circle" I cannot use the "bind to text/enter" function, I have to create the text, then the shape, and align/resize them manually.

**Comment by inwardmovement** [comment]
Yes, still a bit too big, but definitly better.

**Comment by dwelle** [comment]
The 5px change was shipped today. I'm gonna close this in favor of https://github.com/excalidraw/excalidraw/issues/4498
