### ISSUE TITLE
[Bug] When I double click on a text field, the text disappears and I can't edit it anymore

### ISSUE THREAD

**Issue by bricebottegal** [excalidraw/excalidraw#4579]
Hello,

Please see [video](https://www.loom.com/share/275b7c24eb8f4b68bf7919c10345dbc9).

I don't understand why :(

Thanks for the help.

Brice

**Comment by dwelle** [comment]
Hey! This looks strange indeed. From the recording, it seems you're using Windows. Is that a desktop (mouse) or touch (table, styles, trackpad)? What happens if you exit the text editor and resize the container (rectangle) that the text is bound to. Does the text re-appear?

Also, if you could save the file _after_ the text disappears and upload it here (you can rename the `.excalidraw` to `.txt` and you should be able to drop the file into a GitHub comment directly)? If the drawing is private, and you can reproduce on an new drawing, that'll be enough (don't forget to save the current file contents to a file so you don't lose work!).

**Comment by bricebottegal** [comment]
- it seems you're using Windows : yes (I tried 2 browsers result is the same)
- Is that a desktop (mouse) or touch (tablet, styles, trackpad) input ? Desktop mouse
- What happens if you exit the text editor and resize the container ... Does the text re-appear? No

Here is the file:
[for-investigation.txt](https://github.com/excalidraw/excalidraw/files/7856469/for-investigation.txt)

**Comment by yuriybelike** [comment]
+1. This is also happening in my drawing.

I'm also on Windows (10). I've tried and could reproduce on:
- Chrome 96
- Chrome 96 incognito
- Firefox 94
- Using laptop trackpad instead of wireless mouse

Some notes:
- Like Brice, some text fields can be correctly edited without getting their text removed
    - **Looks like it's the "newest" the ones that work fine** -- Very rough estimate: newer than 30th December
- In case it matters: in my case it's a shared room that has been created months ago on my computer.
- A coworker on Linux couldn't reproduce my behaviour

**Comment by zsviczian** [comment]
I experienced this issue after the sticky-notes feature was implemented when I added elements to a scene using updateScene and the elements had the legacy `boundElementIds`. When elements are added to an existing view via update elements the conversion from `boundElementIds` to `boundElements` does not happen. Could that be the issue here as well?

**Comment by dwelle** [comment]
Oops, this is our mistake. We've had a bad migration in place which only expressed yesterday (https://github.com/excalidraw/excalidraw/pull/4543). Fix incoming: https://github.com/excalidraw/excalidraw/pull/4580
