### ISSUE TITLE
Proposal to ditch the current dark mode and opt for a better one

### ISSUE THREAD

**Issue by KL13NT** [excalidraw/excalidraw#4616]
Hi. I have been using Excalidraw almost exclusively whenever I need to draw, explain, or just mess around with shapes. I absolutely love it, and the fact that it's open source. But throughout the period during which I used it I quickly started noticing a lot of issues with the current "Dark Mode". Basically #2346, #3531, #3606, #4074, and #4301. I'd like to list these issues and the possible fixes for them in this proposal. 

## Here are my reasons:
1. It's *super* laggy on Firefox. Canvas filters are not the best in Firefox and they certainly lack the performance of, say, Chrome. Drawing a straight line using the Pen tool in Firefox with Dark Mode on runs at an average of 27 FPS, while drawing complicated circles and random shapes runs at an average of 56 FPS. (#4074 #2346)
2. Colours don't look that great. I draw a red line, I expect it to be red in Dark Mode, but it turns out something entirely different. Even custom hex codes don't work properly. (#3531)
3. Not to mention the various bugs with Safari not supporting svg invert and so on. 

I dug deeper and found out about the tiny `invert` and `hue-rotate` thingy, but that just doesn't work, given the previously mentioned issues. 

## My proposal
1. First off, rename the current Dark Mode to Invert Mode, with clear warnings of what might the output and bugs be. 
2. Then, create a new Dark Mode that only changes the colour of the controls and UI without touching the rendering canvas itself. Maybe change the background colour as well, just for the sake of consistency and user expectations. This would be a true dark mode experience that is completely lag free (I tested it!), respects browser limitations (also tested it!), and doesn't suffer any of the aforementioned issues. 

I currently have Excalidraw with a custom background of the value `#121212` (dark grey) that is consistent with [Material Design's dark theme](https://material.io/design/color/dark-theme.html#properties) (which most users are familiar with), and it's quite comfortable. I didn't face any of the issues mentioned above or other issues regarding dark mode. 

> I'm willing to work on this, just point me in the right direction.

**Comment by dwelle** [comment]
Hey!

I'm open to improving the current dark mode scheme 👍, with the following caveats:

1. We still want to keep dark background. Not only is this pretty much the point since canvas takes up 90% of your screen (or more), but the dark mode output is also often what users go for in terms of aesthetics.
2. We do need to rotate some colors, namely black/gray colors (or more generally, very dark colors) — question is what would the heuristic look like.
3. I assume there are many users who either 1) prefer current dark mode, or 2) have in-progress projects (especially long-term ones like books) where making drastic dark mode scheme changes would affect them negatively. Not sure how to handle this. I don't want to keep two dark mode schemes around (one thing is keeping the logic, another is having multiple different dark modes in the UI).

(3) also addresses your first point:

> First off, rename the current Dark Mode to Invert Mode, with clear warnings of what might the output and bugs be.

If we change the dark mode, let's that in one go and not keep multiple ones. Unless you meant this as an interim solution until the rewrite is done, but I don't think current dark mode is anywhere near unusable to warrant this (well, except some of the bugs).

> I currently have Excalidraw with a custom background of the value #121212 (dark grey) that is consistent with Material Design's dark theme

That's the color we're using — I believe we're following the same design document (or generally Google's).

**Comment by Mobuos** [comment]
Sorry if this is just flying over the actual issue here, but shouldn't dark mode have like... a different palette of colors? Something that looks better than whatever change excalidraw makes to the colors maybe...?

I understand the idea of translating colors into things that stay readable in dark mode without having to change the actual color code, but that makes for a weird user experience when trying to use specific colors, and I don't think this technique of rotating and inverting colors works every time.

If the changing of colors needs to be kept, and I imagine changing the palette would clash with the question you brought up with your third point, could that happen in an actual color code level? So instead of an object with a color code of #364fc7 staying with the same color code but with y'know a different color in practice:
![image](https://user-images.githubusercontent.com/12601762/150244604-2e2fb0ce-cd6d-44d5-bacd-ff6f4ad669b1.png)

The actual color-code could change to it's equivalent after the change:

![image](https://user-images.githubusercontent.com/12601762/150245201-fed6d115-7c2b-48d4-9d04-1b71087112b9.png)

I'm kind of only thinking here about the color issue because that's my main problem with dark mode, I don't notice any performance drops on my machine. Currently, the feature of selecting the color code you want in excalidraw is... useless in dark mode.

**Comment by KL13NT** [comment]
> * We still want to keep dark background. Not only is this pretty much the point since canvas takes up 90% of your screen (or more), but the dark mode output is also often what users go for in terms of aesthetics.
> 
> * We do need to rotate some colors, namely black/gray colors (or more generally, very dark colors) — question is what would the heuristic look like.

There are two main use cases in mind with this, the use case in which users wish to *invert* an already-consumed canvas, meaning they have ongoing projects and wish to switch them from light to dark mode instantly without tinkering with colors, and users who wish to start *new* projects with proper dark mode. 

This is the main reason I suggested keeping two modes, as completely changing the current behavior will certainly break ongoing projects. Asking users of ongoing projects to ditch them or manually transform the colours would be too much, especially in large projects. And ignoring users who wish to use a proper dark mode wouldn't be right. 

With `invert mode` you can apply the invert and call it a day for users who wish to invert the whole thing, which achieves your first two points. With `dark mode` you can modify the background of the canvas to a dark colour, change the colour palette, and be done with it. This achieves your first point and removes the need for the second one.

As for @Mobuos's question, provided I understand your question correctly: I'm pretty sure you can transform the hexa to RGB and rotate `(255 - value)` the RGB variables to fit the new mode, but there are bigger problems with the approach. This will pretty much be slow in JS for ongoing projects, and would still produce the same output for new projects, inverted colours.

**Comment by Mobuos** [comment]
I was thinking the inversion and rotation would happen only when pressing the button to switch to dark/light mode, after that excalidraw would be simply using different colors. I really should have placed my suggestion in #3531 instead because that's all that it fixes: Typed hex codes in dark mode would show correctly without affecting anything.

I don't see how it would be slower though? Excalidraw already does the rotation in dark mode right?

**Comment by KL13NT** [comment]
It does the rotation using CSS, which is a GPU-accelerated native operation. Doing it with JS would be a ton slower, AFAICT.

**Comment by MattKleinsmith** [comment]
Hi, just chiming in here. What I'd like from a Exalidraw dark mode:

1. Dark UI
2. Dark canvas

And on the negative side:

1. Please don't change my images. That's my responsibility. Currently, I avoid using images in Excalidraw, because it inverts them.
2. Please don't make the hex values wrong. "000000" should mean black, not white.

My plan for now is to use light mode (i.e. accurate mode), and then use a user script to achieve a dark UI and dark canvas.

All that being said, I love Excalidraw. Thank you for making it.

**Comment by MattKleinsmith** [comment]
@dwelle 

> I assume there are many users who either 1) prefer current dark mode, or 2) have in-progress projects (especially long-term ones like books) where making drastic dark mode scheme changes would affect them negatively. Not sure how to handle this. I don't want to keep two dark mode schemes around (one thing is keeping the logic, another is having multiple different dark modes in the UI).

The dilemma is real. Excalidraw must sacrifice something. Currently, Excalidraw is sacrificing the accurate-dark-mode use case. The other options of sacrifice are:

1. The inversion use case
2. Simplicity of code

I recommend sacrificing simplicity of code, instead of sacrificing an important use case. In other words, I recommend sacrificing the developer's wants (_"I don't want to keep two dark mode schemes around"_), instead of the user's. Isn't that the proper hierarchy?

As for the UI, you could bury the accurate-dark-mode toggle here:

![image](https://user-images.githubusercontent.com/8968171/190869217-a4a00da2-bfce-4206-bdb6-c875a03bf566.png)

**Comment by dwelle** [comment]
Hi!

> Please don't change my images. That's my responsibility. Currently, I avoid using images in Excalidraw, because it inverts them.

Not something we do by choice, but due to how our dark mode work right now.

I assume you're using Safari? On other browsers that support canvas filters we selectively invert the images back (the double invert isn't 100% accurate, but for now it seems serviceable).

> Please don't make the hex values wrong. "000000" should mean black, not white.

Isn't that the point of canvas-application dark mode? If we didn't, and only inverted the canvas background, then all your black/dark shapes would effectively become invisible.

Or are you suggesting that we don't touch the canvas and only invert the UI? Problem with this is that canvas covers 90% of the screen, and our goal here is for the UI to become easy on your eyes at night.

The secondary consideration is that some people want to create dark-themed drawings for whatever reasons (e.g. they publish on a dark-themed website) with minimum effort. Especially if they want to publish in both themes at the same time. If they had to manually toggle the colors to match the dark theme, that would go counter that goal.

**Comment by MattKleinsmith** [comment]
Hi David,

Thanks for your reply!

> Isn't that the point of canvas-application dark mode? If we didn't, and only inverted the canvas background, then all your black/dark shapes would effectively become invisible.

No, I use light-colored shapes on dark backgrounds. I don't need Excalidraw to modify my colors (please don't). I just need the canvas background to be dark, same with the UI. Currently, unfortunately, I can't achieve a dark canvas background and dark UI in Excalidraw without having incorrect hex colors and inverted image colors.

> Or are you suggesting that we don't touch the canvas and only invert the UI?

No, and just to clarify, I'm only asking for:

1. Dark UI
2. Dark canvas (via setting its color to a dark one, not via inversion of a white canvas)
3. A hand-chosen default color palette that goes well with the dark canvas

And regarding the collision with inversion mode:

The accurate-dark-mode setting could be buried in the workplace settings, so that the inversion workflow would not be affected.

**Comment by Mobuos** [comment]
Maybe the change between dark/light mode should only map colors to the new palette. You could even map the colors used for shapes using the inversion currently used... That would solve the accuracy of hex codes while avoiding messing up any use-cases right?

For example, red is #FA5252, when switching to dark mode all that is needed to do is map that color to #F86769... Ideally the palette of colors available without using hex codes would have a custom mapping (a custom paletter for dark mode), but the inversion route could be the default for everything else.

**Comment by MattKleinsmith** [comment]
> You could even map the colors used for shapes using the inversion currently used...

This is a great idea. It solves part 3: "A hand-chosen default color palette that goes well with the dark canvas".

> That would solve the accuracy of hex codes while avoiding messing up any use-cases right?

Unfortunately, there are two conflicting use cases:

---

### **Toggling** between light and dark at a moment's notice, even in the middle of project:

The best solution for this that I know of is **global inversion**, at the expense of color-code accuracy.

---

### Choosing light or dark at the beginning, for the sake of **color-code accuracy**:

The best solution for this that I know of is mapping the default color options _in the menu_ to an appropriate one, and mapping the canvas background to the appropriate one. This means **leaving the colors of the shapes on the canvas alone**.

![image](https://user-images.githubusercontent.com/8968171/190877373-8234971c-aa1f-4707-825c-c4fc043b7921.png)

**Comment by michelmar** [comment]
Regarding this discussion, I would like to explicitly choose whether I want this to be inverted or not for each element. I'm trying to use some complex SVGs that were made in illustrator, but they just don't work inverted. I think a simple flag to differentiate the inverted to a not inverted conversion would help a lot

**Comment by dwelle** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/3531

Please see the latest comment summing up all the proposal, though I'm sure I've missed some: https://github.com/excalidraw/excalidraw/issues/3531#issuecomment-1406777374


> Regarding this discussion, I would like to explicitly choose whether I want this to be inverted or not for each element. I'm trying to use some complex SVGs that were made in illustrator, but they just don't work inverted. I think a simple flag to differentiate the inverted to a not inverted conversion would help a lot

@michelmar we should definitely do that for SVGs 👍

**Comment by jiajiala** [comment]
Hope Dark mode doesn't handle pasted pictures, emojis. The inaccuracy of the color of the content is most troubling

**Comment by ucimo** [comment]
This is the way, not sure why it's abandoned. Can anyone recommend another web app like excalidraw that supports this?
