### ISSUE TITLE
Change hand-drawn font for non-latin support

### ISSUE THREAD

**Issue by cloudever** [excalidraw/excalidraw#469]
I suggest change the hand-drawn font to another one for supporting not only latin languages.
Russian words do not look aesthetically pleasing (Cyrillic)

![image](https://user-images.githubusercontent.com/16993305/72725820-d3ef5780-3b97-11ea-8737-ca4dc6c6493c.png)

**Comment by dwelle** [comment]
What's the suggestion here? That we should detect if user types non-latin characters and auto switch to regular font?

For now, you can change the font manually. We also should (in the near future) remember the font you selected so that you don't need to update it for new texts.

![excalidraw_russian](https://user-images.githubusercontent.com/5153846/72733819-ec13a680-3b98-11ea-907e-1ec855a0bb96.gif)

**Comment by cloudever** [comment]
I mean that it would be great to support cyrillic letters in hand-drawn text

**Comment by lipis** [comment]
it's hard to find such font that supports Cyrillic, Greek, etc..

**Comment by cloudever** [comment]
maybe https://fonts.google.com/specimen/Neucha?

**Comment by lipis** [comment]
No Greek support.

**Comment by vjeux** [comment]
Looks like the font FG Virgil was done by Ellinor Rapp ( https://www.myfonts.com/foundry/Font_Garden/ ) in 2002 along with a bunch of other fonts with hand-written style. Let me reach out to her to see if she's still in the font creation business and see if she'd be interested in completing the rest of the character set.

**Comment by vjeux** [comment]
Ellinor went back to me and added the greek and cyrillic characters!!

- (Virgil2YOFF.ttf)[https://easyupload.io/vv4aas]
- (Virgil2YOFF.otf)[https://easyupload.io/grf66q]

If someone could verify that they indeed work and bring them to the codebase that would be awesome!

**Comment by dwelle** [comment]
Note that it does not support some/most/all [latin-extended](https://en.wikipedia.org/wiki/Latin_Extended-A) characters, used by e.g. Czech. (I personally don't care.)

![image](https://user-images.githubusercontent.com/5153846/73888920-d7a8fc80-486e-11ea-82c3-f4343922c79e.png)

(This really doesn't matter since the latest font iteration just improves on whatever charset we're already supporting, so there's no reason to not go ahead, apart from size increase.)

(Also note that we'll need to modify the font again to improve the [exclamation point](https://github.com/excalidraw/excalidraw/pull/394) /cc @jsjoeio.)

**Comment by jsjoeio** [comment]
> (Also note that we'll need to modify the font again to improve the exclamation point)

Argh, bummer 😅

Once this gets updated and merged in, can someone tag me? I'll create a follow-up issue and update the exclamation point then.

**Comment by dwelle** [comment]
@jsjoeio Yep. Btw, when you optimized the size in the 2nd PR (https://github.com/excalidraw/excalidraw/pull/400), it broke the font, so I needed to revert that back then. Thus when you modify the font again, be sure to *not* optimize the size :D (or debug it if it works).
