### ISSUE TITLE
Don't explode if initialization fails

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#471]
When `localStorage` contains invalid data for whatever reasons (can result due to bugs, or breaking change update), and it throws during initialization, the app should survive it. Simplest solution in that scenario is to clear `localStorage` and use default values.

Currently, if this happens, there's no recourse other than opening devTools and running `localStorage.clear()` + refresh.

**Comment by gmertk** [comment]
Just had the same issue of #488 Had to clear the localStorage.

Just out of curiosity: Does this mean that the website is broken at the moment for anyone who had a localStorage from the previous versions?

**Comment by vjeux** [comment]
This is bad, we should do our absolute best to be backwards compatible. Can someone check what commit introduced this issue and revert it by any chance?

**Comment by lipis** [comment]
Probably the css units, but I think it's OK, while we are in beta.. we should recover and not crash whatever happens. In the coming weeks while we still sharpening the edges, we don't want to bloat with multiple versions from now on and support every little mistake we did. For example #489

**Comment by vjeux** [comment]
This issue has nothing to do with the CSS unit changes. The problem here is that some version of excalidraw stored something within localStorage that a different version in the future cannot read in such a way that the UI no longer show up at all.

This is not ok. The reason people use excalidraw is because “it just works”. Backwards compatibility is extremely important for those kind of projects to be successful. We want people to trust that they can return to the website and continue working on their drawing from the day before.

**Comment by lipis** [comment]
Sure in a long run that's what we want.. My point is that the project is a few days old! But OK.. let's be consistent from day one.

**Comment by dwelle** [comment]
I think the first course of action is ensure the app doesn't blow up.

Backwards compatibility is a different issue. In private project I've rolled out a solution that implements migrations for specific localStorage (sub)keys. Is that something we wanna do here?

**Comment by vjeux** [comment]
So far I don’t think we have renamed or removed anything from the appState or elements, only added things. This is why it worked so far. I’m not sure what changed since yesterday.

(It’s not 100% true, we did change the text ascentPosition or something but I made sure that it was backwards compatible)

The answer is yes, we should be thinking about migrations whenever we do change the schema in a non backwards compatible ways.

**Comment by dwelle** [comment]
For now, I say we implement a hotfix that clears the localStorage. After that, we can think of how to implement migrations.

**Comment by lipis** [comment]
Only if it fails to load it.

**Comment by vjeux** [comment]
We also store the raw data (eg fontSize) rather than the way we display (eg Big) so that we can tweak the UI without breaking the underlying data model.

I haven’t done a good job documenting all those architecture decisions but they’ve been on my mind since the project started

**Comment by lipis** [comment]
Yes, also would like to see the documentation of the schema and everything.. it's never too late to start.

As for the font size instead of Big and Font name instead of the human readable thing, I think eventually we should change that and store the labels instead of values. That way we can tweak the sizes, fonts, patterns and render everything correctly with backwards compatibility.
