### ISSUE TITLE
Feature request - straight and parallel lines

### ISSUE THREAD

**Issue by DanielShterenberg** [excalidraw/excalidraw#4790]
Is it possible to add a feature that will enable me to draw straight lines? maybe by clicking on 'shift' as its expected in other products?
Also, is it possible to make straight lines that are parallel to the x and y-axis?

**Comment by dwelle** [comment]
Are you talking about the freedraw tool? With line and arrow tools, holding shit already works:

![image](https://user-images.githubusercontent.com/5153846/154072912-e4f49a72-00d3-4354-a9ac-ca4cd66479e7.png)

**Comment by DanielShterenberg** [comment]
So I might have a bug because it doesn't work for me.
Now I'm actually recalling it used to work once.

**Comment by dwelle** [comment]
What's your browser & OS?

**Comment by prajwal0024** [comment]
It works for me, I have same MacOs 10.15.7 (but 19H15) and Chrome 98.0.4758.102

https://user-images.githubusercontent.com/43070174/154855502-49fe0793-692a-472d-b3c5-78389ff179c4.mp4

**Comment by prajwal0024** [comment]
It works for me, I have same 
MacOs version 10.15.7 (but 19H15) and 
Chrome Version 98.0.4758.102 (Official Build) (x86_64)

https://user-images.githubusercontent.com/43070174/155164837-1606bca3-8b47-465d-870e-16a068328de7.mp4

**Comment by DanielShterenberg** [comment]
Hi everyone. I just tried it again after restarting my Mac over the weekend and the issue seems to be resolved. I really don't understand what is going on and how does it work now after not working for two weeks.
Anyway, thank you all!
I'll close the issue.

**Comment by aderchox** [comment]
I've been using Excalidraw for a long time, and I always hold the shift key to draw straight lines, but suddenly it stopped working for me. I thought you've removed this for some reason in an update, but reading this thread I've realized this is not an update, the issue is on my own side. Using a different browser it works fine. I must find out what's wrong with my Chrome (it is updated).
**Update:** On my other browser it works all the time, but in my Chrome, sometimes it works, and sometimes it doesn't. I don't know maybe some extension is stealing my shift key.
I'm leaving this comment here for future readers who might encounter this as well.
