### ISSUE TITLE
[Feature request/Bug report?]: A setting to enable pen mode by default on iPad.

### ISSUE THREAD

**Issue by huntedman** [excalidraw/excalidraw#4936]
Currently, when I open a fresh instance of excalidraw, I first have to tap the screen with a pen in order to even see the button to "enable pen mode".

Normally it's not a problem, but when you open an existing document where the last used tool was a pen, my intuition is to start drawing with the pen immediately BUT my hand that rests on the screen immediately registers as a pen stroke.

A setting that would enable pen mode by default on ipad would make it perfect. 

I'm using excalidraw in conjunction with obsidian, so a startup flag perhaps would make sense?

So far I'm LOVING it, thank you for all the great work. I have nothing but praise for you ❤️

**Comment by zsviczian** [comment]
I wouldn't recommend detecting device type and auto enabling based on that for the simple reason that there are many other devices beyond iPads, and also detecting iPads is not that trivial as one would hope so... the ways to detect continually change with new versions of iPads being released, so such a code would require constant attention.

I am planing to spend some time with pen mode this weekend. My idea is to detect the pen already when you use click the toolbar with the pen. Perhaps that would improve the experience for you.

My own current routine is to touch the screen with the pen when the "Selection tool" is still active and then click the freedraw icon. This avoids the unintended line I sometimes create by placing my palm on the screen.

**Comment by zsviczian** [comment]
I am working on this PR (#4943) to resolve this issue.

**Comment by dwelle** [comment]
@zsviczian ad your PR, I'm not against detecting on tool change, but maybe we should do that _on top_ of current canvas detection? But, neither solution will solve the issue @huntedman is facing. The only solution that comes to mind is preserving `penMode` across sessions.

**Comment by huntedman** [comment]
@zsviczian #4943 is a really clever workaround! It does solve the issue of having to do 3 clicks in order to start drawing!

But this part makes me wonder:
> Without penDetected the pen-lock button will not be displayed
> Saving penDetected and penMode would mean that we shouldn't move penDetected to DeviceType context after all...

This behaviour seems more what I had in mind. When you open a drawing that was previously in penMode, it's automatically in penMode and the unlock button is also displayed.

On a slightly unrelated note, I noticed you released obsidian-excalidraw-plugin 1.6.20 Congrats 🥳 !
I'm a big fan of your work, and yesterdays update made me wonder, is there a way to set penMode and penDetected on by default in excalidraw? Perhaps by front-matter?

Forgive me, for I don't know how you instantiate excalidraw and what flags are available, but my intended behaviour with the pen would be similar to "zen mode on by default" setting. 

(Also let me know if this is discussion is off topic from the core excalidraw.)

**Comment by zsviczian** [comment]
> My IDEAL solution with the pen would be similar to "zen mode on by default" setting in obsidian-excalidraw-plugin.

This has crossed my mind as well.
But maybe the solution is to save penMode and penDetected with state. That would also be required to enable penMode by default similar to zenMode.

The point is, that DeviceType already holds information if the device is a mobile device, and if it has a touch screen. pen would logically fit this. But penMode is more like zen mode, view mode... which are app states.

I'll do another PR that will keep penDetected in appState, but will save it, it only takes few minutes, since there are not many changes required. Then We can try both and see which feels more natural.

**Comment by zsviczian** [comment]
@dwelle #4955 feels more user friendly. The only drawback is penDetected remains in appState. However it also makes sense that it is in penState, since you can expect that next time the user uses the device she/he will still have a pen.

@huntedman, I think #4955 does exactly what you were looking for. I can use this to add an option to Obsidian-Excalidraw to enable penMode by default in the plugin...

**Comment by zsviczian** [comment]
Closed via #4955
