### ISSUE TITLE
bind c to ellipse

### ISSUE THREAD

**Issue by lukesmurray** [excalidraw/excalidraw#5015]
Is there any reason *not* to bind the `c` key to the ellipse tool? With the addition of the eraser, ellipses can no longer be created using the mnemonic `e` key. It's very nice that excalidraw uses mnemonic keyboard shortcuts all on the left side of a qwerty keyboard. The use of `o` for oval is fine but `o` is on the right side of the keyboard. Why not let users use `c` for circle since it's mnemonic, easy to remember, and on the left side of a qwerty keyboard. 

I understand the ellipse tool does not draw circles by default but does it really matter? we're not teaching users the difference between circles and ovals we're providing mnemonic left-handed keyboard shortcuts so that users can switch tools without taking their hands off of the mouse.

**Comment by dwelle** [comment]
We're actually trying to adhere to standards of tools like Figma, Miro and other similar tools if a there's a set precedent, which for many of our tools there are. Just trying to be a good citizen so that users don't have to relearn shortcuts for every app.

For other things like colors we could come up with our own.

`c` is reserved for the comments tool.

**Comment by dwelle** [comment]
But, we will be adding support for customizing shortcuts at some point for people who disagree :).

**Comment by lukesmurray** [comment]
got it thanks, that's a reasonable enough reason not to do this!
