### ISSUE TITLE
Allow users to create a new canvas

### ISSUE THREAD

**Issue by axwellm** [excalidraw/excalidraw#5096]
When I open Excalidraw, I'm shown the last canvas I worked in. I want to create a new, blank canvas but I can't see any option to do this. Therefore, I resort to opening Excalidraw in an incognito browser, which gives me a blank canvas. When I'm done, I can save it (eg, to disk or by creating a shareable list). However, this is inconvenient. By the way, I'm not an Excalidraw+ user.

**Comment by dwelle** [comment]
You can clear the canvas using the trash button:

![image](https://user-images.githubusercontent.com/5153846/165157272-595c875c-4215-4418-9180-fb842f4348a9.png)

**Comment by ad1992** [comment]
Hi @svenn71 👋🏻, this was an [intentional change](https://github.com/excalidraw/excalidraw/pull/4545) so that all tabs sync the data, and users never end up losing drawings due to getting overridden by the latest one. 
Earlier if there were multiple tabs, each with a separate drawing, and if you close a tab and reopen it again (or open a new tab), it will contain the last state from the other tab and no way to recover the lost drawing.

**Comment by ad1992** [comment]
closing this as its resolved, feel free to reopen if you encounter any issue related to this

**Comment by svenn71** [comment]
Since you merged the PR back in January, I cannot have several independent excalidraw tabs open at the same time. The issue of "lost" drawings was something I discovered early and easily managed to work around by not doing it that way. For me the current implementation is even worse:

* I open a tab with excalidraw and drag-drop a file from file explorer to tab to edit
* I do some editing and discover that I need to look at another excalidraw drawing to copy some content
* I must now save my current drawing and open the other, I cannot have both on screen at the same time

Can you rationalize that the intentional change was so important to excalidraw that a change was introduced which hampered the ability to have several drawings open at the same time?

Do you see a solution to modify excalidraw in such a way that each tab actually could have a separate drawing?

**Comment by Zirafnik** [comment]
Being forced to use just one Canvas at a time, then saving, the deleting the current one, and then creating/loading a new one is just bad UX. 

Let me create multiple independent canvases, even if we introduce an internal tab system inside the app, for switching between canvases. This way the browser tabs can still be synced, but Excalidraw can have multiple tabs/canvases available.

I believe this also relates to this issue (which is one of the most basic expected functionality, by users, in such tools): https://github.com/excalidraw/excalidraw/issues/1957

**Comment by marcospgp** [comment]
Sharing a workaround - opening multiple instances of the browser should allow opening different excalidraw documents at the same time

Easiest setup is one regular tab + one incognito tab, but more can be added by for example opening different profiles in chrome.

**Comment by Ghostbird** [comment]
I don't think the issue is solved from a UX perspective. I'll never click the _Reset canvas_ button, because I fundamentally don't want to reset the current canvas. I need separate canvases for things I discuss with software engineers, and for things I discuss with customers.

**Comment by Karsenh** [comment]
Such a great tool with such a fundamental UX flaw it would seem. Shame.

**Comment by xandaaah** [comment]
Why not just add a Vim-style swapfile system? All changes in the current project are saved to localstorage at an auxiliary location, and if the changes are saved to a file, they would be removed. If the tab closes unexpectedly, the changes will stay, and then when you reopen Excalidraw, you get a popup which just tells you that whatever.excalidraw (which was last written to at 21:14 on the 24th of April, 2025) was closed without saving, and press the accept button to reopen it. I didn't word that very well, but the Vim users will get it.

**Comment by benevbright** [comment]
So the number of browsers in the world is max number of canvasses you can save?

**Comment by MathiasLui** [comment]
I have saved drawing 1 to disk before, cleared the canvas (as I have not found of any way to create a new one in any other way, I expect to just have a "New" button), then made a new drawing 2, saved that as a new file, and then I noticed it saved *over* the old one as well so I now lost one drawing and have two identical ones. I don't remember hitting "save" either.  
Couldn't a "New" button just clear the canvas and make it so it doesn't override the one that was there previously when saving?

**Comment by dulasau** [comment]
A drawing is saved in LocalStorage, just add a couple of different domains in your hosts file
(e.g. YOUR_EXCALIDRAW_LOCAL_IP draw1.com, YOUR_EXCALIDRAW_LOCAL_IP draw2.com, YOUR_EXCALIDRAW_LOCAL_IP draw3.com, etc), or in your local dns (e.g pihole, etc).
