### ISSUE TITLE
Black background is not black

### ISSUE THREAD

**Issue by sohrab-** [excalidraw/excalidraw#5184]
If I have a drawing with a black background (confusingly, `#ffffff` in dark mode), when I export the image with a background, I expect the background to be `#000000` but it is `#111111` instead.

I have tried a few different things but I do not seem to be able to produce an image with truly black background.

![image](https://user-images.githubusercontent.com/4444588/167967440-3ffa774b-d878-4889-a89a-0aa0004d213f.png)

![Untitled scene](https://user-images.githubusercontent.com/4444588/167967483-2880e034-9789-471c-b58c-247f8eda4725.png)

![image](https://user-images.githubusercontent.com/4444588/167967473-cc2b5f5b-d8f6-47a3-8b55-ed5e2363cb3c.png)

**Comment by dwelle** [comment]
Correct, our dark mode currently doesn't invert the colors fully, so you won't get a true black. This is by design as the primary goal isn't to truly invert, but to be easier on the eyes (secondary goal is to look somewhat nice if dark mode exporting is desired). I believe we follow Google styleguide on this, but not 100% sure.

**Comment by sohrab-** [comment]
It would be awesome if true colours were available, at least for export.

For others that may have the same issue: the transparent background should cover you in most cases (except say Medium where it insists on a white background on image zoom).
