### ISSUE TITLE
detect when browser zoomed and show a hint

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5213]
Basically, we want to detect when people manage to zoom their browsers while using Excalidraw, and show a toast-like message that tells users how they can reset it. I think we can detect this 100%, and it requires some hacks.

Miro does this, though now the message shows on >= 400% zoom on my screen:

![image](https://user-images.githubusercontent.com/5153846/169527577-3c619dda-9e92-41a5-826e-2a47e67f39a2.png)

https://github.com/excalidraw/excalidraw/issues/5157
https://github.com/excalidraw/excalidraw/issues/2449
https://github.com/excalidraw/excalidraw/issues/3372
https://github.com/excalidraw/excalidraw/issues/5211

**Comment by ad1992** [comment]
We could do similar to Miro but its tricky to make it work in all devices+browsers, we will need to test. 
Also in Miro is probably using `window.devicePixelRatio` coz in Safari it doesn't work since the ratio remains same.
We can improve it and use the `ratio` of `window.outerWidth/window.innerWidth` to detect zoom level.

**Comment by ad1992** [comment]
closing via #5304
