### ISSUE TITLE
Drawing a polyline with shift clamped

### ISSUE THREAD

**Issue by DaSh-More** [excalidraw/excalidraw#5255]
If you draw a line using two points, the clamped Shift aligns it in 30° increments. But if you draw a line at several points, pressing LKM each time, it doesn't work.

**Comment by Servinjesus1** [comment]
@DaSh-More This does not seem to be a feature yet. I have added a Feature Request (FR) that includes solving this issue. If adding this feature would solve your issue, feel free to mark your issue resolved.

**Comment by dwelle** [comment]
We should fix/implement these cases specifically:

- holding shift when creating multi-point lines
- holding shift when editing a single point of a line (multi-point or otherwise) when in the line editor
- holding shift while adding a new point in the line editor (via holding option/alt)

Can be done in a single PR or split into multiple.

**Comment by sojusnik** [comment]
BTW, this happens not only with the line tool, but with the arrow tool as well.

**Comment by dwelle** [comment]
Yes, arrow/line is basically the same thing so it'll fix both.

**Comment by ryan-di** [comment]
Looking at it now : )
