### ISSUE TITLE
[Feature Request] Apple Pencil double tap: switch between Pencil and eraser 

### ISSUE THREAD

**Issue by LePenseur13** [excalidraw/excalidraw#5431]
To implement the Apple Pencil double tap feature, would be a huge improvement for IPad users. 

It increases usability, workflow and speed a lot.

especially if you are used to it. 
Excalidraw is great, however the lack of this feature is the reason, why I quite often use another drawing app and the later import it. 

With this feature Excalidraw would replace other apps like Good notes, Notability, etc.

**Comment by with-heart** [comment]
@LePenseur13 Since this functionality is driven by finger taps on the Pencil itself and not taps in the browser, I don't think this can be implemented at the current time.

The only real information I could find related to implementing double taps is the official Apple docs [Handling double taps from Apple Pencil](https://developer.apple.com/documentation/uikit/pencil_interactions/handling_double_taps_from_apple_pencil) article which is for Swift/native apps only.

As far as I can tell, the interaction doesn't trigger an event in the browser that Excalidraw could detect or react to.

**Comment by LePenseur13** [comment]
@with-heart Aren’t there ways one can access native features even in electron?

I found these posts: 
- https://bountify.co/electron-call-macos-requestreview-api (Executing native code in Electron app: with an example)
- https://stackoverflow.com/questions/34670514/can-i-use-osx-native-apis-in-electron

Couldn’t in that direction a solution found?
I’m not an expert here, so sorry if I missed something important.

**Comment by LePenseur13** [comment]
@with-heart you’re right sorry made mistake. Posted to the wrong Repo. In Obsidian there is an awesome excalidraw plugin, and since there it is running in electron, maybe there it is possible.

**Comment by dwelle** [comment]
Yes, I was looking into before and as @with-heart says it's not possible to do handle this in browser at the moment. If Apple implements this, we'll add support on our side!
