### ISSUE TITLE
Undo selecting last shape after freedraw breaks the workflow

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#5437]
What I'm trying to do:

1. Make a shape
2. Freedraw 
3. Realize I've freedrawn with the wrong color (oops) so press Cmd+Z to erase freedraw
4. Change the stroke color
5. Freedraw again (now with the right color)

Actual sequence:

1. Make a shape
2. Freedraw 
3. Realize I've freedrawn with the wrong color (oops) so press Cmd+Z to erase freedraw
4. **Excalidraw selects the last shape**
5. Change the stroke color
6. **Alas, this changed the selected shape's color instead**
7. **Realize the mistake and press on the canvas to try to make the color selection popup disappear**
8. **This causes a dot on the canvas (because freedraw is still selected)**
9. **Cmd+Z to get rid of the dot**
10. **Cmd+Z to undo the change of the shape color**
11. **Select pointer tool**
12. **Press on the canvas with the pointer to get rid of all selection**
13. **Select freedraw tool**
14. Change the stroke color
15. Freedraw again (now with the right color)

These steps in the middle seem unfortunate but I do them many times a day.

I'm not sure what the right fix is (which is why I've described the sequence). I think I'd expect that Cmd+Z'ing the freedraw doesn't select the last shape.

**Comment by dwelle** [comment]
Yeah, agreed that this isn't ideal.

I've checked how other apps do it:

- Miro: no re-selection whatsoever on either redo/undo
- Figma, Tldraw, Affinity: if you deselect or when a shape isn't selected after creation (e.g. for locked tools), and you then create another element which you undo, the previous element isn't selected.

We should align with the latter. Unclear how easy that'll be with our current history model.

**Comment by Mrazator** [comment]
A possibly easy fix is capturing tool selection in history, the downside is the additional undo entry of deselection. I would say it's likely worth the tradeoff, but not super persuaded, so it's up for discussion.

Please check the behaviour in https://excalidraw-git-mrazator-record-unselection-excalidraw.vercel.app/ (to confirm whether it's worth fixing the tests).

**Comment by dwelle** [comment]
I think adding an entry each time we change away from the selection tool isn't the way to go as it's adding too much noise into the undo stack — for example when you create 4 rectangles you'll end up with 7 entries as opposed to 4 as is traditional.

Maybe we can add an entry if switching to a tool that has implicit tool lock enabled (in this case, freedraw is such a tool) which doesn't end up in selecting the freedraw shape once you finish drawing it, unlike with not-tool-locked shapes.

**Comment by Mrazator** [comment]
My initial concern was that a similar issue would persist when switching between other tools (i.e. rectangle -> diamond), especially when using shortcuts:

1. Make a rectangle (press 2, draw)
2. Make a diamond (press 3, draw)
3. Realize I've drawn a diamond with the wrong color (oops - panic, chaos) so press Cmd+Z to erase it (instead of changing the color directly)
4. Change the color (oops, I've just changed the color of the previous rectangle instead)
5. Press Cmd+Z to undo the change
6. Make a diamond (press 3, now change the color, draw).

Once you get used to it, it seems obvious now to change the color in step 3 immediately, but from my own experience, I've caught myself in this loop multiple times previously, intuitively pressing Cmd+Z when something goes wrong (panic, chaos).

The change above does not make this much better, as the diamond gets unselected (not locked), but it avoids doing steps 4. and 5. 

Anyway, what you proposed sounds even better, though the discrepancy between freedraw (auto-locking) and other tools (switching to selection) might also be slightly confusing.

**Comment by dwelle** [comment]
> Once you get used to it, it seems obvious to change the color in step 3 immediately, but from my own experience, I've caught myself in this loop multiple times previously, intuitively pressing Cmd+Z when something goes wrong (panic, chaos).

Though, as you mention, it has a solution that users just need to (and will likely) find out.

With the OP, you can't avoid the extra step.

> Anyway, what you proposed sounds even better, though the discrepancy between freedraw (auto-locking) and other tools (switching to selection) might also be slightly confusing.

Technically there won't be a discrepancy as the step of "deselect the rectangle by changing to freedraw tool, then draw with freedraw, and undo" suggests that undoing should land you to the previous state, which is the rectangle being deselected.

I'd try it, and see!
