### ISSUE TITLE
Feature Request: Line tool without curves for creating polygons

### ISSUE THREAD

**Issue by MxMossy** [excalidraw/excalidraw#5457]
Currently the line tool adds a curve to move from point to point but I think it would be nice to have the option to have just straight lines to create arbitrary filled polygons like in most CAD software. The shape on the left is created with the line tool but the shape on the right can only be made with the square tool.
![image](https://user-images.githubusercontent.com/11238512/179426844-38c657c9-0248-4992-9f0c-c5bded393041.png)

My use case  for this would be creating diagrams like below. I would like to be able to draw the cube with connected lines so I can fill in the faces. I could do this with the rhombus tool but that would be really finicky.
![excalidraw_example|500](https://user-images.githubusercontent.com/11238512/179426808-7c765533-7d04-4c29-bc39-cddd53bde7f0.png)

**Comment by DanielJGeiger** [comment]
@MxMossy You can achieve this currently by setting "Edges" to be "Sharp" instead of "Round".  (As a side note, my PR #5311 lets you type the formulas in your second screenshot as Latex.)

@dwelle @ad1992 Making this choosable by default would be another use-case for the `ExcalidrawElement` subtype system I use to implement the MathJax plugin in the `@excalidraw/plugins` package I proposed.

**Comment by MxMossy** [comment]
Oh I completely missed this! Thanks, will close this issue.
