### ISSUE TITLE
How do you rotate linear elements? Since the linear elements redesign (#5501) I am not able to rotate arrows and lines

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5535]
https://user-images.githubusercontent.com/14358394/182805730-1ad74bca-da46-4383-b03b-6d89f2a68ae8.mp4

**Comment by zsviczian** [comment]
@ad1992: FYA

**Comment by dwelle** [comment]
Yes, this is the unfortunate side effect of the redesign, and I agree that rotation is still useful enough to be considered for reintroduction in some form.

I'm seeing to options:

1. show the rotate button at the start/end of the arrow (because for multi-point arrows it'd be hard to place it), and maybe change how to rotate button looks in the process to make it more obvious (though we'd then have to change it for all shapes).

	![image](https://user-images.githubusercontent.com/5153846/182816823-ba91dd7f-d0ec-4328-9118-362b071be6f1.png)

2. Ditch the rotate button and do what most other vector apps do: change the cursor to rotate when you hover over the bounding box / edge of the arrow (again would have to apply to all shapes to make consistent). Below is Figma:

	![figma-rotation](https://user-images.githubusercontent.com/5153846/182817332-bb2ad1ab-becf-4cdc-a633-275614539dbc.gif)

**Comment by zsviczian** [comment]
I grouped the linear element with a transparent other element for the purpose of the demonstration. This approach would work for me - and it already works if the selection box is displayed.

Why did you decide to not display the selection box for linear elements? 

https://user-images.githubusercontent.com/14358394/182831666-ea9e7b88-041e-4321-a4c9-64d7beb235d3.mp4

**Comment by ad1992** [comment]
> Why did you decide to not display the selection box for linear elements?

@zsviczian since we are now showing the points on arrow itself which helps in better user experience when updating arrows as compared to bounding box hence we decided to remove the bounding box.
As per rotation we are exploring the options and will be reintroducing rotation soon.

**Comment by zsviczian** [comment]
...and what is against showing both the bounding box and the points in parallel?

**Comment by zsviczian** [comment]
I just ran into a use case where I wanted to resize a linear element. Resizing both with and without locking aspect ratio is important also for linear elements. It all worked nicely before :(

for reference, this is the element I wanted to resize to match the amount of text...

![image](https://user-images.githubusercontent.com/14358394/183054629-d44066f7-709d-4dca-872a-6eab5b8e0459.png)

**Comment by ad1992** [comment]
> I just ran into a use case where I wanted to resize a linear element. Resizing both with and without locking aspect ratio is important also for linear elements. It all worked nicely before :(
> 
> for reference, this is the element I wanted to resize to match the amount of text...
> 
> ![image](https://user-images.githubusercontent.com/14358394/183054629-d44066f7-709d-4dca-872a-6eab5b8e0459.png)

This is actually a good use case. Should we start showing bounding boxes for linear elements with multiple elements / loop ? 
cc/ @dwelle

**Comment by aej11a** [comment]
I like the redesign of the points but I don't see why you can't have the bounding box too - it's still helpful for resizing, rotating, etc

**Comment by dwelle** [comment]
I agree we should definitely reintroduce not just rotation, but resizing as well as commented above.

Since resizing is also needed, the other non-bounding-box options from https://github.com/excalidraw/excalidraw/issues/5535#issuecomment-1205020168 will not solve this.

Question remains, when do we want to show the bounding box? For me I'd do so _at most_ from 3 points and up.

**Comment by dwelle** [comment]
But even for 3-point lines it may be premature, especially for arrows, because we'll end up with:

![image](https://user-images.githubusercontent.com/5153846/183293126-391a9028-e3e4-473a-a69e-be76eec4bc91.png)

Which means the arrow points will often "collide" with the bounding box handles (though we'd likely make them have preferential hitboxes).

**Comment by aej11a** [comment]
@dwelle I think 3 points has the first valid use-case for resizing - the only other way to resize would be to move each of the endpoints individually.

Maybe a very small padding could be added to the bounding box? About equal to the radius of the pt handles?

**Comment by dwelle** [comment]
You can leave feedback on https://github.com/excalidraw/excalidraw/pull/5554#issuecomment-1210552320 in the PR.

**Comment by ad1992** [comment]
closing this via #5554
