### ISSUE TITLE
Excalidraw drawings are not getting saved.

### ISSUE THREAD

**Issue by swetank15** [excalidraw/excalidraw#5830]
None of the options on the left of the Drawing area is opening up. Neither the Save option to Local Disk nor the export as png.

Do I need to register with Excalidraw or something else is the issue  ... 
<img width="1236" alt="Screenshot 2022-11-05 at 9 58 24 AM" src="https://user-images.githubusercontent.com/117499277/200101226-20dcf473-2eea-4e12-8f23-91508451cade.png">

**Comment by dwelle** [comment]
Hi. The message isn't clear (it comes from the browser), but what it means is that the browser thinks you haven't fully interacted with the page so it doesn't allow us to show the file picker (it's a security thing). But that's strange, because you clearly must have interacted with the page by this point.

What's your browser and OS?

**Comment by louis030195** [comment]
I don't know if it's related but my images are not saved, quite pain in the ass and waste of time... 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/25003283/200137438-79e15ef7-2cdc-4e59-a15f-065d4dd38880.png">

Images get broken when leaving tab or changing scene

**Comment by swetank15** [comment]
I'm using chrome on macOS 13

**Comment by swetank15** [comment]
@dwelle thanks for help ... 
I just don't know how ... but its working  now ...

**Comment by dwelle** [comment]
@swetank15 cool. I'm closing for now.

@louis030195 not fully certain what that's about, but this might fix it (for future sessions that is): https://github.com/excalidraw/excalidraw/pull/5839
