### ISSUE TITLE
[FEATURE PROPOSAL] Color Picker

### ISSUE THREAD

**Issue by manuelernestog** [excalidraw/excalidraw#5920]
As a user, I like to have the option to select a color from a color picker, not just an input with the hex color.

I would like to implement this functionality, but I don't know if I should have any approval that it can be included in the project.

Greetings.

**Comment by dwelle** [comment]
Hello. We will be working on redesigning the current color picker soon. I'll create an issue with details to discuss tomorrow.

That said, at current time we are not planning to implement a full color picker in the sense you mean (a color wheel) — mainly because at Excalidraw our goal is to keep it both simple and with as little friction as possible. While that may sound counterintuitive (not forcing you to go pick a color from elsewhere), it's about not overwhelming you with choice (decision paralysis) and consistency. We'll got into this in detail in a blog post later (and I'll some more detail in the followup issue).

I'll keep this open for now so I remember to link this issue.

**Comment by manuelernestog** [comment]
I understand and agree with you that keeping it simple is the right choice. My suggestion is as such for the text input where the selected color appears. Usually these inputs with colors, their main function is to paste the color that one wants or copy the one that is there.

But in case you want to modify them, making them by hand is very difficult because the color that is being selected is not known for sure. My suggestion comes from this problem. 

Suppose I select a color from the Excalidraw palette, but I want to clarify it a bit. This is almost impossible for me to do by hand in that input, I end up opening Photoshop pasting the color and modifying it there for back with that color to excalidraw. 

Maybe using an input `type="color"` or a third party lib for this over the input would improve the UX.

![image](https://user-images.githubusercontent.com/53962116/204909935-c4f0fb5f-2b7c-4c12-bdef-223f37aee555.png)

Again, this is just a suggestion and I understand if you just decide to leave it as it's. I hope it can be of use.

Thanks for this great tool :)
Regards.

**Comment by dwelle** [comment]
Forgot to link the proposal for the new color picker redesign I mentioned. There are some points on why we don't want to go with a full color picker for now, and a proposal for adding color shades that you might find useful enough as substitute — at least that's goal, since Excalidraw shouldn't be about perfection and exactness. That said, as mentioned in the issue the doors to adding that full color picker are still not closed in the future.

https://github.com/excalidraw/excalidraw/issues/5931

Closing in favor of the above issue, so please feel welcome to discuss more over there!
