### ISSUE TITLE
Layers Icons too confusing 

### ISSUE THREAD

**Issue by sedghi** [excalidraw/excalidraw#6003]
As title says

![image](https://user-images.githubusercontent.com/7490180/208187829-45fa3a7d-5e22-4506-8e0c-39bbcc8a2c5f.png)

the above icons are too confusing, I can't get my head around them and I need to hover every time on them to see what they are. 
Can we have simpler icons maybe something similar to Icons as tlDraw has 

![image](https://user-images.githubusercontent.com/7490180/208187967-bdd3571d-edc1-479b-a15a-b5132648bf3e.png)

**Comment by dwelle** [comment]
We used to have it colorized to be more obvious:

![image](https://user-images.githubusercontent.com/5153846/208296171-18367255-93eb-4d3a-a66e-87b3cf23efac.png)

Perhaps we should go back to doing it.

Otherwise, we use these icons because it's a de facto standard. I worry that using arrows in the UI will make people think it's somehow related to arrows.

**Comment by sedghi** [comment]
Colors are much better than what I see right now, but honestly I think the arrows makes the most sense at it reminds me (at least) of the video players navigation (first, previous, next, last). I'm not sure what is the process or whether you do user interviews or surveys. Maybe do a poll on twitter?

**Comment by anatoliibakhtin** [comment]
I would suggest this idea (5) with an explanation of the design change:

Black, white, argue with each other, causing doubt as to which one is the main one, so there is difficulty in understanding how these buttons work.
<img src="https://user-images.githubusercontent.com/71871141/216812232-917f85a8-2452-4565-b612-c6cb416e8ee3.png" width="50%"> 

If you color them, doubts remain if you don't know which color is the accent color.
<img src="https://user-images.githubusercontent.com/71871141/216812235-51021284-ee71-4072-9db7-176cdfde6e3e.png" width="50%">

Because of this, I put even more emphasis on the main element with the scale. 
<img src="https://user-images.githubusercontent.com/71871141/216812241-d2ec8376-3d50-403a-b6d6-e5676ae28643.png" width="50%">
But I don't like how it looks "at the very bottom", too "noisy".

The lowest or the highest usually marks the border of the canvas, so I replaced the square with a silhouette.
<img src="https://user-images.githubusercontent.com/71871141/216812245-cceae043-b5af-405f-94f2-cec09e0785e9.png" width="50%">

And if we have border markings on the left and right I would change their placement to this:
<img src="https://user-images.githubusercontent.com/71871141/216812249-32045506-ab3b-4fb5-b3f9-f63d9b9063aa.png" width="50%">

Thanks for your attention!

**Comment by dwelle** [comment]
@anatoliibakhtin I love your designs!

That said,  the (4)/(5)/(6) are not obvious to me. I could easily explain the (4.1) to both mean either "send to back" or "send backward". And I don't think that (3.1) looking noisy is the issue — it's actually conveying that the selected element (purple) will be hidden behind all the other elements.

I agree on the ordering though.

So we should:

1. go back to using colors
2. order as: `send to back` `send backward` `send forward` `send to front`

**Comment by sedghi** [comment]
Great stuff above. Honestly still I think the arrows is one of the best in conveying the message

**Comment by anatoliibakhtin** [comment]
@sedghi let's dream? If it were possible (I also find arrows to be a faster-reading symbol – it's a simpler figure), which option would you vote for: from 1-6, between A-C ? 
![image](https://user-images.githubusercontent.com/71871141/218254398-f8c82f60-08ff-4604-9cd6-0e0e8714af7c.png)

**Comment by sedghi** [comment]
Hmmm, great options here.
This is my opinion:

1, 2 => too confusing
3 => too video playery 
4 => all looks great and simple. My preference is 4c then 4A then 4B
5 => looks great, I guess 5c then 5B then 5A (too narrow)

**Comment by T3sT3ro** [comment]
In terms of UX the current icons have 2 flaws:
- icon "flow" is counter intuitive with commonly understood left-to-right, top-to-bottom order. The icons are on a bottom-left -> top right diagonal which makes them more obscure
- the "bottom" and "top" element is in the middle of the "stack". It may not look like a stack, but it is.

Here is my proposal:

![image](https://github.com/excalidraw/excalidraw/assets/5300963/7b1050c5-e53a-4d84-ae3c-f1424defb6cb)

The advantages of that approach:
- reads like a stack, you know what is top and what is bottom
- the longer arrows indicate longer moves, i.e. move to bottom/top.
- the bars at the end of an arrow indicate the "edge"
- the "bring to top/bottom" show moving past 2 elements, indicating that it's a longer move
- the "move down/up" show a shorter arrow and only one element
- it is curved to indicate moving it past one object, aka "1 step"
- the active element is clearly indicated with a color
- no diagonal confusion, reads well in both RTL and LTR modes
- colored element indicates the active element and dotted outline indicate previous location

**Comment by anatoliibakhtin** [comment]
😍🎉❤️

**Comment by dwelle** [comment]
@T3sT3ro looks cool, but super complex for icons. Bear in mind that when scaled down to the button size, you'd be barely able to see anything:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/f1eec1ef-66cb-45dd-84ed-3e2e2e01bae1)

In the end we went with the simple arrows:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/66abf52c-915f-4690-84eb-22a8aeb54824)

@anatoliibakhtin thanks for reminding we should close this :)
