### ISSUE TITLE
Move canvas by holding spacebar doesn't work

### ISSUE THREAD

**Issue by TinQk** [excalidraw/excalidraw#6007]
Holding spacebar makes the "hand cursor" appear, but doesn't move the canvas when dragged.

Tested on computer, on windows, with firefox and google chrome.

**Comment by co-bby** [comment]
it works fine on my side. Maybe you can clear cache in your browser

**Comment by dwelle** [comment]
@TinQk just in case, are you click-dragging or just holding space + moving the mouse? If you have a mouse, does mousewheel-dragging work?

**Comment by mickremedi** [comment]
Possibly the confusion is that holding the spacebar sets the cursor to [grabbing](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#:~:text=Something%20is%20being%20grabbed) rather than just [grab](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#:~:text=Something%20can%20be%20grabbed), making people think it's already started grabbing. Possibly changing it so that it starts in grab mode when you hold the spacebar, and switches to grabbing mode when you press on the mouse could fix this confusion?

**Comment by Jeffsingh** [comment]
@mickremedi i've come up with a fix for this.

**Comment by fire17** [comment]
Im getting the same error here, i can see the hand but it is not dragging.
Not in chrome and not in vscode
I am holding space, holding the left mouse button (laptop mousepad), and dragging. nothing happens.

> it works fine on my side. Maybe you can clear cache in your browser

can someone tell me how to clear the cache for just excalidraw? and also.. wouldn't that clear my canvas? (will need to backup save and open file afterwards) + how to clear the vscode version? @co-bby 

Or really any other way to fix this? it's really hard to use without this feature (especially since theres no hotkey (0) to switch to dragging mode)

**Comment by ad1992** [comment]
@fire17 can you check whats the version you are in ? Click on "Stats for nerd" from context menu

<img width="476" alt="Screenshot 2023-08-03 at 8 06 14 AM" src="https://github.com/excalidraw/excalidraw/assets/11256141/ce522d5b-99b7-4e3d-8570-926ffad2c7bd">
