### ISSUE TITLE
render rest children to LayerUI

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6089]
Right now in excalidraw.com we render some app components outside `<Excalidraw/>` but use internal components.

For example, the `<Collab/>` dialog uses `<Dialog/>`, but is rendered outside. So context and atoms (potentially) won't be set correctly.

Thus, this does nothing at best:

https://github.com/excalidraw/excalidraw/blob/618442299f85229a0e5c1fdb7c3bb9aeaa850a50/src/components/Dialog.tsx#L78-L79

When used inside the `<RoomDialog/>`:

https://github.com/excalidraw/excalidraw/blob/618442299f85229a0e5c1fdb7c3bb9aeaa850a50/src/excalidraw-app/collab/RoomDialog.tsx#L178-L185

We should render app-custom `children` passed to Excalidraw to `<LayerUI/>` as is, so we can move the `<Collab/>` inside `<Excalidraw/>`.

Longer-term we'll may introduce an `<ExcalidrawContext/>`, but it's unclear how and whether it will work, and in some cases like the this issue it's unnecessary.

**Comment by ad1992** [comment]
To confirm If I understand correctly, rn since we are allowing only named components, host cannot render anything apart from that and hence the dialog inside collab will not have access to the context, atoms.
To solve this, if we have named `collab` component host will be able to render it. But for other components (custom ones) this is not possible as we filter. 
So one solution is what you are doing but in this we are allowing all top level children to render. Another approach what I think is for those components which could be used outside Excalidraw (so the generic UI components), eg button, dropdown, dialog, these should be pure components and not be dependent on these hooks directly, that way these components could be used outside excal easily and later on if we create a library of UI components of Excalidraw, these components could be directly moved into the library as they are pure components.

**Comment by dwelle** [comment]
> To confirm If I understand correctly, rn since we are allowing only named components, host cannot render anything apart from that and hence the dialog inside collab will not have access to the context, atoms.
> To solve this, if we have named `collab` component host will be able to render it. But for other components (custom ones) this is not possible as we filter.

No, we're just not rendering anything custom from the host. Naming or not naming will not solve it.

> So one solution is what you are doing but in this we are allowing all top level children to render. Another approach what I think is for those components which could be used outside Excalidraw (so the generic UI components), eg button, dropdown, dialog, these should be pure components and not be dependent on these hooks directly, that way these components could be used outside excal easily and later on if we create a library of UI components of Excalidraw, these components could be directly moved into the library as they are pure components. In other words, these UI components shouldn't be tightly coupled to editor.

The Dialog in question is a private component, so excalidraw.com shouldn't even be using it — but it is (meaning, current production is buggy in that the state is not working as intended). We can rewrite the component's API so it's more reusable, but who knows how long that will take. And I'm not confident that we would be able to remove all dependencies on editor state — let's say dark mode toggling or i18n. So it wouldn't be reusable without exposing some Excalidraw provider/context as we discussed and making hosts wrap those components in that provider anyway — at which point whether you render inside the Excalidraw container or in the Excalidraw provider will not make that much difference.
