### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#610]
Right now, in order to create a sharable link, we upload the scene as json to a server that returns an id so that you can retrieve it. It has the unfortunate side effect that the server can read the actual content, which can contain sensitive information.

Here’s a proposed scheme:

Upload:
- The client generates a random secret (eg: 20 characters in base 64, we’ll need to figure out the right size).
- The client uses symmetric encryption to encode the json scene with the secret. (Encryption algorithm to be determined)
- The client uploads the encrypted data to the server (but not the secret)
- The server replies back the id
- The client generates a url that contains the id in the query param and the secret after the # (so it doesn’t get sent to the excalidraw.com server, but is available from locally ran javascript code). We may want to also put the id after the hash too.

Download:
- The client reads the id from the url
- The client queries the server for the id and receives the encrypted data
- The client reads the secret from the url
- The client decodes the json scene from the encrypted data and secret
- The client renders the scene

Open questions:
- Does this scheme make sense?
- What are recommended symmetric encryption algorithms and associated client side libraries?
- What are recommended secret sizes?

**Comment by vjeux** [comment]
It looks like WebCrypto API are now part of the browser and have good coverage: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt

AES-GCM is supported everywhere and authenticated (meaning it has a builtin checksum). It sounds like a good candidate.

**Comment by dchest** [comment]
> Does this scheme make sense?

Yes (of course, given the known limitations of browser-based crypto, where server can send a malicious JS and just send back the secret, etc.).

> What are recommended symmetric encryption algorithms and associated client side libraries?

If old browsers can be disregarded, WebCrypto with AES-GCM would be perfect for this. Since the key is generated randomly for each shared image, the nonce (IV) can be fixed (e.g. to 12 zeroes).

> What are recommended secret sizes?

128 bits would be enough.

**Comment by giuseppeg** [comment]
Probably https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing could work too in this case

**Comment by dchest** [comment]
BTW, with WebCrypto after you generate a key, you can export it as "jwk" (instead of "raw" format and then using a base64 encoder on it). The result will look like this:

```
{alg: "A128GCM", ext: true, k: "2A1lPpSKrau9zi4KgKdNwQ", key_ops: ["decrypt", "encrypt"], kty: "oct"}
```

`k` is already base64-URL encoded, so you can directly put it into the URL hash. To import the key, just construct the same JSON with the key from URL. This avoids having a separate base64 encoder/decoder, and (at least in Chromium/BoringSSL-based browsers) uses the timing safe base64 coder.

**Comment by vjeux** [comment]
@dchest thanks for all the information! It looks like we can start the implementation based on the scheme and your follow-ups!

I chatted with some people offline and there's another detail to consider: the analytics script. If we have the id+secret part of the url, it would send it out. The solution is to put an inline script at the beginning of the page that will read the id+secret part of the url and store it in a JavaScript variable, update the url. Then we can load the scene without the analytics script able to send the url back to the analytics server.
