### ISSUE TITLE
Text shortcut is broken on production

### ISSUE THREAD

**Issue by jillesme** [excalidraw/excalidraw#615]
Clicking the `A` or pressing `T` does not work anymore. After clicking once, we jump straight back the the selection tool. The only way to write something is by double clicking currently.

![2020-01-29 15 31 58](https://user-images.githubusercontent.com/2955483/73406924-86b46980-42ac-11ea-978c-e8c8cec694c2.gif)

**Comment by dwelle** [comment]
Ok, look's like I broke it in #587 after all.

**Comment by dwelle** [comment]
The way it was done in the PR works well, but it's coupled to the `checked` state, so it'll get focus irrespective of how the tool is selected. In the case of text, when you create it we reset tool to `selection` which then adds focus to it, and make the text input lose its own.

We can revert the PR and do it imperatively because there are these edge cases. But I'll revert it first, and make the alternative implem later only if @voluntadpear thinks it's really necessary. Because I'm not sure myself if it's what we want after all --- these edge show that there are many ways in which tool is set/reset, and we'd need to handle all of them separately (where we call `resetSelection`). Also, I'm not sure if it's even the way to go - to force-focus the shape tool on (most) every change, even programmatic.
