### ISSUE TITLE
Upload images to S3 (or some place else)

### ISSUE THREAD

**Issue by rahulwecp** [excalidraw/excalidraw#6151]
Hi,
Currently when I upload an image it looks like the whole base64 data of the image is stored in the elements array. This causes very large size and and since I am saving it to a server, lot of bandwidth is consumed.
Is it possible that when an image is added to excalidraw, it first uploads it to some server (say S3), then stores the link in the elements array. This way the size of the elements to save is also considerable less.

Is this currently possible in excalidraw?

**Comment by dwelle** [comment]
Hi.

We're actually not storing images in the elements array for this very reason, rather in a separate `files` array, that we are passing as the 3rd argument in the `onChange()` callback. Excalidraw.com itself is storing the images on a GCP bucket.

How are you getting the scene JSON so that the elements array contains the image data?

**Comment by rahulwecp** [comment]
My bad, just checked again, it's coming inside files object and not inside elements.
