### ISSUE TITLE
The app is getting too slow with many elements

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#628]
I was just experimenting with bunch of elements.

- 4096 elements: https://excalidraw.com/?id=5461085259825152
- 1024 elements: https://excalidraw.com/?id=5196680764850176
- 256 elements: https://excalidraw.com/?id=5746640992337920

Shall we have some sort of max limit? Can we improve the performance when many items in the scene?

**Comment by dwelle** [comment]
Nice benchmark scenes. I wouldn't set a limit, because each user's machine has difference performance, and ultimately they should be the one to decide.

That being said, we should certainly do all we can to improve it.

**Comment by lipis** [comment]
Yes, setting a limit is a bad idea.

**Comment by dwelle** [comment]
Performance envy: our little scraggly lagging scene of 2d squares vs this https://8fo01.csb.app/ (courtesy of react-three-fiber).

**Comment by pshihn** [comment]
I've thought about creating a webgl shader for roughjs, but it's one of those tasks where I go "Do I really want to start this?" and abandon.

**Comment by dwelle** [comment]
Let's do what we can on our end first.

**Comment by vjeux** [comment]
Would love to see a webgl renderer personally. I believe that it should solve the performance issues if well designed.

**Comment by vjeux** [comment]
This shouldn’t be too hard btw. We only are rendering a few simple elements.

**Comment by pshihn** [comment]
I was looking at this. Just the act of selecting a shape with a single click, caused the canvas to re-render 3 times. I haven't done React, so hard for me to guess what's causing these render calls. 

I have a general suggestion independent of this observation though, that has helped with canvas related performance issues before: 
Layer a transparent canvas on top of the main one. The main canvas is the full scene. The overlay canvas is the "draw" canvas. When an item is selected, or a new one is created, it moves to the draw canvas. As you are dragging or editing the shape, only the draw canvas is cleared and updated. As soon as editing is done, the shape is rendered back to the main canvas. 


This prevents big re-renders. Also, since the draw canvas only has the selected shape(s), you don't need to clear the whole canvas every time, just the rect around the shape.

**Comment by dwelle** [comment]
@pshihn interesting idea, but how would we handle z-indexes? We'd probably have to move all shapes that have higher z-index than the active element to the draw canvas, too.

![excalidraw_z_indexes](https://user-images.githubusercontent.com/5153846/73529976-e54a2680-4417-11ea-8fee-19421def29c2.gif)

**Comment by pshihn** [comment]
I was thinking of moving the selected item to the top and then sink it back in when unselected. Not the ideal case, but I don't think it breaks my mental model. 

Option 2 (less appealing but performant): Some other editors (like illustrator) sometimes only draw the selection outline when selected and not render the whole object till the change has been made.
![Jan-31-2020 08-36-09](https://user-images.githubusercontent.com/833927/73556780-f6d60300-4404-11ea-81f7-cc433232e1c5.gif)

**Comment by dwelle** [comment]
I think either of your proposed solutions are too drastic. One would result in z-index changes on each drag/resize/etc., and the other would prevent you from seeing the end result until mouseup.

IMO we should aim at optimizations that are completely transparent to the user.

**Comment by pshihn** [comment]
Fair enough :)  hoping those thought could seed something better. 

Perhaps small steps at a time.
I still don't know why `renderScene` is called so many times. e.g. when you tap on a shape to select it, causes at least 3 full renders rather than one. This is where my ignorance in React prevents me from investigating further :)

**Comment by dwelle** [comment]
> I still don't know why `renderScene` is called so many times. e.g. when you tap on a shape to select it, causes at least 3 full renders rather than one. This is where my ignorance in React prevents me from investigating further :)

Yes, we do many things inefficiently, which is why I suggested we should fix it on our end, first, before bothering you to make changes in rough.js :).

**Comment by vjeux** [comment]
componentDidMount is called three times upon loading. The first one is the initial render, the other two are from the internalization code :(

**Comment by vjeux** [comment]
- on mouse down, setState is called three times, but only triggers a single componentDidUpdate (good).
- on mouse up, there are two consecutive sequences of setState / componentDidUpdate (bad). I'm investigating what's going on.

**Comment by dwelle** [comment]
Note that if it pertains only to event such as load, mouseUp, mouseDown etc., then it's non-critical. We need to ensure we don't do multiple renders during mouseMove.

**Comment by vjeux** [comment]
We seem to be only running componentDidUpdate once on every mouse move when dragging. And never when not dragging (just hovering). We should be good on this front.

**Comment by vjeux** [comment]
I figured out why we're doing double rendering onMouseUp. We are not using the onMouseUp react lifecycle but manual event listening, so the setState batching doesn't happen. We either need to add the batching (need to figure out the API for it) or remove the non-needed empty setState.

https://github.com/excalidraw/excalidraw/blob/master/src/index.tsx#L1335-L1346

**Comment by vjeux** [comment]
#636 is fixing the double rendering on mouse up

**Comment by vjeux** [comment]
#636 and #638 landed, we should no longer have multiple renderings

**Comment by vjeux** [comment]
For 256 elements, it takes 50ms per frame, but only 6ms in js. So most of the time is spent drawing to the canvas. This is the place where we need to figure out how to optimize in order to improve performance.

**Comment by vjeux** [comment]
I did a quick prototype where instead of memoizing the rough operations and replaying them, I create a canvas and draw the rough operations. Then on every frame I just copy the canvas via (https://stackoverflow.com/questions/4405336/how-to-copy-contents-of-one-canvas-to-another-canvas-locally) and it's dead smooth!

256 and 1024 are 60fps. 4096 runs at 30fps!

For 4096, there's 20ms running in js and 10ms in draw. So we have room to optimize there.

There's still more work to do before we can ship:
- Rough can draw things outside of the bounds but we cut it
- I'm not sure if the 2x retina scaling is working

![image](https://user-images.githubusercontent.com/197597/73588518-08c9ab80-44c2-11ea-9f41-9b18162b9171.png)

**Comment by vjeux** [comment]
I fixed it by adding a bunch of context translate and scale (which is going to be expensive). Here's the profile before/after for the 256 elements scene:

Before:
![image](https://user-images.githubusercontent.com/197597/73588685-01a39d00-44c4-11ea-884a-5d1bb878d42e.png)


After:
![image](https://user-images.githubusercontent.com/197597/73588695-1e3fd500-44c4-11ea-9124-eb5782b36eb4.png)

We're barely spending any time in the frame!

**Comment by lipis** [comment]
I think it got better now!
