### ISSUE TITLE
Revisited my previous drawing and all the text is now broken. 

### ISSUE THREAD

**Issue by savager** [excalidraw/excalidraw#6325]
This is the non-logged in version. Just stored in session state. I tried messing with the settings and can't get the text to go back to normal. It's almost like it's masked. But it's also disconnected from the shape now. 

![image](https://user-images.githubusercontent.com/1455337/223222122-0c65a5cd-8f83-4255-a5ba-c3a6016eaa2c.png)

**Comment by ad1992** [comment]
@savager when you try to edit it does it get fixed? 
If it is not confidential do you mind exporting it as a link and share?

**Comment by ad1992** [comment]
Have been trying to reproduce this issue with very old commits but no luck yet :(
One of my strong guess is for text containers, the `container` is computed as `null` in `getContainerElement` when called from `refreshTextDimensions` when fonts are loaded. This could be coz the scene doesn't have a reference of the container element yet and hence it's returning null due to which dimensions will be mismatched and break for the user. Faced a similar issue recently in alignments as well - https://github.com/excalidraw/excalidraw/pull/6180/

**Comment by savager** [comment]
It is not confidential. Just some random notes. Here ya go. Thanks so much. 

https://excalidraw.com/#json=-DV4Cph-GwtrlhYpHZ-d5,Mq55Gk1Z99mCPwtNPEPrLQ

**Comment by savager** [comment]
No, unfortunately in Brave Browser it never looks right. I've tried incognito, wiping storage, etc. I tested in chrome and it works fine. Thanks I just hate chrome.

**Comment by ad1992** [comment]
One more thing to note - Only opening the link for first time the issue is reproducible in all browsers and on refresh it gets fixed and this I have verified in all browsers including brave as well (Open any empty browser and try loading the link). I am on Mac.

And that's because we don't refresh dimensions when loading from a shareable link but we do on refresh (loading from local storage) hence it gets fixed. I will raise a PR for refreshing the dimensions when loading from shareable links as well and that should fix this issue.

But @savager will need you to confirm if the same happens for you as well and does it get fixed after you refresh on brave as well?

**Comment by ad1992** [comment]
@savager can you try opening https://excalidraw-git-aakansha-refresh-dims-on-json-load-excalidraw.vercel.app/#json=-DV4Cph-GwtrlhYpHZ-d5,Mq55Gk1Z99mCPwtNPEPrLQ and confirm if it works in brave as well? 
Works for me in all browsers on Mac

**Comment by savager** [comment]
Wow, you definitely figured it out. Disabling "Aggressively block fingerprinting" fixes the issue. Thank you for working through this! I wasn't aware that feature mangled url params and or stored data!

**Comment by ad1992** [comment]
@savager closing this as now we show a warning as well in case someone uses Excalidraw on Brave with Aggressive Block Fingerprinting to inform the users about the same
