### ISSUE TITLE
CTRL/CMD to disable binding unbinds both sides of the arrow

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6459]
https://user-images.githubusercontent.com/14358394/232199548-ee05eef2-f1ab-4589-8baf-9f1355a5e174.mp4

**Comment by SnorfYang** [comment]
https://github.com/excalidraw/excalidraw/blob/b0b23353cfbb2def4bcceabdfbd2f0f3cf6d7f51/src/element/binding.ts#L41-L45

**Comment by lirbre** [comment]
Hey! I just took a look on this bug and I don't know if it's intentional.

Look at this if statement explicitly disabling binding when `event[KEYS.CTRL_OR_CMD]` 

https://github.com/excalidraw/excalidraw/blob/b0b23353cfbb2def4bcceabdfbd2f0f3cf6d7f51/src/components/App.tsx#L2151-L2153

Just by commenting these lines I got the following behavior:

https://user-images.githubusercontent.com/86065449/232356691-9d5532ec-d6e6-4827-961d-3ac7f2abcc17.mp4

**Comment by lirbre** [comment]
Dropped a PR to show the changes that I noticed doing that

**Comment by SnorfYang** [comment]
This is intentional. In the help documentation, Ctrl/CMD disables binding.

**Comment by dwelle** [comment]
Correct, the goal of this issue is not to disable the `cmd/ctrl` behavior, but make sure that if you're dragging a single line end-point while holding `cmd/ctrl`, only the single respective binding is disabled, and the other end is preserved (unlike current behavior where both endings are disabled).

**Comment by lirbre** [comment]
So we should refer to
 https://github.com/excalidraw/excalidraw/blob/c3e8ddaf580f395366ff1fded0c9592a4485c701/src/components/App.tsx#L5470-L5476
 
 `unbindLinearElements` which is unbinding everything.  I'll try to implement countermeasures to this but the way it's currently implemented is intentionally disabling all bindings from the selected element when pressing `cmd/ctrl`.

**Comment by sjoelee** [comment]
@lirbre are you still working on this? @ad1992 @dwelle do you mind if pick this up if @lirbre isn't working on it?

**Comment by lirbre** [comment]
Hey @sjoelee. I'm not! About working on it, I don't really think you need permissions. Give it a shot. :)
