### ISSUE TITLE
[user feedback] I have lost my user data, please provide the official measures to solve it.

### ISSUE THREAD

**Issue by kurisaW** [excalidraw/excalidraw#6505]
Why didn't you inform the website to update in advance? All my drawing data was saved locally in the browser recently, but because you updated it, all my data was lost. Is there any way to remedy this?

**Comment by ad1992** [comment]
Hey @kurisaW can you elaborate what update from our side caused your data loss ? 
We store the data in the browser local storage so unless and until your local storage was cleared, the data should always be restored.

**Comment by kurisaW** [comment]
I correct my statement, it should be my own problem, here I apologize to you, I remembered I did a browser cleaning some time ago, this may be the cause of my data loss, is there any way to remedy it.

**Comment by ad1992** [comment]
Hi @kurisaW so sorry there is no way to restore it since the data is stored browser local storage and it was cleared :(. 
However to avoid such scenarios in future, here is what you can do
1. You can save a copy of your drawings in local file system
![image](https://user-images.githubusercontent.com/11256141/233774813-33d73faf-70c2-47b1-823b-c9d83e4a7219.png)![image](https://user-images.githubusercontent.com/11256141/185901419-3b380405-7491-4a1e-9f5c-fe74ee9c3053.png)
You can keep saving the data periodically as well using "Save to Current File" to have a backup
2. You can use shareable links to export your drawings
![image](https://user-images.githubusercontent.com/11256141/185901686-8b528706-71bd-4626-a024-57aa1274f295.png)

**Comment by kurisaW** [comment]
That seems to be the only way, but thank you for your reply. Have you considered adding user database and providing user login function, and then storing user drawing data in it, so as to facilitate user data storage and remote use, and avoid my tragedy from happening again? I think you can consider this aspect.

**Comment by ad1992** [comment]
Hey we already have [Excalidraw Plus](https://plus.excalidraw.com/) for the same. :)
