### ISSUE TITLE
Resources not cached

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#656]
It seems that resources are not cached (due to `max-age=0, must-revalidate`). Not sure if this is due to CRA, or not. I'd say at least fonts should be cached.

![image](https://user-images.githubusercontent.com/5153846/73593749-c1660e00-4507-11ea-87f6-1714ea4a1f95.png)

**Comment by voluntadpear** [comment]
This is due to Netlify's [default policy around caching](https://www.netlify.com/blog/2017/02/23/better-living-through-caching/). We can customize this on the [headers file](https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers).

I think we can keep `max-age=0, must-revalidate` for the HTML entry point, have a better caching strategy for the fonts and perhaps use `immutable` for our CSS and JS assets since we are adding hashed suffix to them.

**Comment by vjeux** [comment]
We moved to zeit and all the headers are now properly set: 
![image](https://user-images.githubusercontent.com/197597/76708513-9a792b00-66b4-11ea-92e8-dd65611616af.png)

**Comment by dwelle** [comment]
I'm still getting 304s on chrome, and 200 (!) on FF (which supposedly supports `immutable`, while chrome doesn't).

I think for the cache to work properly, the header would must be set to `public` or something similar.
