### ISSUE TITLE
Improve Arrow Binding UX

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#6685]
1. Right now we auto bind arrows to the shapes as they are close by but this could be annoying at times when I don't want to bind it and still its bind so we should have a way to unbind it as well. 

This gets worse when arrow gets bind to a text and you try to move text but as a result arrow moves as well (Notice when I am trying to move the text "HELLO")

https://github.com/excalidraw/excalidraw/assets/11256141/f2e77ffb-f70b-4ad7-8b1c-98282c1b7934

This has been one of the requests as well from users so linking all issues here and we will be discussing her how we want to approach this so we can allow unbinding as well and improve overall UX for arrow binding

https://github.com/excalidraw/excalidraw/issues/3690, https://github.com/excalidraw/excalidraw/issues/2138, https://github.com/excalidraw/excalidraw/issues/4797, https://github.com/excalidraw/excalidraw/issues/6631

2. There is one more case as mentioned here in https://github.com/excalidraw/excalidraw/issues/4324 about not binding arrow to elements outside the group (when arrow is inside the group) which makes complete sense as well

**Comment by realkosty** [comment]
It would be fantastic if this was fixed. Ideally it's implemented in such way that doesn't require disabling snapping for every single arrow created. That would destroy the purpose - now instead of constantly positioning the arrow that should have moved back into its place, we'd be constantly disabling snapping behavior.

Maybe just a global toggle that enables/disables behavior for entire canvas?

**Comment by boblehest** [comment]
To me this appears to have been closed without addressing the issue. The fix (#7946) says that it now only binds arrows when the ends are moved; this sounds like it's preserving the undesirable behavior demonstrated in OP's video (unintended binding while moving end of arrow.)

**Comment by sesse** [comment]
> The fix ([#7946](https://github.com/excalidraw/excalidraw/pull/7946)) says that it now only binds arrows when the ends are moved

Oh wow, so _that's_ what's happening! I've been trying to figure out for the life of me why I couldn't bind my arrows to boxes anymore; it was as if everything was cursed and only old ones would still be bound to boxes. It took me a month or three before I found this issue. Dragging the end instead of the entire arrow (it's small) makes it bind again.
