### ISSUE TITLE
[Feature] Resize multiple objects (shapes, lines, ...) in one direction at once

### ISSUE THREAD

**Issue by Nhiet-MD** [excalidraw/excalidraw#6774]
Hello zsviczian,

Thank you for your wonderful Excalidraw, it really boost my productivity with Obsidian. I have a feature request as following:

Say I'm creating a table. I drew lines, then I make contents in the cells. Suddenly a certain chunk of text is quite big, it goes outside the right border of the containing cell. So I have to pull the overlapping line (and also other parallel lines behind it) to the right. And now all the horizontal lines are quite short, they don't cover the last column. So I have to lengthen them to the right, which can only be done by manually selecting and stretching each line, because mass resize can be done only for both vertical and horizontal directions, not for a single one.

Please consider making resizing in one direction possible for multiple objects at once.

Additional context
![image](https://github.com/excalidraw/excalidraw/assets/112700361/3bd7b8ee-4616-4fcd-bdcb-39a02f824fc4)

Please consider my request. Thanks a lot!

Regards,

Nhiet

**Comment by dwelle** [comment]
Hi, we're already tracking this over here: https://github.com/excalidraw/excalidraw/issues/5423

We should get around to it at some point, though until we move to a generic shape implementation it will not be a true constraint-less resizing because we need to maintain the side angles that each shape is designed for (e.g. rectangle needs all angles to be 90 degrees).
