### ISSUE TITLE
Linux middle mouse button panning pastes clipboard items when user-agent is changed

### ISSUE THREAD

**Issue by TKperson** [excalidraw/excalidraw#6827]
I used a browser addon that masks my user-agent for privacy reasons. That caused the fix made by #1402 to not work correctly because `window.navigator.platform` did not return "Linux" after the user-agent changed.

**Comment by ad1992** [comment]
Hmm but since this is a linux specific issue so we need the `navigator.platform` to identify the OS so if the useragent isn't available then the fix won't work as expected. Probably you can check if you can whitelist the `excalidraw.com` domain to access the `navigator.platform` ?
We should start showing error in such cases where `navigator` isn't accessible to communicate to users

**Comment by TKperson** [comment]
Hi, sorry for the late reply. My solution was to disable the addon whenever I use excalidraw. The solution in the pull request seems a little hacky, it feels like there has to be a better way.

**Comment by ad1992** [comment]
> Moving with middle button paste unwanted elements on Linux #1383

Sure there possible could be a better way, PR always welcome :)
 I will close this issue for now then.
