### ISSUE TITLE
No undo for Frame deletion 

### ISSUE THREAD

**Issue by garuna-m6** [excalidraw/excalidraw#7040]
I accidentally deleted entire frame i was working on but the redo doesn't help me retrieve it back, any help to get back 2 day effort.

can share room id if required and helps to trace logs

**Comment by Mrazator** [comment]
We are sorry about the issue, it's likely due to the previously broken undo/redo implementation.

However, as part of https://github.com/excalidraw/excalidraw/pull/7348, we've recently shipped improvements for undo/redo on excalidraw.com & will be shipped on plus.excalidraw.com soonish!

Hence this issue should not be anymore reproducible.
