### ISSUE TITLE
Vertical arrows are extremely hard to select and drag; drag cursor is missing

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#706]
Especially in combination with #703

<img width="44" alt="Screen Shot 2020-02-04 at 3 02 37 PM" src="https://user-images.githubusercontent.com/498274/73795444-7ba38280-475f-11ea-884a-684ec314f064.png">

**Comment by vjeux** [comment]
Indeed, you need to select the 3px of the arrow to select it. I thought we were looking at the distance between cursor and the line and put some "padding". Something is not right here.

**Comment by vjeux** [comment]
Something is wrong with the hit test function

- For the arrow, only the left part of the line is hitting, not the right. Also the cap (>) of the arrow doesn't seem to be hit tested.
- For the vertical line, you need to be straight on the line to hit test.
- For the curve, the top of the curve seems to be working on both sides. But the rounded part only on the inside.

![ezgif-3-de49c73478b8](https://user-images.githubusercontent.com/197597/76709479-4c682580-66bc-11ea-84b0-14b266279211.gif)

http://localhost:3000/#json=6024311835983872,8AF-xvL2k_GDVCmf6tO1Jw

cc @GasimGasimzada

**Comment by j-f1** [comment]
It might be useful to have a few debug tools, including rendering hit areas for things like resize handles and selection.

**Comment by lipis** [comment]
That's exactly what I wanted to say @j-f1.. you were faster :)

**Comment by vjeux** [comment]
I believe this is the issue:
https://github.com/excalidraw/excalidraw/blob/e1e2249f577d73229902ad23ad76b2c880a39350/src/element/collision.ts#L202

epsilon is supposed to be small in order to avoid rounding errors. This is not meant to be the distance.

The correct approach is to first find the point on the bezier curve that's closest to the point we're looking for. And then to compute the distance between that point and the original point. If it's smaller than 10 then it's a hit.

**Comment by vjeux** [comment]
Okay, found the issue, the bounding box heuristic is wrong

https://github.com/excalidraw/excalidraw/blob/e1e2249f577d73229902ad23ad76b2c880a39350/src/element/collision.ts#L167-L170

**Comment by sompylasar** [comment]
Can arrows be handled better than with a bounding box? Be defined and have draggable points instead of being scaled like an opaque rectangle? Negative sizes might be a problem, too, when arrows need to be flipped.

**Comment by dwelle** [comment]
> Can arrows be handled better than with a bounding box? Be defined and have draggable points instead of being scaled like an opaque rectangle? Negative sizes might be a problem, too, when arrows need to be flipped.

Having access to underlying bezier handles is/was a long-term goal (maybe isn't anymore, not sure), but it seems we're not tracking it anywhere, so maybe create a new issue (since it's unrelated to this one).

**Comment by vjeux** [comment]
@sompylasar this is a two steps process:
- first we compute a rough bounding box to see if the element is within. If not, we bail. The issue here is that we don't correctly extend it: we only add the threshold to y1 and y2, not x1 and x2. So for vertical it doesn't work.
- then we take the shapes (the output of roughjs) and compute precise hit testing on those. This is almost correct, it is for some reason using 20 instead of 10 and doesn't take into account zoom.

PR incoming.
