### ISSUE TITLE
Notion Embedding Doesn't Sync With Live Collaboration

### ISSUE THREAD

**Issue by sanchitram1** [excalidraw/excalidraw#7097]
So, i'm unsure if this is a Notion bug, or Excalidraw, but a simple workaround to embed Excalidraw drawings in Notion is to create a collaboration and then embed the room's URL into Notion as an Excalidraw Drawing.

I found that Notion doesn't keep the excalidraw drawing up to date however.  I think it might be because Notion has some sort of cache of a drawing in Excalidraw, because if I create multiple Excalidraw Rooms, Notion will always pick the first one that I had created to Embed

# Steps To Reproduce

## Excalidraw

1. Create an Excalidraw Whiteboard
2. Make it a session
3. For example; https://excalidraw.com/#room=bb2cd8e8bdc33286cf86,U6CG2ukiyBNVz9E8mOL7Nw
This should be a Whiteboard with two boxes, A going to B

## Notion

1. In a Notion Page, hit `/` and embed an Excalidraw Whiteboard
2. Navigate back to Excalidraw Web, and edit the Whiteboard

I do not see any changes reflected on my end. Is anyone else seeing this?

**Comment by JaguarsCodehub** [comment]
Yes this was previously working very well  couple of months ago, when I was using it on Notion. Now however, it doesn't work as you said. Notion is only taking the first excalidraw board ever created on Notion.

**Might be a issue on Notion's end.**

**Comment by sanchitram1** [comment]
Per Notion's Instructions, I tried the [following instructions](https://www.notion.so/help/reset-notion).  This does indeed reset the cached Excalidraw Diagram Notion stores, but still does not solve the problem.

If you subscribe to Excalidraw+, is this issue mitigated since each whiteboard will have its own URL?  My guess is no, since the room kinda achieves the same thing, right?

**Comment by manumonti** [comment]
Same issue here.

**Comment by ShravanSunder** [comment]
This is still an issue.  Its an issue with excalidraw and any iframes.  cc @dwelle 

Reproduction
1. https://jsfiddle.net/eu12yopc/
2. excalidraw share:  https://excalidraw.com/#room=b92d5e15419d01fb49fe,1VuxwYSOSZhojuyASO72Bg

There should be 3 boxes in iframe.  
- 1: `instructions`
- 2: `made in iframe`
- 3: `not made in iframe`


So any excalidraw share room in iframe doesn't seem to render properly in iframe, and that's why we can't embed it in notion.

![2024-08-31 0850 Brave Browser Notion Embedding Doesn't Sync With Live Collaboration · Issue #7097 · excalidrawexcalidraw](https://github.com/user-attachments/assets/8203b62c-9c34-49a2-b562-58405f966068)


![2024-08-31 0851 Brave Browser mtolmacswasm2map WebAssembly sourcemap generator and WASM binary source mapping url section patcher](https://github.com/user-attachments/assets/b35dc3a5-2502-4478-be52-978a0d370f9a)


We can see drawings in the room link are not reflected in drawings in the room link embedded in the fiddle.

**Comment by dwelle** [comment]
We currently don't have plans to enable embedding live collab links into 3rd party websites. To collaborate freely, you can use excalidraw.com collab rooms directly.

**Comment by ShravanSunder** [comment]
@dwelle I understand.  My usecase was just to have live view of an excalidraw link embedded in notion (rather than colab).  Is that possible now or would you consider it?  

I tried the read only view, and it has similar problems when put in a iframe

**Comment by dwelle** [comment]
Non-collab links are stored in the browser, so that won't work. We do support creating proper embeddable links in Excalidraw+ though.

**Comment by d-roak** [comment]
The current embed shouldn't be ambiguous if it's not in the current plans to support live collaboration. You need to pass a URL for the embed when you use it.

![Image](https://github.com/user-attachments/assets/96bb8b88-a46a-4efb-b507-cefec174b914)

It makes more sense that it would just create an empty excalidraw canvas
