### ISSUE TITLE
Embedding issue while sharing a session

### ISSUE THREAD

**Issue by xeen0** [excalidraw/excalidraw#7103]
Input:
1. Draw a web embedded with some YouTube video link
2. Start sharing the session

![](https://github.com/excalidraw/excalidraw/assets/12679388/c41f1999-73a0-4347-b97e-b681f99aa912)

Issue: The embedded preview starts to blink, and makes it difficult to interact with embedded web 

Platform: Chrome Browser
os:  Ubuntu,

**Comment by protoys-webdev** [comment]
I am experiencing the same issue. 
testing scenarios:
- same pc, 2 sessions
- different pcs, 2 sessions
- pc and smartphone, 2 sessions

Since it seems to be about how information about live content is synced between two sessions, I guess this is not a new issue but rather an architectural/foundational one.

Possible solutions from my perspective:
- run async views on live content during collaboration (kinda defeats the purpose but would make it somehow usable for now)
- lock control for a live content tile for the user interacting with it. then use streaming/broadcasting to update the other collaborators (use Twitch API?)
- ... ?

**Comment by Amey-Chaudhari** [comment]
it is working fine on my side

**Comment by protoys-webdev** [comment]
just tested it again. Seems like they deactivated live web views in collaboration mode for now.
