### ISSUE TITLE
Bug: When is screen 682 hand sign is not visible 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [excalidraw/excalidraw#7125]
![Screenshot from 2023-10-09 21-41-05](https://github.com/excalidraw/excalidraw/assets/78332454/029ca326-dcda-42c7-8f2d-4c11463874e4)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by abishek0057** [comment]
@AnshuPathak-88825 you mean the hand tool on the toolbar or the hand tool as a cursor pointer? For the former, there is a hand tool icon located on the right side of your screenshot. However, for the latter, it seems you are in responsive mode, which displays touch interactions rather than tool icons.
If I'm missing something please explain in more detail.

**Comment by AnshuPathak-88825** [comment]
[Screencast from 10-10-23 08:34:50 PM IST.webm](https://github.com/excalidraw/excalidraw/assets/78332454/c627540e-062c-4a3c-9154-21d2d978e8cb)

you can see when I decrease it's browser size then some of the icons disappear

**Comment by m-Chetan** [comment]
Its showing on the right side

**Comment by AnshuPathak-88825** [comment]
I'm sorry everyone I didn't noticed that hand pointer moved to right side

**Comment by AnshuPathak-88825** [comment]
it's working fine pls close this issue
