### ISSUE TITLE
Ready promise discontinued - why? How do I now perform actions after component is ready?

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#7267]
@ad1992 I have a set of actions performed after the component is ready. How are these to be handled without readyPromise?

- Additionally `ready` and `readyPromise` from the API have been discontinued. These APIs were found to be superfluous, and as part of the effort to streamline the APIs and maintain simplicity, they were removed in version v0.17.0.

**Comment by ad1992** [comment]
@zsviczian the `ready` and `readyPromise` were not really conveying whether component is ready to use (which should be happening after component is initialized and its ready to use) and now since its simply a callback so you should be able to achieve the same result using the `excalidrawAPI` as well (you have to use state - you can check the docs wip [here](https://docs-git-docs-next-excalidraw.vercel.app/docs/@excalidraw/excalidraw/api/props/excalidraw-api)), let us know if this doesn't work out for you.
However we plan to bring in `onReady` or something similar which will make sure that. the component is initialized and ready to use when triggered

**Comment by zsviczian** [comment]
@ad1992, you're awesome! Thanks for the quick answer.

this seems to have solved my issues, and yes, this looks much cleaner than readyPromise:
```typescript
export default function App() {
  const [excalidrawAPI, setExcalidrawAPI] = useState(null);
  return <Excalidraw excalidrawAPI={{(api)=> setExcalidrawAPI(api)}} />;
}
```

**Comment by ad1992** [comment]
> @ad1992, you're awesome! Thanks for the quick answer.
> 
> this seems to have solved my issues, and yes, this looks much cleaner than readyPromise:
> 
> ```ts
> export default function App() {
>   const [excalidrawAPI, setExcalidrawAPI] = useState(null);
>   return <Excalidraw excalidrawAPI={{(api)=> setExcalidrawAPI(api)}} />;
> }
> ```

That's Great 😊
