### ISSUE TITLE
Ctrl +Z occasionally don't work  

### ISSUE THREAD

**Issue by anton-kharchenko** [excalidraw/excalidraw#7324]
I don't know exactly after which doing this happened, however sometimes Ctrl+Z combination stop to work. Has someone the same problem?

**Comment by ryan-di** [comment]
Hey @antonKharchenko1997 did this happen to you when you're in collaboration mode? If so, this is a known limitation and we're working on improving it right now. If not, could you please provide some more info?

**Comment by antonKharchenko1997** [comment]
Hey @ryan-di I work in single mode. And if I will be honest, I even couldn't provide more details because it's happened occasionally, and I even didn't understand after which actions. However, after this happened, even reload page doesn't help. I thought, maybe someone has the same issue and know how to fix it or to escape this problem

**Comment by dwelle** [comment]
Working on it! 🙏

**Comment by antonKharchenko1997** [comment]
I know when it's going on. It's happened when I use only draw mode. Writing text working fine, but drawing sometimes lags. I hope it's help

**Comment by kirillrocks** [comment]
Still happening often.

**Comment by dwelle** [comment]
Closing in favor of https://github.com/excalidraw/excalidraw/issues/8003 — if this is a different issue, please open a new issue with more details or steps to reproduce. 🙏
