### ISSUE TITLE
Cyrillic issues in Virgil font

### ISSUE THREAD

**Issue by dchest** [excalidraw/excalidraw#747]
Unfortunately, the Cyrillic glyphs for Virgil have some issues:

* р looks a bit like ф (solution: move the curve a bit closer to p)
* ы looks like bl (solution: make the glyph the same height as "а" or "ч")
* в looks like b (solution: add top curve, like in B, but not as wide as the bottom one)
* д is a print variant, not a script/handwritten (should look more like g). It's acceptable, but uncommon

Here's a comparison with some handwritten styles from Google Fonts:
![fonts](https://user-images.githubusercontent.com/52677/74112768-aa768a00-4b9f-11ea-81d9-282540702dee.png)

(they have т written as m, but the Virgil variant is also common in such blackboard-style writing)

**Comment by thorn0** [comment]
Also:

* Ukrainian г and ґ look too similar. The upturn of the ґ should be much more noticeable.
* No support for Serbian and Macedonian Љ љ, Њ њ, Џ џ; Serbian ђ, ћ (only lowercase).

Besides, not Cyrillic, but the lowercase Turkish ı, just like its name implies, shouldn't have the dot. E.g., this is wrong ('Altın gün'):
![image](https://user-images.githubusercontent.com/94334/74146980-f3aff380-4c0a-11ea-92ea-1f10f1ed2d10.png)
Otherwise, support for Turkish is good. And to support Azerbaijani, the font needs to fix the ı issue and to add only two glyphs: Ə and ə.

**Comment by vjeux** [comment]
Ellinor made updates to the font based on this feedback. Could people that posted here look at the updated font and see if it works? https://easyupload.io/9281t7

**Comment by dchest** [comment]
It looks much better! Unfortunately, the uppercase "Д" is now wrong — sorry, I should have been more clear that only the lowercase one looks like "g", the uppercase one looks closer to Latin "D", but the one that was in the first version was also okayish.

<img width="793" alt="Screen Shot 2020-02-12 at 00 26 14" src="https://user-images.githubusercontent.com/52677/74289064-6239a200-4d2e-11ea-8e70-97afdd8b418b.png">


I'm not too familiar with Serbian and Ukrainian script styles, so can't comment on them.

PS Huge thanks to Ellinor for the work!

**Comment by vjeux** [comment]
@dchest, @thorn0: could you check the latest update here https://github.com/excalidraw/excalidraw/pull/764 ? Thanks!

**Comment by dchest** [comment]
To me `public/FG_Virgil.ttf` looks unchanged from my previous comment — same Д that looks like G. (Maybe it's caching in Font book?)

**Comment by thorn0** [comment]
* Pairings like гу, гі, гн, гю, etc. are hard to read because the letters collide with each other:
  ![image](https://user-images.githubusercontent.com/94334/74450471-c7a0a680-4e86-11ea-8636-41527da850b5.png)
  Would be good to have a bit more space after г.
* Љ is originally a ligature Л + Ь, so it should look similar to Л in the same font, but it doesn't:
  ![image](https://user-images.githubusercontent.com/94334/74452299-907fc480-4e89-11ea-9944-caf547d7194f.png)
  This shape of it doesn't really look handwritten.
* As dchest wrote, the original uppercase Д was good, not sure we need to change it to D.
