### ISSUE TITLE
Update existing shared link

### ISSUE THREAD

**Issue by azz** [excalidraw/excalidraw#749]
If I have shared a link with someone, then continue working on the diagram, I would like to be able to update the drawing that it points to (effective "save" instead of "save as..."). Is this possible with the (awesome!) E2E encryption?

**Comment by vjeux** [comment]
e2e encryption doesn't really change much. The challenge is more about authentication. You must prove that you are the owner of the particular id so you can change it. Because we don't have a notion of ownership right now, we can't really do that.

I'm not sure we want to start adding authentication right now. We now have collaboration mode that partially addresses this. I'll go ahead and close this for now.
