### ISSUE TITLE
Add “pan mode” to move canvas by dragging

### ISSUE THREAD

**Issue by j-f1** [excalidraw/excalidraw#794]
This would also allow single-finger panning on mobile.

**Comment by dwelle** [comment]
There already is such a mode and you can do so in two ways:

- spacebar + drag
- wheel (click & hold down) + drag

Or were you thinking of something different?

**Comment by j-f1** [comment]
I was thinking of just regular dragging with nothing held down.

**Comment by dwelle** [comment]
I see. Yes, I can see value in having a special tool (:hand:) to move the canvas, though I'm not sure if it won't add unnecessary clutter (though if no one knows about the shortcuts, then it is necessary indeed). WTBS, maybe adding it to the hint manager when you have `selection` tool active should be enough.

For mobile though, yea.

**Comment by dwelle** [comment]
I reckon three-finger drag can't be easily implemented in browsers, right?

**Comment by j-f1** [comment]
I doubt it. Two-finger scroll already works though.

**Comment by vjeux** [comment]
I feel like the current behavior on mobile is not optimal. The only way to move around is with two fingers pan, unfortunately I can't be precise enough to be strictly parallel so end up zooming slightly in and out.

The downside is that our currently drawing method is very inefficient when zooming. This means that the experience feels very choppy and slow.

Single finger pan when not selecting an element, double finger pan + zoom in case the entire screen is composed of elements. The only thing remaining is rectangle selection. I don't really know what to do about that :(

**Comment by j-f1** [comment]
> The downside is that our currently drawing method is very inefficient when zooming. This means that the experience feels very choppy and slow.

I think the problem is that zoom is rounded to the nearest `.01`. Maybe we should only do that after the user releases, or not at all.

**Comment by dwelle** [comment]
I think the reason is performance like vjeux suggested. I have very laggy experience on my mid-end Android.

**Comment by heitara** [comment]
> I feel like the current behavior on mobile is not optimal. The only way to move around is with two fingers pan, unfortunately I can't be precise enough to be strictly parallel so end up zooming slightly in and out.
> 
> The downside is that our currently drawing method is very inefficient when zooming. This means that the experience feels very choppy and slow.
> 
> Single finger pan when not selecting an element, double finger pan + zoom in case the entire screen is composed of elements. The only thing remaining is rectangle selection. I don't really know what to do about that :(

Here is an idea - What do you think about adding a sticky "hand" icon (only on mobile only) under the "locker" icon (at the right edge). If a user clicks on it a one finger pan is activated. (Similar to holding SPACE key on a desktop.) You need a second click to deactivate it or a click on any of the tools.

**Comment by sehlhorst** [comment]
Really enjoying Excalidraw (I use the Obsidian plugin), thank you.

A weird corner case - on Lenovo Thinkpad, the mouse (trackpoint) is part of the keyboard, and does not simultaneously register key press and mouse movement.  Because of this, I cannot hold down space and use the mouse (trackpoint) to pan.  Having a "move mode" similar to mural.co would make Excalidraw usable on my laptop.  Even if it were a configurable option to enable / disable this control to avoid the clutter (vs. making it mobile only), it would be great. 

Thanks again

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/6141 🖖

**Comment by kylevernyi** [comment]
Hello. I am wondering if it is possible to change the default behavior of the "sticky hand" on mobile. For reference I am on a S-Tab 7+. I am also using Excalidraw through Obsidian.

Desired behavior: When in drawing mode with my S Pen, 1 finger panning should work. This requires the app to differentiate between my pen input and my finger input. This is the default behavior in Samsung Note for example and it works really nicely.

Current behavior: One finger panning is not supported so I am forced to use 2 finger panning. 2 finger panning is very bad as mentioned above. Since you can never move exactly parallel, the screen zooms in and out very quickly.

Perhaps this is an option somewhere already?
