### ISSUE TITLE
Control-Z working only on English keyboard

### ISSUE THREAD

**Issue by kirillrocks** [excalidraw/excalidraw#8003]
Hey!

I am using 4 different languages, but for Control-Z to work, I always have to go back to the English layout. On Russian/Ukrainian/Dutch it is not working.

This is the only tool that has that limitation.

**Comment by Mrazator** [comment]
Hi @kirillrocks! Does it mean that when you are on English layout, it works just sometimes or it always works with English layout, but not the other ones mentioned? Asking due to the comment in https://github.com/excalidraw/excalidraw/issues/5375#issuecomment-2104348111

**Comment by Mrazator** [comment]
Could you reproduce the issue on excalidraw.com? Trying out dutch layout on Chrome, MacOS (command + z) and I can't reproduce it.

**Comment by kirillrocks** [comment]
Hey @Mrazator. Can reproduce on Excalidraw.com. 

There is another issue with command+z that sometimes it just losing it's memory (even with manually clicking on redo/undo). But this issue is specific to the language.

I am on Windows10, Chrome(latest version).

**Comment by kirillrocks** [comment]
@Mrazator, can you try the non-Latin alphabet? Maybe Cyrilic?

**Comment by Mrazator** [comment]
I could try with non-Latin but not sure if I will be pressing the right keys :) Could you please provide us with explicit repro steps?

**Comment by Mrazator** [comment]
Similar to Dutch, switching to Russian layout works as expected for me, with "Z" being in the same position in both. Interestingly Dutch-Belgium has intertchanged "Z" with "W", so it instead closes the tab. I suspect that some combination of pressed keys (i.e. due to switching languages) could lead to refresh (like CTRL+R), but I guest you would notice the tab would close / reload, unless it's some kind of silent refresh.

**Comment by dwelle** [comment]
@kirillrocks in order to identify the issue, we need to separate the "ctrl-z doesn't work on non-english layout" from "undo sometimes doesn't work at all (from UI)".

If you can reproduce the latter, please open up a new issue with steps. Also make sure that your browser isn't being reloaded as @Mrazator suggested could be happening.

As for making the shortcut work on non-english layout, we'll investigate what we can do.

**Comment by zadeviggers** [comment]
I have a similar issue on mac (firefox) where crtl+Z works, but command+Z doesn't work (which is the norm on macos). It could be a similar problem.

**Comment by Mrazator** [comment]
@zadeviggers which keyboard layout are you using? cannot reproduce with the default US layout (with mac & firefox).
<img width="645" alt="Screenshot 2024-07-28 at 13 44 21" src="https://github.com/user-attachments/assets/9a11adf2-7d8a-4702-baea-e869cecaaba6">

**Comment by zadeviggers** [comment]
That's very odd. I just tried again, using both the US keyboard layout and the Māori keyboard I use sometimes, and now it works as expected. My guess is there was a browser bug since I just installed a new patch update for Firefox.

**Comment by Dementir** [comment]
@Mrazator Hello i try use cyrillic keyboard and ctrl + z don't work. I checked last version Firefox (129.0.2 (64-bit)) and Chrome (128.0.6613.114 (Official Build) (64-bit)) 

proof https://youtu.be/NCdzJwvzAoA
