### ISSUE TITLE
Drawing zoomed to NaN and so drawing disappears and you can no longer draw

### ISSUE THREAD

**Issue by AaronRobinson** [excalidraw/excalidraw#804]
This has happened a couple of times now. While working normally the drawing disappears. Trying to draw anything further doesn't get retained on page. You can type text but on return it disappears. You can draw a line or any of the other shapes. The Zoom % shows NaN. I only realised the significance of this when I tried clicking on the zoom in. The Zoom % went to 10% and I could see a my tiny drawing. The text I had type that disappeard was now there too.

So looks like something is triggering the Zoom to go to NaN and this results in the drawing not rendering. You just need to Zoom in and restore to original size.

This is on the Brave browser. I can see no network or console errors.

**Comment by j-f1** [comment]
I figured out how to reproduce. Drag your cursor from the canvas outside of the window, then click in the canvas.

**Comment by j-f1** [comment]
And here’s why it happened: `pointerdown` unconditionally adds the new pointer to the list of currently pressed pointers, and `pointermove` looks up all the pointers with a given ID and sets their location. Since the pointer wasn’t properly removed when dragging outside of the window, clicking created two pointers with the same ID and updated them to have the same location. Next, the system detected two pointers and initialized a gesture. This gesture had the initial distance between the pointers set to 0, and we divide by the current distance by the initial distance while setting the zoom.

The fix was to remove the pointer whenever it can no longer be tracked, but it might be good to add some checks to `pointerdown` to make sure we don’t duplicate pointer IDs in the list.
