### ISSUE TITLE
PNG Export puts arrow with label in the wrong spot.

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#8058]
Somebody reported within Meta that the arrow position when exporting a diagram to png was off. I made a small repro with just three shapes to show the problem:

<img width="563" alt="image" src="https://github.com/excalidraw/excalidraw/assets/197597/0ac832f2-15ff-419a-b7ae-1459a58b63e3">

* Go to https://excalidraw.com/#json=O9jEqYDAmq3NqgWtoy8a0,XvJyVF9uM2lhrgv7Gsbi9g
* Right click on the scene > Copy clipboard as PNG
* Paste

You can see that the green arrow is not behind the 100ms text but many pixels above.

**Comment by vjeux** [comment]
@ad1992, not sure if you're aware of this.

**Comment by dwelle** [comment]
@vjeux arrow constructed programmatically?

**Comment by vjeux** [comment]
I don’t believe so.

**Comment by ad1992** [comment]
Interesting, I wasn't aware of this.  We don't store the label coordinates in text json and instead decide at the time of render so I am not sure why this would happen if it's not created programmatically, unless due to some changes pushed, we were unable to restore the arrow from older versions correctly
