### ISSUE TITLE
Content doens't appear in slides

### ISSUE THREAD

**Issue by vasylkorchynskyi** [excalidraw/excalidraw#8084]
On screen you can see that there is a frame around content and current slide is selected. But slide just blank.
Is there any trick to fix it?

<img width="1512" alt="Screenshot 2024-05-30 at 14 45 21" src="https://github.com/excalidraw/excalidraw/assets/9628243/4e96ee77-6de4-4474-aafb-73dda68c0548">

Context:
- I have tried to create each slide by clicking `+ Create slide` - the same result
- I have tried duplicate frame and move it to target area - the same result

**Comment by ad1992** [comment]
cc @maielo @barnabasmolnar

**Comment by dwelle** [comment]
@vasylkorchynskyi currently the slide only shows content that's physically in the frame, meaning shapes that were added to frame by dragging them into it (or by resizing the frame over the content to include it).

![excal-adding-frame-children](https://github.com/excalidraw/excalidraw/assets/5153846/18ff64a0-a276-4584-a14c-2ea07156b334)

We'll be changing it so that slide includes even shapes that just overlaps the frame, over the coming days!

**Comment by twist-off** [comment]
Has this been implemented? Currently, it is impossibly to make a slide show of a flow chart, as it can never incorporate arrows next to the box that the slide is focused on. Excalidraw within Obsidian had this figured out, I would consider this broken, not a feature.
