### ISSUE TITLE
Focusing text elements can crash excalidraw

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#871]
Repro:
* Create a new drawing
* Add a text field, type something, press enter
* Click outside the text field to unselect it
* All elements disappear, zoom level goes to NaN%

Video here: https://drive.google.com/file/d/1-AVTDYvbM1Gr0JI4Oa0xjTt-Zzn0aQb5/view?usp=sharing

I believe that Excalidraw gets confused about whether it's currently in a panning gesture but I haven't thoroughly debugged the issue.

**Comment by j-f1** [comment]
I tested this on mobile and couldn’t reproduce. Maybe try reloading the page?

**Comment by Fausto95** [comment]
I could repro on desktop @j-f1 with the instructions above

**Comment by lissitz** [comment]
Consistent repro:
- Add a text field, type something
- Press F11 to go form windowed to fullscreen mode/Windows key on Windows
- Click outside the text element , zoom level goes to NaN%

Probably related, pressing the Menu key instead makes the zoom go to 10%.

**Comment by dwelle** [comment]
Can't repro using any of the steps above, but will check the code tomorrow if I see something obvious.

**Comment by lissitz** [comment]
the issue seems to appear in https://github.com/excalidraw/excalidraw/blob/c89584832d1aedc8316789c29107dad20b5eb9f1/src/components/App.tsx#L1719-L1736
, intially the gesture.pointers.length is 2 but by the time scale factor is calculated 
gesture has been modified. Usually initialDistance is null and pointers is an empty array, so scaleFactor is NaN.

**Comment by petehunt** [comment]
fixed in #877
