### ISSUE TITLE
Right click paste command does not work for images

### ISSUE THREAD

**Issue by leoncurchack** [excalidraw/excalidraw#8826]
Tried to paste with right click and paste command, but it doesn't work.

**Comment by JodhwaniMadhur** [comment]
Is there any discussion for this or can i take this up?

**Comment by leoncurchack** [comment]
Sure.  Let me know what you can do.


------ Original Message ------
From "Madhur Jodhwani" ***@***.***>
To "excalidraw/excalidraw" ***@***.***>
Cc "leoncurchack" ***@***.***>; "Author" 
***@***.***>
Date 11/22/2024 9:39:21 PM
Subject Re: [excalidraw/excalidraw] Right click paste command does not 
work for images (Issue #8826)

**Comment by JodhwaniMadhur** [comment]
Hello @Mrazator @ad1992 @dwelle ,
had a quick question. 

When we paste from the right click, we refer to `createPasteEvent` in `clipboard.ts` while when pasting from Keyboard, we use `pasteFromClipboard` in `App.tsx`. Why is that? 

Why can't we move the part that pastes to a seperate function in maybe utils or somewhere else? from where both the files can call it? 

I understand that one is an event and other isn't but when I did some simple debugging, I found that the files in the createPasteEvent are undefined for some reason but when I check the same in `App.tsx` it is well formatted and contains data. 

Note: Just a rookie here trying to learn, contribute to Open Source with not much indepth knowledge of coding of this project. Also, it would be grateful if you could tell me how to debug excalidraw in VS Code.

**Comment by Mrazator** [comment]
> When we paste from the right click, we refer to createPasteEvent in clipboard.ts while when pasting from Keyboard, we use pasteFromClipboard in App.tsx. Why is that?

We use `pasteFromClipboard`, also when pasting manually through context menu and the input is result from `createPasteEvent`. If the question is why we are running `createPasteEvent`, then it's likely due to the browser emitting the event automatically on `ctrl/cmd + v`, while we need to "emit" it manually when triggered through the context menu.

> Also, it would be grateful if you could tell me how to debug excalidraw in VS Code.

The most straightforward is debugging through the Chrome devtools (opening "Sources" tab, clicking on file you want to debug and adding a breakpoint).
